### ISSUE TITLE
Support storing Bundle resources with type "searchset"

### ISSUE THREAD

**Issue by seanmcilvenna** [hapifhir/hapi-fhir#1288]
**Describe the bug**
When I POST a Bundle which a Bundle.type of "searchset", I get the following error in response:

```xml
<OperationOutcome xmlns="http://hl7.org/fhir">
    <text>
        <status value="generated"/>
        <div xmlns="http://www.w3.org/1999/xhtml">
            <h1>Operation Outcome</h1>
            <table border="0">
                <tr>
                    <td style="font-weight: bold;">ERROR</td>
                    <td>[]</td>
                    <td>
                        <pre>Unable to store a Bundle resource on this server with a Bundle.type value of: searchset</pre>
                    </td>
                </tr>
            </table>
        </div>
    </text>
    <issue>
        <severity value="error"/>
        <code value="processing"/>
        <diagnostics value="Unable to store a Bundle resource on this server with a Bundle.type value of: searchset"/>
    </issue>
</OperationOutcome>
```

Both Rick and Lloyd agree that Bundles with a type of "searchset" should be able to be stored in HAPI. We need to be able to store examples of searchset bundles on the FHIR server.

**To Reproduce**
```
POST <base>/Bundle
<?xml version="1.0" encoding="UTF-8"?>
<Bundle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://hl7.org/fhir fixed/fhir-all-xsd/bundle.xsd" xmlns="http://hl7.org/fhir">
    <!--Start of header elements-->
    <id value="read-error-example"/>
    <meta>
        <lastUpdated value="2018-08-20T16:37:08-05:00"/>
    </meta>
    <type value="searchset"/>
    <total value="0"/>
    <link>
        <relation value="self"/>
        <url value="http://localhost/fhir-stu3/1.0.1/Organization?_format=xml"/>
    </link>
</Bundle>
```

**Expected behavior**
Successfully store the Bundle with a type of "searchset"

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.7.0 (both DSTU3 and R4)
 - OS: Linux
 - Browser: Chrome

**Comment by jamesagnew** [comment]
What would be the use case for storing a search set? Wouldn't it be better to convert it to a `collection`?

**Comment by rgeimer** [comment]
We are trying to store all content related to an ImplementationGuide resource, and that includes examples of query results (i.e. a Bundle where type=searchset).

**Comment by rgeimer** [comment]
Our workaround right now is to comment out type=searchset, add type=collection, then when we export to run the IG publisher we have to manually remove the collection type and uncomment out the searchset type. It is a real pain.

**Comment by patrick-werner** [comment]
If this would be allowed (which i support) you will run into issue #1250

**Comment by seanmcilvenna** [comment]
I believe this is fixed now in the hapi-fhir-jpaserver-starter project. You can configure it to allow storing various types of bundles, including "searchset".

**Comment by fergusleen** [comment]
Apologies for reopening this, but how do we configure the jpa server to store a searchset bundle? I say this as someone starting with hapifhir. The use case is I am manually copying data from a custom plain server into a jpa server, using the transaction field on the home page of the jpa server.

**Comment by CzarMich** [comment]
> I believe this is fixed now in the hapi-fhir-jpaserver-starter project. You can configure it to allow storing various types of bundles, including "searchset".

@seanmcilvenna  I have not really be successful in configuring the server to accept  bundle type, especially "searchset". Anybody willing to elaborate this further or point me to a resource where this is mentioned/ explained. 
Thanks a bunch.
