### ISSUE TITLE
Search doesn't return correct resources

### ISSUE THREAD

**Issue by jarimayenburg** [hapifhir/hapi-fhir#1384]
**Describe the bug**

We're developing a PHR to be used by patients and healthcare professionals in the Netherlands. Sometimes, when I try to search for resources within the context of a Patient (so using the subject field), the returned Bundle doesn't contain all the resources I'd expect (most of the times, it returns an empty Bundle).

**Screenshots**

This is the resource I'm trying to find:
```json
{
  "resourceType":"Condition",
  "id":"gpdata-condition-icpc-d02",
  "meta":{
    "versionId":"1",
    "lastUpdated":"2019-07-15T10:15:08.000+02:00",
    "profile":[
      "http://nictiz.nl/fhir/StructureDefinition/zib-Problem"
    ],
    "security":[
      {
        "system":"http://hl7.org/fhir/v3/ActReason",
        "code":"HTEST",
        "display":"Touchstone test data"
      }
    ]
  },
  "text":{
    "status":"additional",
    "div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><thead><tr><th>ProbleemType</th><th>ProbleemNaam</th><th>Probleem BeginDatum</th><th>ProbleemStatus</th><th>Toelichting</th></tr></thead><tbody><tr><td>Diagnosis</td><td>Maagpijn</td><td>2019-04-02</td><td>Inactief (sinds 2019-04-07)</td><td></td></tr></tbody></table></div>"
  },
  "clinicalStatus":"inactive",
  "category":[
    {
      "coding":[
        {
          "system":"http://snomed.info/sct",
          "code":"282291009",
          "display":"Diagnosis"
        }
      ]
    }
  ],
  "code":{
    "coding":[
      {
        "system":"http://hl7.org/fhir/sid/icpc-1-nl",
        "code":"D02",
        "display":"Maagpijn"
      }
    ]
  },
  "subject":{
    "reference":"Patient/gpdata-patient-kwalificatie1",
    "display":"Jacqueline XXX_Cevat"
  },
  "onsetPeriod":{
    "start":"2019-04-02"
  },
  "abatementDateTime":"2019-04-07",
  "asserter":{
    "extension":[
      {
        "url":"http://nictiz.nl/fhir/StructureDefinition/practitionerrole-reference",
        "valueReference":{
          "reference":"PractitionerRole/gpdata-practitionerrole-kwalificatie1",
          "display":"Dr. V. Huisarts 1"
        }
      }
    ],
    "reference":"Practitioner/gpdata-practitioner-kwalificatie1",
    "display":"V. Huisarts 1"
  }
}
```

This is the request I'm executing:
`GET http://URL_TO_SERVER/fhir/Condition?subject:Patient=gpdata-patient-kwalificatie1`

This is the result:
```json
{
  "resourceType": "Bundle",
  "id": "c964ec54-8cb2-45d1-9ab0-02a186dffb8d",
  "meta": {
    "lastUpdated": "2019-07-15T20:12:49.108+02:00"
  },
  "type": "searchset",
  "total": 0,
  "link": [
    {
      "relation": "self",
      "url": "http://URL_TO_SERVER/fhir/Condition?subject%3APatient=gpdata-patient-kwalificatie1"
    }
  ]
}
```

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.7.0
 - OS: HAPI is running in a Docker container running a Jetty image (jetty:9-jre8-alpine). The Docker container is running on Arch Linux (x86_64 Linux 5.0.13-arch1-1-ARCH)
 - Browser: None, server is tested using plain HTTP requests with Insomnia.

**Additional context**
We're loading a lot of resources in in quick succession for testing purposes, maybe that has something to do with it. Also, for ease of development, I haven't implemented any authorization yet.

**Comment by jamesagnew** [comment]
Are you able to reproduce this on our public server? Also, have you tried using the latest HAPI FHIR?

**Comment by jarimayenburg** [comment]
I wasn't able to reproduce it on the public server, let me upgrade to the latest version to find out whether that fixes the issue.

**Comment by jarimayenburg** [comment]
I have upgraded to the latest version and that doesn't resolve the problem. I think it has something to do with the placeholder resources that are created, or perhaps it's because we don't enforce referential integrity on write?

**Comment by jarimayenburg** [comment]
I have re-enabled the config to enforce referential integrities on write and added `_include`s to the test searches, to make sure the Patient resource is included and after doing that, I'm able to find all data within the context of this patient. So it appears that the resources can't be found if referential integrity is not enforced and placeholder resources are created automatically.
