### ISSUE TITLE
Creation of a resource removes the narrative from contained resources

### ISSUE THREAD

**Issue by GeorgeNistorCernerBv** [hapifhir/hapi-fhir#1466]
When creating a resource that includes a contained resource, the narrative from the contained resource is removed by the HAPI server code. That is a direct consequence of [https://github.com/jamesagnew/hapi-fhir/issues/33](https://github.com/jamesagnew/hapi-fhir/issues/33). 

The HAPI issue referenced in the comment is from 2014, so it was based on the DSTU1 specification: [http://www.hl7.org/implement/standards/fhir/DSTU1/narrative.html](http://www.hl7.org/implement/standards/fhir/DSTU1/narrative.html).
In that specification, it is true that the Narrative was not supposed to exist in contained resources.
In the R4 specification though, such a sentence cannot be found anymore ( [http://www.hl7.org/implement/standards/fhir/narrative.html](http://www.hl7.org/implement/standards/fhir/narrative.html) ).
At this link: [https://www.hl7.org/fhir/references.html#contained](https://www.hl7.org/fhir/references.html#contained) we find the explicit mention that: 

> Like other resources, contained resources can contain narrative

The narrative of a contained resource should remain there and not be stripped by the FHIR server anymore. 

- HAPI FHIR Version: 3.8.0
- FHIR version: 4

**Comment by noergelsef** [comment]
> "Like other resources, contained resources can contain narrative"

But in FHIR 4.0.1 the sentence continues with

>However, when rendering the containing resource, the narrative of the contained resources is ignored, so relevant information about contained resources SHALL appear in the narrative of the containing resource.

HAPI FHIR R4 5.0.2 still does no render the narrative text in a contained resource, but that sounds correct for me since following the 4.0.1 spec.

Ref. [https://www.hl7.org/fhir/references.html#contained](https://www.hl7.org/fhir/references.html#contained)

**Comment by noergelsef** [comment]
But unfortunately the German NHS KBV has set the text in their resources inherited from AuditEvent to max value = 0 and expect the narrative text in the contained resource.

- [KBV_PR_AW_Report_Import](https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Report_Import)
- [KBV_PR_AW_Report_Export](https://fhir.kbv.de/StructureDefinition/KBV_PR_AW_Report_Export)

**Comment by florianboemmel** [comment]
@noergelsef, @GeorgeNistorCernerBv did you found a solution for this issue?

**Comment by GeorgeNistorCernerBv** [comment]
Hello, @florianboemmel ! I did not find any solution, as I am not working at a FHIR implementation anymore (at least, for the time being).

**Comment by florianboemmel** [comment]
> Hello, @florianboemmel ! I did not find any solution, as I am not working at a FHIR implementation anymore (at least, for the time being).

Thank you for your quick reply!

**Comment by patrick-werner** [comment]
> Hello, @florianboemmel ! I did not find any solution, as I am not working at a FHIR implementation anymore (at least, for the time being).

Thanks for reporting and pointing to the issue/commit when this was added. As hapi doesn't support DSTU1 anymore, and the current behaviour isn't corrrect. I will create a PR re-enable narratives in contained resources
