### ISSUE TITLE
Resource.meta.extension not persisted

### ISSUE THREAD

**Issue by seanmcilvenna** [hapifhir/hapi-fhir#1477]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**
HAPI does not persist Resource.meta.extension.

**To Reproduce**
1. POST or PUT a resource that has at least one Resource.meta.extension specified.
2. When HAPI responds, it shows the resource the same as how it was submitted (WITH the Resource.meta.extension).
3. Do a GET on the resource that is now persisted. The Resource.meta.extension is gone.

**Expected behavior**
HAPI *should* persist Resource.meta.extension.

**Comment by jamesagnew** [comment]
Extensions in the `Resource.metadata` element are deliberately not persisted currently by the JPA server. We currently purge the metadata section before persisting, as all of its properties are things that are generated from data elsewhere in the database.

I've actually seen a few applications that take advantage of this fact, by using this as a spot where processing directives and outcome details are read/written by interceptors.

This could be a configurable thing though I suppose..

**Comment by umberto-cappellini** [comment]
I guess storing meta could be very useful to compare lastUpdated with an incoming resource to decide whether to update the resource or not.

**Comment by jamesagnew** [comment]
This will be fixed as a part of https://github.com/hapifhir/hapi-fhir/pull/2481
