### ISSUE TITLE
Units of time value set missing during validation

### ISSUE THREAD

**Issue by Henni16** [hapifhir/hapi-fhir#1659]
**Describe the bug**
When trying to validate a [FHIR Medication Statement object](https://www.hl7.org/fhir/medicationstatement.html) which uses the unit of time "d" the validator throws the following error:
```java.lang.AssertionError:SingleValidationMessage[col=732,row=1,locationString=MedicationStatement.dosage[0].timing.repeat.periodUnit,message=The value provided ('d') is not in the value set http://hl7.org/fhir/ValueSet/units-of-time|4.0.0 (http://hl7.org/fhir/ValueSet/units-of-time, and a code is required from this value set) (error message = Unknown code[d] in system[(none)]),severity=error]```

**To Reproduce**
1. Use [this example](https://www.hl7.org/fhir/medicationstatementexample1.json.html) of a Medication Statement
2. Create a HAPI validator as follows:
```java
FhirContext ctx = FhirContext.forR4();

IParser parser = ctx.newJsonParser();

parser.setParserErrorHandler(new StrictErrorHandler());

try (BufferedReader reader = Files.newBufferedReader(filePath, StandardCharsets.UTF_8)) {
      T bundle = parser.parseResource(resourceType, reader);

       FhirValidator validator = ctx.newValidator();

       validator.registerValidatorModule(new FhirInstanceValidator());

       return validator.validateWithResult(bundle);
}
```
3. Run the validator

**Expected behavior**
Validator accepts the object.

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.1.0
 - OS: MacOS

**Comment by mfjarvis** [comment]
I experienced exactly this issue. I believe it's a bug in the `InMemoryTerminologyServerValidationSupport`. It doesn't support the code system `http://unitsofmeasure.org`. That in itself is fine as there's a fallback which will still consider a code valid as long as the code and system both match the `ValueSet`. Unfortunately, while this works for a `Coding` which has a code system, here we only have a primitive `code` which doesn't. So this second check also fails, resulting in every unit of time being considered invalid.

I managed to work around it in my case by extending the validation class:
```
val supportChain = ValidationSupportChain(
            DefaultProfileValidationSupport(fhirContext),
            object : InMemoryTerminologyServerValidationSupport(fhirContext) {
                    override fun validateCodeInValueSet(theValidationSupportContext: ValidationSupportContext?, theOptions: ConceptValidationOptions?, theCodeSystem: String?, theCode: String?, theDisplay: String?, theValueSet: IBaseResource): IValidationSupport.CodeValidationResult {
                        val valueSetUrl = CommonCodeSystemsTerminologyService.getValueSetUrl(theValueSet)
                        if (valueSetUrl == "http://hl7.org/fhir/ValueSet/units-of-time") {
                            return super.validateCodeInValueSet(theValidationSupportContext, theOptions, "http://unitsofmeasure.org", theCode, theDisplay, theValueSet)
                        }
                        return super.validateCodeInValueSet(theValidationSupportContext, theOptions, theCodeSystem, theCode, theDisplay, theValueSet)
                    }
                },
            SnapshotGeneratingValidationSupport(fhirContext)
        )
```

**Comment by jamesagnew** [comment]
Is this still in issue in HAPI FHIR 5.1.0? UCUM support was significantly
enhanced in that version.

**Comment by mfjarvis** [comment]
The first thing I tried was bumping everything to 5.1.0, so I believe it's still an issue unless I'm doing something wrong.

**Comment by mfjarvis** [comment]
My case at least was user error. I needed a `CommonCodeSystemsTerminologyService` in my validation chain in addition to the `InMemoryTerminologyServerValidationSupport` I was using.

**Comment by jamesagnew** [comment]
Thanks @mfjarvis - I'm going to close this. Please feel free to comment if the issue comes back.
