### ISSUE TITLE
Raise an error if _include is used on a read

### ISSUE THREAD

**Issue by jamesagnew** [hapifhir/hapi-fhir#1774]
A common mistake is trying to use the `_include` search parameter on a read. I'd like to help people realize their mistake by specifically raising a helpful error when this happens.

This could probably be done right inside ReadMethodBinding.

Might be worth looking at the FHIR Search page to identify any other candidates (revinclude, count, maybe others?)

**Comment by tadgh** [comment]
here's the list of search result parameters, which I imagine means they should only be used on searches:

![](https://i.gyazo.com/7efac40eb5727f87a442b1edf2222567.png)

**Comment by jamesagnew** [comment]
_elements and _summary actually are supported, since they only filter the
response resource. Technically the FHIR spec doesn't require this, but we
do it to be nice :)

**Comment by dmuylwyk** [comment]
Closing. This was addressed in https://github.com/hapifhir/hapi-fhir/pull/1786
