### ISSUE TITLE
Failed to build HAPI FHIR - Docker

### ISSUE THREAD

**Issue by sjagadee** [hapifhir/hapi-fhir#1803]
Failed to build HAPI FHIR

Steps to reproduce
downloaded the project from the git 
go to project directory and did: docker-compose build

[INFO] Reactor Summary for HAPI-FHIR 5.0.0-SNAPSHOT:
[INFO]
[INFO] HAPI-FHIR .......................................... SUCCESS [ 48.107 s]
[INFO] HAPI FHIR - Deployable Artifact Parent POM ......... SUCCESS [ 59.944 s]
[INFO] HAPI FHIR BOM ...................................... SUCCESS [  1.608 s]
[INFO] HAPI FHIR - Core Library ........................... SUCCESS [01:48 min]
[INFO] HAPI FHIR - Server Framework ....................... SUCCESS [ 18.899 s]
[INFO] HAPI FHIR - Validation Resources (DSTU3) ........... SUCCESS [  5.457 s]
[INFO] HAPI FHIR - Client Framework ....................... SUCCESS [ 12.821 s]
[INFO] HAPI FHIR Test Utilities ........................... SUCCESS [ 29.984 s]
[INFO] HAPI FHIR Structures - DSTU3 ....................... SUCCESS [ 26.218 s]
[INFO] HAPI FHIR - Validation Resources (FHIR R4) ......... SUCCESS [  6.510 s]
[INFO] HAPI FHIR Structures - FHIR R4 ..................... SUCCESS [ 36.973 s]
[INFO] HAPI FHIR - Validation Resources (DSTU2) ........... SUCCESS [  3.364 s]
[INFO] HAPI FHIR Structures - HL7.org DSTU2 ............... SUCCESS [ 15.084 s]
[INFO] HAPI FHIR - Validation Resources (FHIR R5) ......... SUCCESS [  3.625 s]
[INFO] HAPI FHIR Structures - FHIR R5 ..................... SUCCESS [ 17.172 s]
[INFO] HAPI Tinder Plugin ................................. SUCCESS [01:00 min]
[INFO] HAPI FHIR Structures - DSTU2 (FHIR v1.0.0) ......... SUCCESS [01:04 min]
[INFO] HAPI FHIR - Validation Resources DSTU2.1 (2016May) . SUCCESS [  3.026 s]
[INFO] HAPI FHIR Structures - DSTU2.1 (2016May) ........... SUCCESS [ 17.556 s]
[INFO] HAPI FHIR - Converter .............................. SUCCESS [ 10.981 s]
[INFO] HAPI FHIR - Validation ............................. SUCCESS [ 20.995 s]
[INFO] HAPI FHIR OkHttp Client ............................ SUCCESS [ 10.290 s]
[INFO] HAPI FHIR JAX-RS Server ............................ SUCCESS [ 18.651 s]
[INFO] HAPI FHIR Search Parameters ........................ SUCCESS [ 19.858 s]
[INFO] HAPI FHIR JPA API .................................. SUCCESS [  9.927 s]
[INFO] HAPI FHIR Subscription Server ...................... SUCCESS [ 18.648 s]
[INFO] HAPI FHIR JPA Server ............................... SUCCESS [04:12 min]
[INFO] HAPI FHIR TestPage Overlay ......................... SUCCESS [ 30.021 s]
[INFO] HAPI FHIR - Docs ................................... SUCCESS [  9.922 s]
[INFO] HAPI Tinder Plugin - Test Project .................. SUCCESS [01:05 min]
[INFO] hapi-fhir-igpacks .................................. SUCCESS [ 12.584 s]
[INFO] HAPI FHIR JAX-RS Server - Example .................. SUCCESS [ 25.106 s]
[INFO] HAPI FHIR JPA Server - Migration ................... SUCCESS [ 59.067 s]
[INFO] HAPI FHIR Sample RESTful Server .................... SUCCESS [  7.176 s]
[INFO] HAPI FHIR - fhirtest.uhn.ca Deployable WAR ......... FAILURE [ 23.059 s]
[INFO] HAPI FHIR - Android ................................ SKIPPED
[INFO] HAPI FHIR - Command Line Client - Server WAR ....... SKIPPED
[INFO] HAPI FHIR - Command Line Client - API .............. SKIPPED
[INFO] HAPI FHIR - Command Line Client - Base Project ..... SKIPPED
[INFO] HAPI FHIR - Command Line Client - Application ...... SKIPPED
[INFO] HAPI FHIR - Distribution Archive ................... SKIPPED
[INFO] HAPI FHIR JAX-RS Server Kotlin test ................ SKIPPED
[INFO] HAPI FHIR - Minimal Dependency Test - Client ....... SKIPPED
[INFO] HAPI FHIR - Minimal Dependency Test - Server ....... SKIPPED
[INFO] hapi-fhir-spring-boot-autoconfigure ................ SKIPPED
[INFO] hapi-fhir-spring-boot-starter ...................... SKIPPED
[INFO] hapi-fhir-spring-boot .............................. SKIPPED
[INFO] hapi-fhir-spring-boot-samples ...................... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-client-apache ......... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-client-okhttp ......... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-server-jersey ......... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-server-jpa ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19:20 min
[INFO] Finished at: 2020-04-17T07:58:26Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.2.3:war (default-war) on project hapi-fhir-jpaserver-uhnfhirtest: Error assembling WAR: Problem creating war: Execution exception: Java heap space -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :hapi-fhir-jpaserver-uhnfhirtest
ERROR: Service 'hapi-fhir-jpaserver-start' failed to build: The command '/bin/sh -c /tmp/apache-maven-3.6.2/bin/mvn install -DskipTests' returned a non-zero code: 1

OS: running it on windows 

Please help me solve this problem or point me if have to do anything differently. Thank you

**Comment by jamesagnew** [comment]
Our CI is currently passing, so I'm assuming this is something specific to your environment.

The error is complaining about running out of memory, does your docker container have appropriate memory settings?

**Comment by cspielmann** [comment]
hello same error here (version 7.4)
Running it on windows from intelliJ.
As I am not a specialist of docker, I expected run and forget. 
I have to allocate more memory to the docker container ? 
How could we do that ? in the docker file I supposed. at the level of maven ?

**Comment by cspielmann** [comment]
rerun docker-compose. Worked fine this time.
