### ISSUE TITLE
Support for :of-type Token Modifier

### ISSUE THREAD

**Issue by sqshq** [hapifhir/hapi-fhir#1892]
**Describe the issue**
Currently HAPI FHIR does not support `ofType` Token Modifier - there is no such enum value in the [TokenParamModifier](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/param/TokenParamModifier.java) and therefore ofType requests are not parsed correctly (contain empty modifier).

**Environment:**
 - HAPI FHIR Version: 4.2.0

Is there a reason why `:of-type` is not supported, or the enum value just needs to be added?

**Comment by jamesagnew** [comment]
I think that modifier is just newer than the enum is. 

No objections to adding it (feel free to submit a PR if you need it now)
