### ISSUE TITLE
(partitioned server) NullPointerException on BaseHapiFhirResourceDao when querying for non existing resource

### ISSUE THREAD

**Issue by umberto-cappellini** [hapifhir/hapi-fhir#1953]
In a partitioned server, a query for a non existing resource as following:
http://localhost:8080/partID/Patient/254

Returns an error:
"Failed to call access method: java.lang.NullPointerException"

This happens becuse in BaseHapiFhirResourceDao, the block:
```
		if (entity == null) {
			throw new ResourceNotFoundException(theId);
		}

```
Shall be placed before the block just above "Verify that the resource is for the correct partition" (there's a call to the null entity).

 - HAPI FHIR Version: 5.1.0-SNAPSHOT (master)

**Comment by umberto-cappellini** [comment]
@jamesagnew 
This is still happening on master branch.

**Comment by bbray** [comment]
+1
Just found this NPE bug in 5.2.0 as well, looks like a really simple fix.

**Comment by jamesagnew** [comment]
Whoops, agree that's an easy fix, thanks for the heads up!
