### ISSUE TITLE
Support Arbitrary resource MDM

### ISSUE THREAD

**Issue by tadgh** [hapifhir/hapi-fhir#2161]
Current EMPI implementation is useful for Patients/Practitioners, but there is large demand for Master Data Management over arbitrary resource types, e.g. medication, organization. 

To this end we should: 
1. Drop references to person, and instead rely directly on MPI_LINK table results. 
2. Replace usages of person with an instance of the same MDM'ed class. e.g. Patient links to Patient, Organization links to Organization. Note these links are now only maintained in the MPI_LINK table. 
3. Deprecate some of the MPI_LINK columns
4. Add MDM toggles on a per-resource basis. Maybe in the empi-rules.json itself?
5. Auto-create subscriptions based on these new MDM types.

**Comment by nvg-smile** [comment]
Reopening issue to complete in sync with CDR merge.
