### ISSUE TITLE
ApacheRestfulClientFactory does not use system properties for proxy configuration

### ISSUE THREAD

**Issue by paulleseute** [hapifhir/hapi-fhir#2192]
**Describe the bug**
`ApacheRestfulClientFactory` provide HTTP client whose proxy is not configured with system parameters (`http.proxyHost`, `http.proxyPorts`). Configuration must be done by hand:

```
String proxyHost = System.getProperty("http.proxyHost");
String proxyport = System.getProperty("http.proxyPort");
if (proxyHost != null && proxyport != null) {
    fhirContext.getRestfulClientFactory().setProxy(proxyHost, Integer.parseInt(proxyport));
}
```

On the other hand, the `OkHttpRestfulClientFactory` does take those system properties into account.
 
**Expected behavior**
HTTP client provided by `ApacheRestfulClientFactory` should consider proxy system parameters.

**Comment by jamesagnew** [comment]
This feels like it would be a reasonable addition. Would you be willing to
submit a PR with tests?

**Comment by vladonemo** [comment]
The http client can be built by calling `useSystemProperties()` method of the builder. This will then set the default proxy settings from the environment (`http(s).proxy(Host|Port)`) if not explicitly provided. However, this will also apply the default settings of:
- supported protocols (env. variable `https.protocols`)
- supported Cipher suites (env. variable `https.cipherSuites`)
- SSL connection factory 
- keep alive (env. variable `http.keepAlive` which defaults to `true`)
- http max connections (env. variable `http.maxConnections` which defaults to `5`)
- reuse strategy (depending on the variable `http.keepAlive`; defaults to `DefaultClientConnectionReuseStrategy` that is the same as if no reuse strategy configured)
- user agent header (env. variable `http.agent`)
- credentials provider (considering env. variables like `http.auth.ntlm.domain`, `http(s).proxyUser`, `http(s).proxyPassword`, etc)

By using system properties there will be no change in the current behaviour. Just that the following would be possible to alter with env. variables;
- reuse strategy
- user agent header
- proxy
All the others are explicitly provided in the `ApacheRestfulClientFactory`.

I'm happy to submit a PR if you like ;)

**Comment by vladonemo** [comment]
@jamesagnew, is this ok? Could you please review the PR?

**Comment by jamesagnew** [comment]
#2241 has been merged
