### ISSUE TITLE
upload-igpack command and documentation need to be deprecated

### ISSUE THREAD

**Issue by dmuylwyk** [hapifhir/hapi-fhir#2229]
Thanks, @KevinDougan-SmileCDR!

**Comment by KevinDougan-SmileCDR** [comment]
Actually, based on a comment James made in our meeting the other day, I am going to remove this feature entirely, rather than leave it in as "deprecated".

**Comment by KevinDougan-SmileCDR** [comment]
@jamesagnew   Implementing this change will ALSO impact the `smileutil validate` functionality, in that it will remove the ability to use the `--igpack [filename]` option, as described here: https://smilecdr.com/docs/smileutil/validate.html

Is this acceptable ?

**Comment by jamesagnew** [comment]
I think so. To be honest that command should probably also be removed
(hah)...

This command really supercedes it now:
https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator (Mark is
maintaining it too)
