### ISSUE TITLE
500 error on any request

### ISSUE THREAD

**Issue by JElgar** [hapifhir/hapi-fhir#2247]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**
Getting:
Error: HTTP 500 Server Error: Failed to call access method: org.springframework.dao.InvalidDataAccessApiUsageException: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled.
When hitting any endpoint

**To Reproduce**
1. Go to http://hapi.fhir.org/
2. Make any request eg: GET http://hapi.fhir.org/baseR4/Patient?_include=Patient:link&_sort=_id&_pretty=true
3. See 500 error

**Expected behavior**
200 + Response

**Environment (please complete the following information):**
 - HAPI FHIR Version: UHN_HAPI Server (R4 FHIR)
 - OS:  Mac Os + Android
 - Browser: Chrome + Postman

**Comment by tadgh** [comment]
Looks like this server has been since rebooted, thanks for the heads up!

**Comment by dermatologist** [comment]
It seems that the issue has resurfaced again. Another reboot would be highly appreciated.
Thanks!
