### ISSUE TITLE
Upgrade hapi-fhir fhir_core_version dependency from 5.2.0 to 5.2.16

### ISSUE THREAD

**Issue by KevinDougan-SmileCDR** [hapifhir/hapi-fhir#2307]
This is being driven by the upcoming CQL feature implementation.

The CQL Libraries recently upgraded their dependency to **v5.2.16** to eliminate a sub-dependency on several `info.cqframework` **v1.4.9-SNAPSHOT** JARs.

The CQL Libraries only use the FHIR CORE dependencies for the data model objects:
```
The hapi-fhir-structures are deeply baked into the cqf-tooling since those are 
the java representations of the fhir objects we use. Unless hapi splits the "POJO" representations 
of the objects apart and releases those separately from the server components OR the cqf-tooling 
rebuilds those java POJOS from scratch we'll be in this boat.
cql-engine, cql-evaluator, and cqf-tooling will have to depend on version N-1.
```

**Comment by jamesagnew** [comment]
Branch started for this: https://github.com/hapifhir/hapi-fhir/tree/ja_20210120_bump_core_version
