### ISSUE TITLE
Create via PUT for ImplementationGuide that references some placeholders

### ISSUE THREAD

**Issue by seanmcilvenna** [hapifhir/hapi-fhir#2332]
**Describe the bug**
When JPA server is configured to auto-create placeholder references and you PUT an ImplementationGuide that references a ValueSet resource that doesn't exist, you get the following error:

```
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>ValueSet has no value for ValueSet.url</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "ValueSet has no value for ValueSet.url"
    }
  ]
}
```

I believe this happens because it attempts to auto-create a ValueSet, and it is requiring that the ValueSet have a URL and throwing an exception because the placeholder ValueSet does not have a URL.

**To Reproduce**
1. Run HAPI JPA Server with "auto-create placeholder references" configured to "true"
2. PUT an ImplementationGuide that references a ValueSet that does not exist

**Expected behavior**
It should auto-create a placeholder ValueSet that the IG references and successfully create the ImplementationGuide.

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.2
 - OS: Ubuntu/Docker

**Comment by seanmcilvenna** [comment]
The same thing happens when POST/PUT'ing a resource that references a Bundle.
When HAPI tries to auto-create the Bundle, it fails saying "Bundle is missing type".

**Comment by jamesagnew** [comment]
We've been talking about adding a special HAPI FHIR extension automatically to any placeholder resources to mark them as placeholders.

The presence of that extension could probably be used to tell the system to ignore these checks.

**Comment by seanmcilvenna** [comment]
That makes sense to me. :) Looking forward to the change!

**Comment by jamesagnew** [comment]
Internal HubSpot ticket: 287283730

**Comment by fil512** [comment]
Fixed in https://github.com/hapifhir/hapi-fhir/pull/2423
