### ISSUE TITLE
Fix for CQL dependency issue in hapi-fhir-jpaserver-cql

### ISSUE THREAD

**Issue by gered** [hapifhir/hapi-fhir#2350]
`info.cqframework/quick` is a dependency of `info.cqframework/cql-to-elm` which hapi-fhir-jpaserver-cql depends on. But `info.cqframework/quick` is currently set with scope=runtime which is preventing it from being included in application builds that depend on hapi-fhir-jpaserver-cql.

**Comment by KevinDougan-SmileCDR** [comment]
This was merged in [PR-2351](https://github.com/hapifhir/hapi-fhir/pull/2351)
