### ISSUE TITLE
$document operation does not include Bundle.entry.fullUrl in response

### ISSUE THREAD

**Issue by seanmcilvenna** [hapifhir/hapi-fhir#2377]
**Describe the bug**
When using the `$document` operation, the response _should_ include Bundle.entry.fullUrl, but does not.

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.2.0
 - OS: Ubuntu server
 - Browser Postman

**Comment by tadgh** [comment]
Heya Sean, starting work on this now. Can you provide me just a sample composition resource and API request you are using? Will work it into the test case. 

Cheers,
