### ISSUE TITLE
Encounter.reasonReference is not parsed

### ISSUE THREAD

**Issue by flodpanter** [hapifhir/hapi-fhir#2399]
**Describe the bug**
Using R5, when parsing a json representation of an Encounter, the reasonReference is not parsed.  It looks to be related to a mismatch in naming as the name of the property is not **reasonReference**, but **reason**.

**To Reproduce**
1. Run the test below that reproduces the issue

**Expected behavior**
- The reasonReference is parsed 
- Maybe the reason property of the Encounter should be renamed or a new property added 

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.3.0 (also seen the issue in 5.2.0 and 5.1.0)
 - OS: Win 10

**Test that reproduces the issue**
     
       @Test
        fun encounter_is_not_parsed_correctly() {

        val parser = FhirContext.forR5().newJsonParser()

        var jsonToParse = "{\n" +
                "    \"resourceType\": \"Encounter\",\n" +
                "    \"id\": \"1004066\",\n" +
                "    \"meta\": {\n" +
                "        \"versionId\": \"1\",\n" +
                "        \"lastUpdated\": \"2021-02-16T16:04:56.624+01:00\",\n" +
                "        \"source\": \"#coGTf1T5sf6kd3dB\"\n" +
                "    },\n" +
                "    \"status\": \"planned\",\n" +
                "    \"subject\": {\n" +
                "        \"reference\": \"Patient/1004063\"\n" +
                "    },\n" +
                "    \"reasonReference\": [\n" +
                "        {\n" +
                "            \"reference\": \"Observation/1004064\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"reference\": \"Observation/1004065\"\n" +
                "        }\n" +
                "    ]\n" +
                "}"

        var encounter = parser.parseResource(Encounter::class.java, jsonToParse)

        Assert.assertNotNull(encounter.reason) //I believe this is where the reasonReference should go?
        Assert.assertSame(2, encounter.reason.count())
    }

**Comment by jamesagnew** [comment]
The R5 Encounter.reason field is called `reason` and not `reasonReference`. See: http://build.fhir.org/encounter.html
