### ISSUE TITLE
HAPI FHIR R5 implementation in QuestionnaireResponse does not accept subject with reference

### ISSUE THREAD

**Issue by BSVogler** [hapifhir/hapi-fhir#2419]
**Describe the bug**
HAPI R5 REST API on the QuestionnaireResponse resource does not accept the field _subjects_ with a reference to a patient in a POST request. (http://hl7.org/fhir/2020Sep/questionnaireresponse-definitions.html#QuestionnaireResponse.subject)
HAPI R4 (http://hapi.fhir.org/baseR4/) accepts them.
Ther server respons with an error message
```
Failed to extract values from resource using FHIRPath \"QuestionnaireResponse.item.where(hasExtension('http://hl7.org/fhir/StructureDefinition/questionnaireresponse-isSubject')).answer.value.ofType(Reference)\": org.hl7.fhir.r5.utils.FHIRLexer$FHIRLexerException: Error @1, 1: The name hasExtension is not a valid function name
```

**To Reproduce**
Send a POST request to http://hapi.fhir.org/baseR5/QuestionnaireResponse
```json
{
	"resourceType": "QuestionnaireResponse",
	"authored": "2020-12-24T23:54:55.834+00:00",
	"status": "completed",
	"subject": {
		"reference": "Patient/a6d944c4-6aba-11eb-8800-865aaa65457a"
	}
}
```

**Expected behavior**
The resource should be created

**Environment:**
HAPI FHIR Server - 5.3.0

**Comment by ZuSe** [comment]
The only  part of the code where I see that message is here:

https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-structures-r4/src/test/resources/rdf-test-input/questionnaireresponse-extensions-QuestionnaireResponse-item-subject.json

@jamesagnew  Is there any chance that the RDF tests are causing that behavior?

**Comment by jamesagnew** [comment]
I'm really confused by this. The expression contains the FHIRPath function `hasExtension` but the FHIRPath spec does not actually specify such a function: http://hl7.org/fhirpath/

I've posted a question to clarify this on Zulip:

https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Invalid.20expression.20in.20QuestionnaireResponse.20SP

**Comment by jamesagnew** [comment]
Confirmed, this is a spec bug, not a code bug. 

Tracking ticket filed for the spec: https://jira.hl7.org/browse/FHIR-31479

**Comment by ZuSe** [comment]
Hi James,

what does that mean in terms of temporary work around.
Is there a chance that it gets changed soon in the spec or would it be worth to ignore within the code for now?

Thanks for the opening the ticket that fast!

**Comment by ZuSe** [comment]
@jamesagnew The ticket has been closed on FHIR and pushed to github.
What is the flow to apply the changes to HAPI? 
Happy to help out if u tell me what to do.

**Comment by ZuSe** [comment]
I just double checked. The problem still exists. 
Tested with FHIR-5.4.0-PRE-10

```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to extract values from resource using FHIRPath &quot;QuestionnaireResponse.item.where(hasExtension('http://hl7.org/fhir/StructureDefinition/questionnaireresponse-isSubject')).answer.value.ofType(Reference)&quot;: org.hl7.fhir.r5.utils.FHIRLexer$FHIRLexerException: Error @1, 1: The name hasExtension is not a valid function name</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to extract values from resource using FHIRPath \"QuestionnaireResponse.item.where(hasExtension('http://hl7.org/fhir/StructureDefinition/questionnaireresponse-isSubject')).answer.value.ofType(Reference)\": org.hl7.fhir.r5.utils.FHIRLexer$FHIRLexerException: Error @1, 1: The name hasExtension is not a valid function name"
        }
    ]
}
```

**Comment by jamesagnew** [comment]
You would need to upload a fixed version of the SearchParameter resource for now. Unfortunately it will probably be a while before the fix percolates through the standards process in order to make it into a FHIR standard release
