### ISSUE TITLE
ca.uhn.fhir.rest.param.StringParam with overloaded "exact=true" not showing up in final QueryString

### ISSUE THREAD

**Issue by granadacoder** [hapifhir/hapi-fhir#2426]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**

StringParam with a value and overload of "exact=true" is not showing up in the final query string.

```
package ca.uhn.fhir.rest.param;
public class StringParam


```

final query-string does not seem to consider the contains and exact member variables.

	private boolean myContains;
	private boolean myExact;
	private String myValue;

**To Reproduce**

```

import ca.uhn.fhir.model.api.IQueryParameterType;
import ca.uhn.fhir.rest.client.api.IGenericClient;
import ca.uhn.fhir.rest.param.DateParam;
import ca.uhn.fhir.rest.param.ParamPrefixEnum;
import ca.uhn.fhir.rest.param.StringParam;
import ca.uhn.fhir.rest.param.TokenParam;

import org.hl7.fhir.instance.model.api.IBaseResource;
import org.hl7.fhir.r4.model.Bundle;
import org.hl7.fhir.r4.model.Patient;
import org.hl7.fhir.r4.model.Resource;


        IGenericClient client = /* blah blah blah */

        Map<String, List<IQueryParameterType>> searchParameterMap = new HashMap<>();

            List<IQueryParameterType> familyNameChainedFilters = new ArrayList<>();

            StringParam sp1 = new StringParam("Smith", true); // NOTE THE true for "exact" here <<<<<<<

            familyNameChainedFilters.add(sp1);
            searchParameterMap.put(Patient.FAMILY.getParamName(), familyNameChainedFilters);




        Bundle bundleSearchResult = client
                .search()
                .forResource(Patient.class)
                .where(searchParameterMap)
                .count(100)
                .returnBundle(Bundle.class)
                .execute();


The query will produce a:

https://my.fhir.server/R4/Patient?family=Smith



```
**Expected behavior**

StringParam sp1 = new StringParam("Smith", true); 

(should) result in:

https://my.fhir.server/R4/Patient?family:exact=Smith

**Screenshots**

![image](https://user-images.githubusercontent.com/5487824/109333772-dd80cf80-782d-11eb-9100-15c3907450ae.png)

![image](https://user-images.githubusercontent.com/5487824/109334064-39e3ef00-782e-11eb-9754-39cd72455993.png)

**Environment (please complete the following information):**

    implementation group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-structures-r4', version: hapiFhirVersion
    implementation group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-client-okhttp', version: hapiFhirVersion
        hapiFhirVersion = '5.2.0'

**Additional context**

http://hl7.org/fhir/search.html#string

[base]/Patient?given=eve | Any patients with a name containing a given part with "eve" at the start of the name. This would include patients with the given name "Eve", "Evelyn".
-- | --
[base]/Patient?given:contains=eve | Any patients with a name with a given part containing "eve" at any position. This would include patients with the given name "Eve", "Evelyn", and also "Severine".
[base]/Patient?given:exact=Eve | Any patients with a name with a given part that is exactly "Eve". Note: This would not include patients with the given name "eve" or "EVE".

Living example:

https://server.fire.ly/R4/Patient?family=Smith

(get back "Smithy" and  "Smithies-Thursday",

====

https://server.fire.ly/R4/Patient?family:exact=Smith

(correct behavior, only "Smith" 's.

**Comment by granadacoder** [comment]
Thanks for the quick fix.

#eagleEyeJames

**Comment by jamesagnew** [comment]
@granadacoder thanks for the detailed report. That made it easy :)
