### ISSUE TITLE
Creating HapiWorkerContext crashes: java.lang.ClassNotFoundException: org.fhir.ucum.UcumException

### ISSUE THREAD

**Issue by jingtang10** [hapifhir/hapi-fhir#2443]
**Describe the bug**

java.lang.ClassNotFoundException: org.fhir.ucum.UcumException

**To Reproduce**

Create a new java project using gradle.

Add dependency to hapi structures lib

```
    implementation 'ca.uhn.hapi.fhir:hapi-fhir-structures-r4:5.3.0'
```

Create a main class that does the following:

```
package com.example;

import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.context.support.DefaultProfileValidationSupport;
import org.hl7.fhir.r4.utils.FHIRPathEngine;
import org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext;

public class Main {
  public static void main (String[] args) {
    FhirContext context = FhirContext.forR4();
    DefaultProfileValidationSupport validationSupport = new DefaultProfileValidationSupport(context);
    FHIRPathEngine fhirPathEngine = new FHIRPathEngine(new HapiWorkerContext(context, validationSupport));
  }
}
```

**Expected behavior**
It should run.

**Actual behavior**
```
Caused by: java.lang.ClassNotFoundException: org.fhir.ucum.UcumException
```

**Environment (please complete the following information):**
 - HAPI structures version: ca.uhn.hapi.fhir:hapi-fhir-structures-r4:5.3.0
 - IDE:
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
 - java: project sdk: 11.0.4

**Additional info**
Interestingly, when I tried to look into the source code, it says the decompiled code doesn't match the source code. So I think there might have been some changes in the release that caused this mismatch. I also see the class `org.hl7.fhir.exceptions.UcumException` in the hapi utilities lib which the structures lib depends on. So I think there might have been some kind of package reorg that got out of sync here? (notice the namespace mismatch: `org.fhir.ucum.UcumException` vs `org.hl7.fhir.exceptions.UcumException`)

**Comment by MuhammadSalman-7214** [comment]
I am facing this error on my PR https://github.com/google/android-fhir/pull/536

**Comment by jingtang10** [comment]
This is caused by a missing dependency of HAPI validation lib.

**Comment by bhargavchowdhary** [comment]
after adding hapi-fhir-validation to the dependencies still i am getting 
 java.lang.ClassNotFoundException: org.fhir.ucum.UcumException
