### ISSUE TITLE
Deadlock in TermDeferredStorageSvcImpl with postgresql

### ISSUE THREAD

**Issue by tyfoni** [hapifhir/hapi-fhir#2493]
We have upgraded to hapi-fhir 5.3.0 and now see deadlocks when updating a CodeSystem. 

The deadlock is caused by the deferred deletion of codesystem version in TermDeferredStorageSvcImpl. 
One thread is doing:
  1. update TRM_CODESYSTEM_VER set CODESYSTEM_PID=$1,  CS_DISPLAY=$2, CS_VERSION_ID=$3 where PID=$4
  2. call deleteCodeSystemVersion()
```
  	public synchronized void deleteCodeSystemVersion(TermCodeSystemVersion theCodeSystemVersion) {
		myDeferredCodeSystemVersionsDeletions.add(theCodeSystemVersion);
	}

```
Another thread is doing:
 3. processDeferredCodeSystemVersionDeletions()
```
    private void processDeferredCodeSystemVersionDeletions() {
		for (TermCodeSystemVersion next : myDeferredCodeSystemVersionsDeletions) {
			processDeferredCodeSystemVersionDeletions(next.getPid());
		}

		myDeferredCodeSystemVersionsDeletions.clear();
	}

```
4. delete from TRM_CODESYSTEM_VER where PID=$1

The update request does not return and will timeout. Inspection in postgresql show that delete transaction (4) is waiting for update transaction (1) to commit. But the call to deleteCodeSystemVersion (2) is synchronized and must wait for the iteration in processDeferredCodeSystemVersionDeletions (3) to finish.

This deadly embrace can only be released if the update transaction is rolled back.

**Expected behavior**
It is expected that entries can be added to myDeferredCodeSystemVersionsDeletions without waiting for the deferred processing.

**Screenshots**
![image](https://user-images.githubusercontent.com/11489416/111980010-067f4200-8b06-11eb-9321-ef89e7b656ab.png)

**Environment:**
 - HAPI FHIR Version 5.3.0
 - OS: Linux (Docker+Kubernetes)

**Suggested solution**
Use ConcurrentLinkedQueue instead of synchronizedList.  We have made a workaround by replacing TermDeferredStorageSvcImpl with a local implementation. It is just a clone with the following modifications:

```
49,50c67
< // cloned from hapi-fhir to solve deadlock issue
< public class EHealthTermDeferredStorageSvcImpl implements ITermDeferredStorageSvc {
---
> public class TermDeferredStorageSvcImpl implements ITermDeferredStorageSvc {
54c71
<     final private Queue<TermCodeSystemVersion> myDeferredCodeSystemVersionsDeletions = new ConcurrentLinkedQueue<>();
---
>       final private List<TermCodeSystemVersion> myDeferredCodeSystemVersionsDeletions = Collections.synchronizedList(new ArrayList<>());
484c501
<     public void deleteCodeSystemVersion(TermCodeSystemVersion theCodeSystemVersion) {
---
>       public synchronized void deleteCodeSystemVersion(TermCodeSystemVersion theCodeSystemVersion) {


```

**Comment by ruoat** [comment]
@jamesagnew is there any plans to implement this workaround in Hapi or is there better options? We have this problem also and planning to override Hapi classes with this workaround.

**Comment by jamesagnew** [comment]
Fix accepted as suggested. Thanks for the contribution!
