### ISSUE TITLE
How to check if my information is saved properly in FHIR.

### ISSUE THREAD

**Issue by sa4mata100** [hapifhir/hapi-fhir#2503]
Hello, I am new to FHIR and i have a beginner question.
I want to create a test for an app that creates a data in "QuestionnaireResponse" and i want to check if that data is saved properly.
I can get and save the data from the "QuestionnaireResponse" like json or XML, but i dont know how to check if the data is saved properly.

**Comment by KevinDougan-SmileCDR** [comment]
Check the Getting Help article ad other docs if you need help, rather than creating an issue:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help
