### ISSUE TITLE
Select2 version incompatible with 5.3.0

### ISSUE THREAD

**Issue by ruoat** [hapifhir/hapi-fhir#2504]
This breaks Hapi 5.3.0 version of select2. You can go to http://hapi.fhir.org/ and see select2 load failing

_Originally posted by @ruoat in https://github.com/hapifhir/hapi-fhir/issues/2273#issuecomment-806862498_

**Comment by jamesagnew** [comment]
Ah, I see the path changed. Whoops.

Fix coming up.
