### ISSUE TITLE
Search with a large number for `_getpagesoffset`  returns invalid Bundle

### ISSUE THREAD

**Issue by nicozorza** [hapifhir/hapi-fhir#2552]
**Description**
In our server we have a large number of resources stored. I was trying to iterate over a resource by incrementing the `_getpagesoffset` query, and I saw that sometimes the returned bundle was randomly empty.
For example: when making the following request `MedicationRequest?_getpagesoffset=5000& _count=20&_bundletype=searchset` there are times when the result is empty, even though there are about 10k MedicationRequests (sometimes making the same request returns the correct data)
I also noticed that if the value of `_getpagesoffset` is larger than the number of elements stored, sometimes the returned Bundle contains one element (the last resource created).

**To Reproduce**
This happens randomly, and we only noticed it when `_getpagesoffset` is large

**Environment (please complete the following information):**
 - HAPI FHIR JPA Server - Starter Project 4.2.0
 - OS: Linux

**Comment by jamesagnew** [comment]
The FHIR server requires you to use the paging URLs that are returned by the server, it is an error to manipulate them by hand. HAPI does not guarantee consistent behaviour if you do that.
