### ISSUE TITLE
Count when non-existing patient

### ISSUE THREAD

**Issue by BSVogler** [hapifhir/hapi-fhir#2568]
**Describe the bug**
When you count the number using the rest api `_count=0` and combine it with a non-existing patient on the Contract object

**Count with existing**
`{{ fhir }}Contract?subject=Patient/someexisting&_count=0`
returns e.g. 200 total: 3 ☑️

**Query for non-existing patient**
[{{ fhir }}Contract?subject=Patient/nonexisting](http://hapi.fhir.org/search?serverId=home_r5&pretty=true&_summary=&resource=Contract&param.0.0=&param.0.1=nonexisting&param.0.name=subject&param.0.type=reference&sort_by=&sort_direction=&resource-search-limit=)
200 with total: 0☑️

**Count with querying for non-existing patient**
[{{ fhir }}Contract?subject=Patient/nonexisting&_count=0](http://hapi.fhir.org/baseR5/Contract?subject=Patient/nonexisting&_count=0)
500 with response body❌
```
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Index 0 out of bounds for length 0"
    }
  ]
```

**To Reproduce**
Query for any non-existing patient.

**Expected behavior**
it should return a 200 with `total: 0`.

**Environment (please complete the following information):**
R4 or R5

**Comment by theGOTOguy** [comment]
The same is the case for any other FHIR resource you might do a search on, e.g. Specimen.

**Comment by BSVogler** [comment]
Looks like the issue has been resolved in the current version.
