### ISSUE TITLE
Add builtin Search Parameters for resource-placeholder extensions. 

### ISSUE THREAD

**Issue by tadgh** [hapifhir/hapi-fhir#2580]
Previously, we added the following in HAPI FHIR:

**Auto-created placeholder reference targets now have an extension with the URL `http://hapifhir.io/fhir/StructureDefinition/resource-placeholder` and a value of true.** 

We'd like to come with one or more built-in custom SearchParameters to support searching for resources of all types where this extension is present with a given value (i.e. true/false).
Ideally, this will behave just like all of the other SearchParameters that come with an installation of  HAPI-FHIR (e.g. if they're missing, they'll get installed at startup).

**Comment by jamesagnew** [comment]
fyi @grahamegrieve we only currently auto-install the SP resources in smile cdr, hapi JPA currently only uses in memory copies (although these can be overridden by uploading them manually)

wouldn't be a bad idea to bring this feature over to hapi though, and implement the improvement you're proposing (great idea!)

**Comment by jamesagnew** [comment]
sorry @grahamegrieve accidentally tagged you in my original comment, you can disregard :)

**Comment by tadgh** [comment]
I kind of already implemented this in hapi 🙈 https://github.com/hapifhir/hapi-fhir/pull/2581

**Comment by tadgh** [comment]
Happy to move it out of here if you'd rather though
