### ISSUE TITLE
hapi-fhir-server-openapi not available in maven

### ISSUE THREAD

**Issue by reshmi1990** [hapifhir/hapi-fhir#2639]
Not able to find hapi-fhir-server-openapi in maven and hence not able to add this feature to Java spring boot application.

**Comment by jamesagnew** [comment]
Please use our google group and not GitHub issues to ask questions. See this page for information on where to get help with HAPI FHIR: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

The hapi-fhir-server-openapi is in Maven here: https://oss.sonatype.org/content/repositories/snapshots/ca/uhn/hapi/fhir/hapi-fhir-server-openapi/
