### ISSUE TITLE
How to change picture

### ISSUE THREAD

**Issue by kmlvli88** [hapifhir/hapi-fhir#2715]
![問題](https://user-images.githubusercontent.com/85544705/121136341-1fc39f00-c868-11eb-9719-43082b35f4e6.PNG)
1.How to change picture
2.How to solve Warning
thanks

**Comment by j-fbriere** [comment]
This is not related to the **hapi-fhir** project.
Instead, this is related to the **hapi-fhir-jpaserver-starter** project.

For the picture question:

In the **src/main/webapp/WEB-INF/templates** folder, modify the **tmpl-banner.html** file:
`<img src="img/sample-logo.jpg" width="383" alt="Sample Logo" />`
to
`<img src="img/your_picture_file.jpg" width="383" alt="your picture text logo" />`

Also add the **your_picture_file.jpg** file in the **src/main/webapp/img** folder.

**Comment by kmlvli88** [comment]
Hi j-fbriere tank you for your reply
I want to build hapi fhir server for eclipse. And I get a new resources from  [https://github.com/hapifhir/hapi-fhir-jpaserver-starter]
The following is me step.
1.import  resources
2.run us →maven build →Goals:jetty:run
but alawys fail .how can i do?
java version 11

**Comment by jamesagnew** [comment]
HI @kmlvli88 - Please see this page for information on where to get help with HAPI FHIR: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help
