### ISSUE TITLE
History requests do not include a "next" link

### ISSUE THREAD

**Issue by salahlantana** [hapifhir/hapi-fhir#2725]
**Describe the bug**
When making a request for _history on a resource that has more than 20 versions, the response Bundle does not include a "next" link, which is different behavior than other search responses (such as GET /ImplementationGuide).

**To Reproduce**
1. Create a resource and update it more than 20 times
2. Perform GET /<resourceType>/<id>/_history

**Expected behavior**
Response Bundle should include a Bundle.link[relation=next]

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.2.1
 - OS: Ubuntu (docker)
 - Browser Chrome (recent)

**Comment by jamesagnew** [comment]
Does this issue occur on HAPI FHIR 5.4.0?

**Comment by jamesagnew** [comment]
Fixed in !2741
