### ISSUE TITLE
How to use HAPI API with retrofit in Android?

### ISSUE THREAD

**Issue by pravingaikwad07** [hapifhir/hapi-fhir#2740]
I want to fetch/query FHIR test server using Retrofit but I am not able to map the Bundle response using GsonConverterFactory. How to do it ?

This is my RetrofitAPIService:
```
 @GET(Hl7ApiEndPoint.PATIENT_LIST)
    Call<Bundle> getPatients(@Query("organization") String managingOrganizationRef,
                                    @Query("_count") int count
    );
```

Error msg:

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 10 path $.id

**Comment by jamesagnew** [comment]
The FHIR model objects in HAPI FHIR do not support automatic serialization/deserialization by Gson. You need to use HAPI FHIR's parser. 

I'm not sure what's possible with retrofit, but if nothing else you could just return a string, and use HAPI's parser to parse your Bundle object.
