### ISSUE TITLE
Reduce Excessive Use of Reflection

### ISSUE THREAD

**Issue by goafabric** [hapifhir/hapi-fhir#2788]
Hello Everybody,
I noticed that HAPI FHIR Is using Reflection heavily.
While this does not disturb in usual environments,
this hurts with the Rise of Cloud Native Applications and GraalVM.

To my own surprise I was able to get HAP FHIR 5.3 running with Quarkus as a native Image.
But besides some basic Reflection hints, like FHIRVersionEnum and XhtmlNode,
it is also necessary to define EVERY "model" class per used FHIR Version (R4, STU3 ..)
Because the Modelscanner runs over all these Classes, even if they are not used.

For R4 alone this result in 250 class that have to be registered for reflection.
And this hurts both the Compile and Runtime Performance of Native Binaries a lot.

So are there any plans, to reduce the amount of Reflection, at least for the Model(Scanner) part ?

**Comment by jamesagnew** [comment]
An easy thing to try: There is a setting `FhirContext#setPerformanceOptions` that can be used to defer the model scanning, and could potentially avoid the need to register the entire model for reflection.

I did a research spike last year in removing the reflection entirely, instead using the `listChildren`, `getNamedProperty` etc properties that exist on all DSTU3+ structures. At the time I was interested in seeing the impact on parsing/encoding performance as opposed to model scanning, and I ended up finding that the reflection method was surprisingly fast compared to not using it so I abandoned that work.

I could see there being value for scenarios like the ones you describe though.. Maybe time to revisit that work

**Comment by goafabric** [comment]
Ok cool,
thank you very much James
That would already help a lot.
Thank you very much

**Comment by goafabric** [comment]
@jamesagnew 
so that's unfortunately not working ...
inside ModelScanner.init 
we have an early call to scanVersionPropertyFile

which than starts to walk over the model via reflection

The "PerformanceOptionsEnum.DEFERRED_MODEL_SCANNING" is checked much later inside the init method.
When all this is already done .. am I doing something wrong ?

**Comment by goafabric** [comment]
@jamesagnew 
so anyways .. it would be very good if you could give the No Reflection alternative a spin ...
For GraalVM this pretty much hurts the build time, by increasing it from about 2 minutes up to 15 minutes
so much much slower ...

I currently ended up with a Reflection Configuration with about 300! Classes .. only for R4 and Metadata stuff

**Comment by goafabric** [comment]
@jamesagnew 
Hi James, any news concerning this topic ?

**Comment by goafabric** [comment]
@jamesagnew 
Do we have an news on this or should i just close the issue ?

The thing however is, that we would really need a solution here, with less reflection involved.

Our Main Goals for 2022 involve HAPI Fhir as well as building Cloud Native Binaries.
And with all the reflection going on, both for server and client .. these two goals are somehow mutually exclusive.

So at least a sign of life would be appreciated :)

**Comment by goafabric** [comment]
Closing the Issue as no reaction from other side

**Comment by Bugerman58** [comment]
In fact, this question is still relevant 😫

Our environment:
* Micronaut 3.10.1
* ca.uhn.hapi.fhir:hapi-fhir-structures-r4
* ca.uhn.hapi.fhir:hapi-fhir-client
* GraalVM CE 21.0.2

Application is successed build and running, but when fhir-client received response from server throw exception:
```
ca.uhn.fhir.context.ConfigurationException: HAPI-1694: Failed to instantiate org.hl7.fhir.r4.model.CapabilityStatement$CapabilityStatementKindEnumFactory
ca.uhn.fhir.context.RuntimeChildPrimitiveEnumerationDatatypeDefinition.toEnumFactory(RuntimeChildPrimitiveEnumerationDatatypeDefinition.java:69)
ca.uhn.fhir.context.RuntimeChildPrimitiveEnumerationDatatypeDefinition.getInstanceConstructorArguments(RuntimeChildPrimitiveEnumerationDatatypeDefinition.java:55)
ca.uhn.fhir.parser.ParserState.getPrimitiveInstance(ParserState.java:240)
ca.uhn.fhir.parser.ParserState$ElementCompositeState.enteringNewElement(ParserState.java:661)
ca.uhn.fhir.parser.ParserState.enteringNewElement(ParserState.java:137)
ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1465)
ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1346)
ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:263)
ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:243)
ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:648)
ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:632)
ca.uhn.fhir.rest.client.impl.BaseClient$ResourceResponseHandler.invokeClient(BaseClient.java:691)
ca.uhn.fhir.rest.client.impl.BaseClient$ResourceResponseHandler.invokeClient(BaseClient.java:618)
ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:448)
ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:585)
ca.uhn.fhir.rest.client.impl.GenericClient$FetchConformanceInternal.execute(GenericClient.java:896)
ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBase(RestfulClientFactory.java:335)
ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBaseIfConfiguredToDoSo(RestfulClientFactory.java:294)
ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:272)
ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:585)
ca.uhn.fhir.rest.client.impl.GenericClient$SearchInternal.execute(GenericClient.java:2201)
```

Has anyone else gone through this thorny way?
