### ISSUE TITLE
Execute bundle searches in parallel

### ISSUE THREAD

**Issue by tadgh** [hapifhir/hapi-fhir#2836]
When processing a FHIR Transaction/Batch operation containing non-modifying operations (e.g., read, search) these operations are processed sequentially by the transaction processor.
As these items do not affect server state, they can safely be executed in parallel without violating the
contract of the FHIR transaction/batch operations. This task involves the implementation of a worker pool
(i.e., a configurable thread pool) that will be used to execute all non-writing search tasks.

Solution Design:

When executing a transaction, instead of executing each search in turn, have a configurably-sized threadpool dedicated to executing non-modifying searches. Possibly use the existing search thread pool?

**Comment by frankjtao** [comment]
As discussed, the parallelism is switched to the **batch** level instead of **transaction** level, and it's all operations. @tadgh
