### ISSUE TITLE
Word-boundary Text Matching 

### ISSUE THREAD

**Issue by tadgh** [hapifhir/hapi-fhir#2841]
#### Description of Enhancement

Currently searches on Observation code:text match only at the beginning of the string, rather than on
words. This task will change the matching behavior of :text for any parameter (not just Observation
code:text) so that will match on word boundaries. Example 1: A search on “weight” should match the
display string “Body weight” or “Weight”. Example 2: A search on “h” should match “Height” but not
“Weight”.

#### Acceptance Criteria

Example 1: A search on “weight” should match the display string “Body weight” or “Weight”.
Example 2: A search on “h” should match “Height” but not “Weight”.

#### Solution Design

Change our indexing to tokenize on words, and change :text to compose a prefix search against all tokens

#### Testing

Enter several Observations with different codes.
Search by `code:text=` for different words.

**Comment by michaelabuckley** [comment]
https://github.com/hapifhir/hapi-fhir/tree/issue-2841-word-boundary-text-searching
