### ISSUE TITLE
_include does not work for QuestionnaireResponse:questionnaire

### ISSUE THREAD

**Issue by xluanlhc** [hapifhir/hapi-fhir#2843]
**Describe the bug**
Per FHIR spec, QuestionnaireResponse.questionnaire is a canonical. But when using a full URL for this field, a QuestionnaireResponse search request with _include=QuestionnaireResponse:questionnaire does not return the Questionnaire resource the QR refers to.
Ironically, if you use relative URL for the "questionnaire" field, the _include works, but FHIR spec requires that
 the QuestionnaireResponse.questionnaire should be a canonical.

**To Reproduce**
- Use/load the attached (see below) sample Questionnaire and QuestionnaireResource files or create/load your own,
- Make sure to use "full" URL for the QuestionnaireResponse.questionnaire field. 
- A request like:
     QuestionnaireResponse?_id=MY-QR-RES-ID&_include=QuestionnaireResponse:questionnaire
Should return Questionnaire resource as well.

Attached sample Questionnaire and QuestionaireResponse files:
[questionnaire-hapi.json.txt](https://github.com/hapifhir/hapi-fhir/files/6896612/questionnaire-hapi.json.txt)
[questionnaire-resp-hapi.json.txt](https://github.com/hapifhir/hapi-fhir/files/6895980/questionnaire-resp-hapi.json.txt)

**Expected behavior**
Should included the referenced Questionnaire in the results as requested.

**Environment (please complete the following information):**
 - HAPI FHIR Version: HAPI FHIR 5.5.0-PRE1-SNAPSHOT (live on hapi.fhir.org as of 2021-07-28)

**Comment by tyfoni-systematic** [comment]
We have found out how to make #1583 work with our configuration. The missing part was to strip the base url on canonical references before storing the resource. Then the suggested workaround is no longer needed. This is the same as we do for references. 
When retrieving resources, the base url must be added again to allow validation.
