### ISSUE TITLE
JPA server stops responding under load when caching is disabled or configured to low timeout

### ISSUE THREAD

**Issue by jarimayenburg** [hapifhir/hapi-fhir#2896]
**Describe the bug**
When configuring the JPA server to not use the search cache (`reuse_cached_search_results_millis: 0` in the starter project) or a search cache with relatively small timeout (`reuse_cached_search_results_millis: 10000`), the server stops responding with a  load of a certain amount of parallel requests.

**To Reproduce**
1. Run the stock JPA server starter project with a MySQL database
2. Perform 10,000 or 100,000 parallel requests, observe that while the responses take long, the server never stops processing the requests.
3. Now update the config `reuse_cached_search_results_millis` to a value of 10000 or below (I used 0).
4. Perform the same amount of requests, observe that the server stops processing the requests after a little while. With `reuse_cached_search_results_millis` set to 0, my instance already stopped responding after less than 100 simultaneous requests.

**Expected behavior**
I'd expect the server to respond slower, but never stop processing the incoming requests.

**Environment:**
 - HAPI FHIR Version: 5.4.2

**Additional context**
Re-enabling the cache to the default of 60 seconds is no option for us, because that causes newly created resources to not be found in searches within 60 seconds after creation, which is a necessity for us.

**Comment by jarimayenburg** [comment]
Closing for now because the cause and reproduction steps aren't quite correct yet

**Comment by jarimayenburg** [comment]
Did some more testing today, above causes are correct after all. The combination of MySQL and a low `reuse_cached_search_results_millis` does the trick.

**Comment by jamesagnew** [comment]
Can you attach a thread dump taken when the system is hung?

**Comment by jarimayenburg** [comment]
Here you go

[dump.txt](https://github.com/hapifhir/hapi-fhir/files/6999127/dump.txt)

**Comment by jarimayenburg** [comment]
After waiting for a while, Hikari starts to give timeouts
```
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:05.784 [http-nio-8080-exec-31] INFO  fhirtest.access [LoggingInterceptor.java:160] ERROR - GET http://localhost:8080/fhir/Patient
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.652 [search_coord_9] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.652 [search_coord_9] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] HikariPool-1 - Connection is not available, request timed out after 30000ms.
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.654 [search_coord_14] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.654 [search_coord_14] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] HikariPool-1 - Connection is not available, request timed out after 30000ms.
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.655 [search_coord_12] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.655 [search_coord_12] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] HikariPool-1 - Connection is not available, request timed out after 30000ms.
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.656 [search_coord_10] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.656 [search_coord_10] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] HikariPool-1 - Connection is not available, request timed out after 30000ms.
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.655 [search_coord_19] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.657 [search_coord_19] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] HikariPool-1 - Connection is not available, request timed out after 30000ms.
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.655 [search_coord_15] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.656 [search_coord_7] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.656 [search_coord_13] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
hapi-fhir-jpaserver-start    | 2021-08-17 10:26:06.657 [search_coord_3] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 0, SQLState: null
```

**Comment by jarimayenburg** [comment]
For ease of reproduction, here's a minimal patch on the starter project.

```
diff --git a/docker-compose.yml b/docker-compose.yml
index fcf1f2b..4ea3d1b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -4,10 +4,15 @@ services:
     build: .
     container_name: hapi-fhir-jpaserver-start
     restart: on-failure
+    environment:
+      SPRING_DATASOURCE_URL: jdbc:mysql://hapi-fhir-mysql:3306/hapi?serverTimezone=Europe/Amsterdam
+      SPRING_DATASOURCE_USERNAME: admin
+      SPRING_DATASOURCE_PASSWORD: admin
+      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
     ports:
       - "8080:8080"
   hapi-fhir-mysql:
-    image: mysql:latest
+    image: mysql:5.7
     container_name: hapi-fhir-mysql
     #https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
     command: --lower_case_table_names=1
diff --git a/src/main/resources/application.yaml b/src/main/resources/application.yaml
index 1ff811a..82df865 100644
--- a/src/main/resources/application.yaml
+++ b/src/main/resources/application.yaml
@@ -108,7 +108,7 @@ hapi:
 #    max_binary_size: 104857600
 #    max_page_size: 200
 #    retain_cached_searches_mins: 60
-#    reuse_cached_search_results_millis: 60000
+    reuse_cached_search_results_millis: 0
     tester:
         home:
           name: Local Tester
```

**Comment by jamesagnew** [comment]
That thread dump looks to me like threads are blocking waiting for connections from the pool. Can you try increasing your connection pool size?

**Comment by jarimayenburg** [comment]
Increasing the Hikari connection pool fixes this issue in the starter project, but not in our FHIR server, which is a fork of the starter project with mainly some config changes. In that project, even with a connection pool with a size of 100 the server stops responding with +/- 70 simultaneous requests. Let me figure out if I can reproduce that in the starter project with a greater pool size.

**Comment by jamesagnew** [comment]
FWIW the issue at least in the starter project is that Hibernate has to compensate for the lack of native database sequences in MySQL by using a table to achieve the same thing. This causes the occasional request to require 2 connections because of the way hibernate accomplishes this, so the problem is that if your DB pool isn't bigger than your server thread pool you get what is effectively a deadlock (it won't show up as a real deadlock in any management tools, but that's basically what it is).

If your real system shows lots of threads blocked waiting on PooledOptimizer, you're hitting the same issue.

To be honest, I think we should probably put stronger guidance against using MySQL on the starter project - its performance is lousy compared to Postgres for all kinds of reasons including this one.

**Comment by jarimayenburg** [comment]
Thanks for the info. Our real system does indeed show lots of threads waiting on PooledOptimizer, so it's the same issue.

I just tried Postgres for our project and that's performing like a champ. I'll look into migrating our system to Postgres using something like [pgloader](https://github.com/dimitri/pgloaderl).

I agree with the stronger guidance against MySQL and in favor of something like PostgreSQL, especially for production scenarios.

**Comment by jamesagnew** [comment]
One thing to note - If you migrate your data to PG it will work, but the one thing you'll need to do manually is to set the DB sequences to the same values from the MySQL ID generation table.

**Comment by jarimayenburg** [comment]
Ok thanks for the heads-up. Do you mean the values in the seq_* tables? Aren't those values copied to the Postgres DB in the migration itself?

**Comment by jamesagnew** [comment]
Yup, those are the ones. As far as I know those won't auto migrate, only
because they are a different kind of thing across the platforms (tables in
MySQL vs sequences in Postgres)

**Comment by smilenannan** [comment]
> One thing to note - If you migrate your data to PG it will work, but the one thing you'll need to do manually is to set the DB sequences to the same values from the MySQL ID generation table.

I refer to your discussion and am trying to migrate from MySQL to PG by using pgloader.

I can not find any tables which use auto increment column.
I ran

> SELECT AUTO_INCREMENT
>  FROM   information_schema.tables
> WHERE  TABLE_SCHEMA = 'hapi'\G

I got

> *************************** 1. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 2. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 3. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 4. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 5. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 6. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 7. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 8. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 9. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 10. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 11. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 12. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 13. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 14. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 15. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 16. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 17. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 18. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 19. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 20. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 21. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 22. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 23. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 24. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 25. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 26. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 27. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 28. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 29. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 30. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 31. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 32. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 33. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 34. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 35. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 36. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 37. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 38. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 39. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 40. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 41. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 42. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 43. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 44. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 45. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 46. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 47. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 48. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 49. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 50. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 51. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 52. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 53. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 54. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 55. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 56. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 57. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 58. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 59. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 60. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 61. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 62. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 63. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 64. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 65. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 66. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 67. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 68. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 69. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 70. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 71. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 72. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 73. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 74. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 75. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 76. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 77. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 78. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 79. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 80. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 81. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 82. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 83. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 84. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 85. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 86. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 87. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 88. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 89. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 90. row ***************************
> AUTO_INCREMENT: NULL
> *************************** 91. row ***************************
> AUTO_INCREMENT: NULL

JPA version : helm-v0.2.0 
MySQL : Ver 8.0.26 for macos11.4 on arm64 (Homebrew)

Does this mean there is nothing I have to manually migrate?
Thanks.

**Comment by smilenannan** [comment]
@jamesagnew 

Thank you for this discussion. I decided to use PostgreSQL instead of MySQL.
Is there any versions of PostgreSQL which are currently supported by JPA server?
