### ISSUE TITLE
The Timer already cancelled error

### ISSUE THREAD

**Issue by serveriev** [hapifhir/hapi-fhir#2990]
Hi, the Hapifhir team. 

It looks there is a bug when I use the http://hapi.fhir.org/ tool. When I'm trying to use the tool I got the error:
```
Warning!
Error: HTTP 500 Server Error: Failed to call access method: org.springframework.dao.InvalidDataAccessApiUsageException: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled.
```
Such an error I've faced this week. Prior to this week, I didn't face it.

**Steps to reproduce the behavior:**
1. Go to http://hapi.fhir.org. Open any resources for handling an API. For instance, I used the resource DocumentReference. 
2. Try to execute any API. For instance searching, validation / etc. Basically, it doesn't matter. Any API returns the error.
3. See an error.

**Screenshot**
![image](https://user-images.githubusercontent.com/4405764/133227511-1c5ad0ea-d371-46b2-adc5-41cdaab8d41f.png)

**Comment by jamesagnew** [comment]
Server has been restarted
