### ISSUE TITLE
Remove loinc.xml file from application used as fallback when loading loinc terminology

### ISSUE THREAD

**Issue by jmarchionatto** [hapifhir/hapi-fhir#3017]
A loinc.xml file is being provided in the application to use when uploading LOINC terminology in case one is not provided as input. This files is being removed, making an homonymous file required as input when uploading

Version: HAPI FHIR 5.5.1

**Comment by KevinDougan-SmileCDR** [comment]
**homonymous**
[ huh-mon-uh-muhs]
**adjective**
_of the nature of homonyms; **having the same name**._

**Comment by jmarchionatto** [comment]
Merged to master by: https://github.com/hapifhir/hapi-fhir/pull/3025
