### ISSUE TITLE
Large(ish) transaction bundles no longer work with SQL Server

### ISSUE THREAD

**Issue by jenspetervester** [hapifhir/hapi-fhir#3065]
**Describe the bug**
HAPI FHIR 5.5.1 on SQL Server 2016 throws an exception when processing a batch transaction with ~1900 entries. The problem is that a query hits the well-known SQL Server limitation of max 2100 parameters.

**To Reproduce**
1. Pull https://github.com/hapifhir/hapi-fhir-jpaserver-starter
2. Create an empty database in SQL Server
3. Add the mssql-jdbc driver version 9.4.0.jre11 to pom.xml
4. Change the configuration in application.yaml
> datasource:
> url: 'jdbc:sqlserver://localhost;databaseName=<name of the database>'
> username: sa
> password: <password>
> driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
5. Post [this bundle](https://gist.github.com/jenspetervester/006a60e6c966ade620f9702d4bb06863)

**Expected behavior**
The transaction to be completed. This works flawlessly in 5.4.1.

**Environment **
 - HAPI FHIR Version: 5.5.1
 - OS: Windows, Linux

**Additional context**
I want to insert or update a complete organization structure in one transaction.
We already have 55 hospitals as customers using our product suite based on SQL Server. We are looking to make HAPI FHIR a central part of our platform.

Log:
> WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 8003, SQLState: S0001
> ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.

**Comment by jamesagnew** [comment]
Hmm, this is weird. I am not actually sure how adding more entries in a batch operation could actually lead to a query with that many parameters in it.

Does the log have a stack trace in it?
