### ISSUE TITLE
$export operation does not provide binary links in 5.6 pre-release

### ISSUE THREAD

**Issue by gansoper** [hapifhir/hapi-fhir#3111]
HAPI FHIR 5.6.0-PRE2-SNAPSHOT/28cc51393b/2021-09-03 REST Server (FHIR Server; FHIR 4.0.1/R4)

Following settings are set:

    binary_storage_enabled: true
    bulk_export_enabled: true
    enable_index_missing_fields: true

I tried $export operation for the whole Base URL and Patient URL 
[base]/$export
[base]/Patient/$export

Both operations do not return binary links in $export-poll-status. 

[base]/$export-poll-status?_jobId=70c966c1-b98f-4d38-acd4-d94617ed9d40

{
    "transactionTime": "2021-10-25T12:14:32.908+03:00",
    "request": "/Patient/$export?_outputFormat=application%2Ffhir%2Bndjson"
}

The only working variant is
[base]/$export?_type={Resource}

**Comment by kiwisky** [comment]
When I enable the bulk_export_enabled, the jpaserver is down.

**Comment by tadgh** [comment]
Did you possibly mean to open this against this project? https://github.com/hapifhir/hapi-fhir-jpaserver-starter/

**Comment by kiwisky** [comment]
> Did you possibly mean to open this against this project? https://github.com/hapifhir/hapi-fhir-jpaserver-starter/

Yes. Is something wrong with me?  Does hapi-fhir-jpaserver-starter not support $export?
If I disable bulk_export_enabled, the jpaserver is OK to start but I got following error from [base]/$export or Patient/$export.
ponse Body
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[$export] with parameters [[]]</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "not-supported",
    "diagnostics": "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[$export] with parameters [[]]"
  } ]
}

**Comment by kiwisky** [comment]
BTW, I am deploying hapi-fhir-jpaserver-starter to an application server with Apache Tomcat.

**Comment by tadgh** [comment]
Heya! I am just saying this issue is logged against the HAPI-FHIR repo, not the hapi-fhir-jpaserver-starter repo. If you could kindly go submit this same issue at this link instead: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/new . It is totally possible this is a bug in hapi-fhir-jpaserver-starter, this is just the wrong github repo to submit the issue to.

**Comment by kiwisky** [comment]
Thanks a lot.
