### ISSUE TITLE
Provide RemoteTerminologyServiceValidationSupport Implementation For Operation $lookup

### ISSUE THREAD

**Issue by KevinDougan-SmileCDR** [hapifhir/hapi-fhir#3131]
The purpose of this Issue is to enhance the current support for the $lookup Operation so it can be provided by an instance of RemoteTerminologyServiceValidationSupport. It currently returns NULL instead of providing an implementation.

**Comment by rprobinson** [comment]
Hi I'm not trying to hijack but could this be the same reason why we're not getting the expected $validate-code for units of measure? - here's my issue:
NHS UK FHIR Terminology Server - HAPI FHIR Remote Terminology Service Validation #3113 https://github.com/hapifhir/hapi-fhir/issues/3113

**Comment by KevinDougan-SmileCDR** [comment]
Hi @rprobinson !
I am going through several scenarios for Remote Terminology Services and I believe in your case, there's a different call that needs to be addressed.
I just created the following issue now to address the $validate-code Operation:
#3136

**Comment by rprobinson** [comment]
Hi Kevin,
Thank you
Best regards
Richard
