### ISSUE TITLE
Duplicate record creation possible with conditional create (ifNoneExist / If-None-Exist parameter); race condition?

### ISSUE THREAD

**Issue by RudolfCardinal** [hapifhir/hapi-fhir#3141]
Making multiple simultaneous requests for conditional creation of the same resource to a HAPI FHIR server, using the ``ifNoneExist`` parameter (per ``fhirclient``, https://github.com/smart-on-fhir/client-py; ``If-None-Exist`` in FHIR spec, per https://www.hl7.org/fhir/http.html#ccreate), can lead to the creation of >1 "identical" records (each returning HTTP 201 Created). After this, subsequent calls fail with errors like: ``Failed to CREATE resource with match URL \"identifier=https://some_system|value1\" because this search matched 2 resources``.

Correct behaviour would be a single creation (HTTP 201 Created), after which subsequent calls return HTTP 200 OK.

It's easy to reproduce this bug with parallel requests, on multiple versions of the HAPI FHIR server (from Docker) -- sometimes 8 out of 8 threads succeed in creating the resource -- but I've not managed to reproduce it with serial requests. I wonder if this is a manifestation of https://github.com/hapifhir/hapi-fhir/issues/2317. Reproduced with all Docker versions from 5.4.1 to 5.5.1/latest, inclusive (5.4.0 doesn't support this type of request in any case).

Full details in the attached minimal Python demonstration: [hapi_fhir_server_ifnoneexist_race.py.txt](https://github.com/hapifhir/hapi-fhir/files/7471444/hapi_fhir_server_ifnoneexist_race.py.txt)

**Comment by jamesagnew** [comment]
In cases where you are making concurrent similar/identical requests across a distributed cluster, the only way to guarantee uniqueness is to rely on constraints enforced by the database. This can be done using a special type of Search Parameter.

See Enforcing Uniqueness here for an example of how to do this (docs are Smile CDR, but this is a HAPI FHIR feature too): https://smilecdr.com/docs/fhir_repository/custom_search_parameters.html#uniqueness

**Comment by RudolfCardinal** [comment]
Thanks, James! I will try to understand how this works.

(Meanwhile I note for reference that this has been observed in other systems -- https://github.com/microsoft/fhir-server/issues/1382 classed this behaviour as a bug -- but do you think it's conformant to insert >1 record in a concurrent situation? I see other similar discussion at https://issueexplorer.com/issue/IBM/FHIR/2051 also. The spec does say that If-None-Exist "can be used to avoid the risk of two clients creating duplicate resources for the same record.")

**Comment by jamesagnew** [comment]
I don't personally consider this a bug because there's a proven and documented way of avoiding it (although we should really have a reference in the HAPI FHIR docs too). Adding distributed duplicate checking is not without a performance penalty on any FHIR platform, and many implementors do not run concurrent workloads like this so they don't need that performance penalty.

**Comment by RudolfCardinal** [comment]
OK; thanks. Will try to grasp the method and work that into the test code.

**Comment by RudolfCardinal** [comment]
Thanks again, James. Since (as we understand it) this is something supported by HAPI, SmileCDR, and potentially other FHIR implementations, but not all, and we're trying to write generically, we'll take the approach of serializing requests if the receiving FHIR system can't guarantee concurrency. I'll close; thank you again for thinking about it and for your help.

**Comment by tuomoa** [comment]
> In cases where you are making concurrent similar/identical requests across a distributed cluster, the only way to guarantee uniqueness is to rely on constraints enforced by the database. This can be done using a special type of Search Parameter.
> 
> See Enforcing Uniqueness here for an example of how to do this (docs are Smile CDR, but this is a HAPI FHIR feature too): https://smilecdr.com/docs/fhir_repository/custom_search_parameters.html#uniqueness

@jamesagnew could you provide some details how uniqueness should work #1724
