### ISSUE TITLE
Specialcase handling for loinc?

### ISSUE THREAD

**Issue by jvitrifork** [hapifhir/hapi-fhir#3194]
Just stumbled across this: https://github.com/hapifhir/hapi-fhir/blob/bc250e141d908d9f22a2fd967449f77118751c6c/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoCodeSystemR4.java#L184

Why is there a special case handling for LOINC here and how can this case even happen? If you're in a flow of creating resources, the Id should (at all times) be ignored, right? Also, shouldn't the url check be against the fully qualified URL as defined in https://github.com/hapifhir/hapi-fhir/blob/71e2b821286851d965067ced9914492c388cd1b9/hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/ValidationConstants.java#L27

**Comment by jvitrifork** [comment]
@jmarchionatto maybe you would know?

**Comment by jmarchionatto** [comment]
The reason for that check is that loinc systems required the possibility of loading non-current versions, so the last loaded version was not necessarily the current anymore, then the Id is used to point the current version.

Using a column flag to indicate current version instead was analyzed and discarded because of the complications it was generating the fact of ValueSets having their own specific versions, which combine with the CodeSystem version with which they were loaded.

**Comment by jvitrifork** [comment]
Why not use CodeSystem.version instead? If you need to support multiple versions anyway, you cannot rely on the id pointing to the most reason one - not without making certain assumptions.
Anyways - I was hit by this because I needed to load just a very small set of LOINC and I was doing so by simply POST'ing a CodeSystem with loinc content - among this the URL of loinc and during POST/Create the id will always be omitted - [the server SHALL ignore it](https://www.hl7.org/fhir/http.html#create).

I understand your need but I would encourage such behaviour to be configurable.

**Comment by jmarchionatto** [comment]
Can't use the CodeSystem.version. If you have CS version 201 loaded and load a non-current version 202, how does the version indicate that 201 is still the current?
If you could load a loinc version with omitted id, that would never be considered current, and any older version would be considered for any operation.

**Comment by jvitrifork** [comment]
The current logic prohibits posting of a CodeSystem with a URL containing LOINC. The question around what 'current' means when you have mulitple versions that all may be valid is context specific. The 'non-current version 202', may be valid in some scenarios but aint that what the CodeSystem.version is for + a sort on latest updated?

**Comment by jvitrifork** [comment]
So to answer your question "Is this generating some problem?" - yes, it is.

**Comment by jmarchionatto** [comment]
Is it any reason why you can't PUT the CS including an ID?

**Comment by jmarchionatto** [comment]
Closing as suggestion was tested and works well. LOINC system can be uploaded by a PUT request.

**Comment by jvitrifork** [comment]
👍 - thx. Sorry for a late reply. PUT will definetly do it
