### ISSUE TITLE
_revinclude queries returns extra resources in HAPI 5.6.0 R4

### ISSUE THREAD

**Issue by vivektk84** [hapifhir/hapi-fhir#3261]
When _revinclude search parameter is used, the searchset response returns extra resources than what is being queried for. The issue is seen with the following revincludes for a Patient based search:

- EpisodeOfCare:patient 
- FamilyMemberHistory:patient

**To Reproduce**
1. Create a Patient with references to EpisodeOfCare, FamilyMemberHistory and other resources
2. Perform a _revinclude based search using EpisodeOfCare:patient or FamilyMemberHistory:patient.
e.g: _[baseurl]/Patient?_id=[patient_id]&_revinclude=EpisodeOfCare:patient 
[baseurl]/Patient?_id=[patient_id]&_revinclude=FamilyMemberHistory:patient_ 

The above queries returns all the other resources that are part of the matching patient apart from the Patient resource and EpisodeOfCare/FamilyMemberHistory resources.

**Expected behavior**
The  searchset response should only contain the Patient resource and the exact resources that are mentioned as part of the _revinclude queries.

**Environment (please complete the following information):**
HAPI version: 5.6.0
FHIR version: R4

**Additional context**
**This issue is noticed only in HAPI 5.6.0** and it works as expected in HAPI 5.3.0
The following are the FHIR resources that are created as part of this exercise which links to the Patient resource:

- AllergyIntolerance
- Observation
- DiagnosticReport
- Procedure
- CarePlan
- EpisodeOfCare
- MedicationStatement
- Encounter
- ServiceRequest
- FamilyMemberHistory
- ClinicalImpression
- Composition
- QuestionaireResponse
- Condition
- RiskAssessment
- ImagingStudy
- Practitioner

This behaviour is causing performance issues in the queries due to the inclusion of all other resources which are part of the patient.
NOTE: Similar issue occurs for Encounter based search using _revinclude.

**Comment by j-fbriere** [comment]
Any update yet on this issue which is, indeed, causing performance issues?

**Comment by j-fbriere** [comment]
Here is a fix for this issue. 
Applies to HAPI v5.6.0.
[hapi_issue_3261.patch.txt](https://github.com/hapifhir/hapi-fhir/files/7991828/hapi_issue_3261.patch.txt)

**Comment by jamesagnew** [comment]
Thanks for the proposed fix. Submitting PR now.
