### ISSUE TITLE
SearchParameterMap does not support recursive includes

### ISSUE THREAD

**Issue by vilaug** [hapifhir/hapi-fhir#3269]
**Describe the bug**
Recursive includes are changed to regular includes when using `ca.uhn.fhir.jpa.searchparam.SearchParameterMap::toNormalizedQueryString`

**To Reproduce**
1. Set the includes for SearchParameterMap with atleast one recursive
2. Call `SearchParameterMap::toNormalizedQueryString`
3. The string returned will contain only `_include` and no `_include:recurse`

**Expected behavior**
The recursive include is added as `_include:recurse`

**Comment by jarimayenburg** [comment]
Fixed by #3270
