### ISSUE TITLE
ca.uhn.fhir.jpa.search.builder.sql.SearchQueryBuilder fails with new Hibernate (5.6.x)

### ISSUE THREAD

**Issue by Romanow88** [hapifhir/hapi-fhir#3296]
ca.uhn.fhir.jpa.search.builder.sql.SearchQueryBuilder#generate does String#contains checks. These are case sensetive. With newer hibernate versions, the "top(?)" clause is lowercase for SqlServer, which causes the generated sql to fail as the parameter is not added to the bindVariable.

**Comment by jamesagnew** [comment]
Thanks for flagging this! I'm bumping Hibernate now and will account for this change.
