### ISSUE TITLE
HAPI FHIR 5.5.1 Snapshot generator is replacing existing complex data type elements for new slice addition

### ISSUE THREAD

**Issue by Shob-dev** [hapifhir/hapi-fhir#3302]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
HAPI FHIR 5.5.1 snapshot generator is replacing existing complex data type elements with slice element definition

**To Reproduce**
1. Have used base profile as CARIN patient profile from attached file StructureDefinition-C4BB-Patient.json which has "patient.identifier:memberid" and "patient.identifier:uniquememberid" slices.

2. Passed below differential structure definition from attached file differential-carin-bb-patient.son which has new slice "patient.identifier:subscriberid" added to patient.identifier complex data type and used HAPI FHIR SnapshotGenerator to generate the snapshot.
  
3. Attached generated-snapshot.json is the snapshot generated where patient.identifier:memberid" and "patient.identifier:uniquememberid" slices has been completely removed and has only "patient.identifier:subscriberid" instead of additing this slice to existing patient.identifier slices

**Expected behavior**
Expected behavior should be new Patient.identifier:subscriberid slice should have been added to existing patient.identifier:memberid and patient.identifier:uniquememberid slices in the generated snapshot instead of removing the existing identifier slices and  root patient.identfier elements like  patient.identifier.id , ipatient.dentifier.extension, patient.identifier.use,patient.identifier.system,patient.identifier.value from the base snapshot.

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version - 5.5.1
 - OS: [e.g. iOS] - Mac

**Additional context**
[snapshot-generator-issue.zip](https://github.com/hapifhir/hapi-fhir/files/7871911/snapshot-generator-issue.zip)

**Comment by grahamegrieve** [comment]
This should actually be filed under https://github.com/hapifhir/org.hl7.fhir.core, no?

**Comment by Shob-dev** [comment]
I think so. Is there a way to move this issue under  https://github.com/hapifhir/org.hl7.fhir.core or we need to close this and create one in  https://github.com/hapifhir/org.hl7.fhir.core,?

**Comment by Shob-dev** [comment]
Created a new bug  https://github.com/hapifhir/org.hl7.fhir.core/issues/712 under right module https://github.com/hapifhir/org.hl7.fhir.core. Hence closing this bug as this issue will be tracked with https://github.com/hapifhir/org.hl7.fhir.core/issues/712
