### ISSUE TITLE
Make sure thread count is always less than connection count (or throw config warnings on startup)

### ISSUE THREAD

**Issue by TipzCM** [hapifhir/hapi-fhir#3356]
Currently, we have many uses of TransactionDefinition.PROPAGATION_REQUIRES_NEW for subtransactions (typically for saving metadata).

Problem is, if we have every thread using a db connection, and then encounters such a transaction, we can have locks.

We should:
* Document all uses of TransactionTemplate with REQUIRES_NEW
* Use this information to ensure we always have enough connections for configured threads
* Throw config warnings on startup if the configured thread count (plus potential REQUIRES_NEW transaction count) >= configured connection count

**Comment by michaelabuckley** [comment]
The normal java servlet model assumes one thread = one request = one connection.  Calls with REQUIRES_NEW violate that assumption.  Customers have had cases where the system "hangs" - tag create a common case.  To avoid this, we need to ensure there are surplus connections for our calls to REQURIES_NEW.  How many surplus connections do we need?  At least one ;-).

**Comment by michaelabuckley** [comment]
Other connection consumers:
- quartz (1 continuously?)
- batch jobs
