### ISSUE TITLE
Security Vulnerability with Hibernate-ehcache

### ISSUE THREAD

**Issue by ColumbusDong** [hapifhir/hapi-fhir#3424]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
When scanning a docker image build from the [hapi-fhir-jpaserver-base](https://github.com/hapifhir/hapi-fhir/tree/master/hapi-fhir-jpaserver-base), Twistlock/Prisma reports critical security vulnerability:
`com.fasterxml.jackson.core_jackson-databind version 2.9.6 has 56 vulnerabilities.`

com.fasterxml.jackson.core_jackson-databind is a dependency of `ehcache`, which is a dependency of `hibernate-ehcache`. `hibernate-ehcache` has not updated the version of `ehcache` (2.10.6) that they use in 4 years, and that version of `ehcache` uses `jackson-databind` version 2.9.6 which has a critical security vulnerability.  

**Expected behavior**

Twistlock/Prisma should find no critical security vulnerabilities while scanning any image build from the hapi-fhir-jpaserver-base.

**Screenshots**
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/11592570/155614411-c7563037-8c24-40c9-98c2-952961bb1fb9.png">

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/11592570/155614494-03809716-e53b-479e-ba96-a615e4e83456.png">

**Environment (please complete the following information):**
 - HAPI FHIR Version 

**Additional context**

**Comment by jamesagnew** [comment]
The current `Master` (for 6.0.0 snapshot builds) has removed ehcache as a dependency entirely, so this should no longer be an issue. Please feel free to reopen if you see this on current master.
