### ISSUE TITLE
as of hapi-fhir v5.7.0, hapi-fhir-cli no longer supports MySQL 5.7

### ISSUE THREAD

**Issue by jschneid-nmdp** [hapifhir/hapi-fhir#3444]
**Describe the bug**
Version 5.7.0 of the hapi-fhir-cli tool fails to execute the "migrate-database" command when used with a MySQL 5.7 database.  The command exits with an error message saying, "org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 5.7".

This change is not mentioned in the HAPI FHIR 5.7.0 release notes.

Newer versions of the Flyway "community edition" apparently do not support MySQL 5.7.  A comment on [Flyway issue 3319](https://github.com/flyway/flyway/issues/3319) indicates, "You can [request a trial license for Teams](https://flywaydb.org/download/teams) or downgrade to Flyway version 7.15 for the time being."

Example error message:
```
$ ./hapi-fhir-cli migrate-database -d MYSQL_5_7 -n myuser -p secret -u 'jdbc:mysql://localhost:3306/fhir_r3'
------------------------------------------------------------
🔥  HAPI FHIR 5.7.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 19704@A0505825
Max configured JVM memory (Xmx) : 4.0GB
Detected Java version           : 13.0.2
------------------------------------------------------------
2022-03-03 09:53:27.957 [main] INFO  ca.uhn.fhir.cli.App Logging configuration set from file logback-cli-on.xml
2022-03-03 09:53:28.845 [main] ERROR ca.uhn.fhir.cli.App Error during execution: 
org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 5.7
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:106)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:143)
	at org.flywaydb.core.Flyway.repair(Flyway.java:335)
	at ca.uhn.fhir.jpa.migrate.FlywayMigrator.migrate(FlywayMigrator.java:63)
	at ca.uhn.fhir.cli.BaseFlywayMigrateDatabaseCommand.run(BaseFlywayMigrateDatabaseCommand.java:142)
	at ca.uhn.fhir.cli.HapiFlywayMigrateDatabaseCommand.run(HapiFlywayMigrateDatabaseCommand.java:56)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:254)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2022-03-03 09:53:28.846 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
```

**To Reproduce**
1. Download hapi-fhir-5.7.0-cli.tar.bz2 from the hapi-fhir GitHub releases page.
2. Start a MySQL 5.7 database server (ideally, loaded with hapi-fhir data).
3. Attempt to execute the "hapi-fhir-cli migrate-database" command, e.g. "./hapi-fhir-cli migrate-database -d MYSQL_5_7 -n myuser -p secret -u 'jdbc:mysql://localhost:3306/fhir_r3'"
4. See error message saying, "org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 5.7".

**Expected behavior**
The "hapi-fhir-cli migrate-database" command should successfully update the MySQL 5.7 database schema.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.7.0
 - OS: MacOS 10.15.7
 - Browser N/A

**Additional context**

**Comment by KevinDougan-SmileCDR** [comment]
Try using the `--dont-use-flyway` option when upgrading your databae.

From the command-line help:

```
     --dont-use-flyway           If this option is set, the migrator will not
                                 use FlywayDB for migration. This setting should
                                 only be used if you are trying to migrate a
                                 legacy database platform that is not supported
                                 by FlywayDB.
```

**Comment by jschneid-nmdp** [comment]
Thanks!  The `--dont-use-flyway` options looks like it worked.

The MySQL 5.7 database had already been migrated to hapi-fhir v5.6.0, so watching the migrate-database process cycle through all migrations since 3_3_0.20180115.0 was slightly unnerving, but most of them said "No action performed", "No action needed", or "NopTask".

**Comment by KevinDougan-SmileCDR** [comment]
Closing this since the work-around resolved the problem.
