### ISSUE TITLE
org.hl7.fhir.r5.utils.FHIRLexer$FHIRLexerException in AppointmentCreation (R5)

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir#3459]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**

**To Reproduce**
1. Go to the offical test server http://hapi.fhir.org/create (R5)
2. Create a new appointment
3. Provide this as an example body:

`Request Body | {     "resourceType": "Appointment",     "identifier": [         {             "use": "secondary",             "system": "https://myserver.de/schedule/",             "value": "62211f8ca513460c127315af"         },         {             "use": "usual",             "value": "iatros-fhir-connector"         }     ] }`

**Expected behavior**
It should work and return the created Appointment

**Screenshots**
![image](https://user-images.githubusercontent.com/522403/157245184-37ddc258-7169-48e2-b98c-de31fd8cc58d.png)

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.7.0 

**Additional context**
We have the problem on 5,7,0, however as shown above it seems to exist in 6.0.0-PRE5 as well

**Comment by ZuSe** [comment]
@jamesagnew  I have in mind that we had a similar problem before. I think you told me that it comes from hapi-core, shall I create the issue over there?

**Comment by BSVogler** [comment]
Same thing happens with the minimum example
```json
{
	"resourceType": "Appointment"
}
```

**Comment by BSVogler** [comment]
We investigated and found the cause of the bug: R5 introduces the search parameter`(start | requestedPeriod.start).first()` for Appointment. The search parameters are used when populating a resource (`populateFromResource`). [Then a split is performed on this string](https://github.com/hapifhir/hapi-fhir/blob/05bc20819242b064ae29b55fcde44179a7a4fe9b/hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/extractor/BaseSearchParamExtractor.java#L1020). This split causes the chunks to be in violation of the grammar as it is split into `(start`. Not sure where the grammar of it is defined but the parsing with a simple split is not working in this case.

**Comment by BSVogler** [comment]
This fixes the issue. However it is really hacky and I have not fully tested it.

```java
	private <T> void extractSearchParam(RuntimeSearchParam theSearchParameterDef, IBaseResource theResource, IExtractor<T> theExtractor, SearchParamSet<T> theSetToPopulate, boolean theWantLocalReferences) {
		String nextPathUnsplit = theSearchParameterDef.getPath();
		if (isBlank(nextPathUnsplit)) {
			return;
		}

		String[] splitPaths = split(nextPathUnsplit);
		boolean recursion = false;
		for (String nextPath : splitPaths) {
			nextPath = trim(nextPath);
			// check if split inside brackets
			if (nextPath.contains("(") && !nextPath.contains(")")) {
				nextPath = nextPath.substring(1); //asuming the string starts with (
				recursion = true;
			} else if (!nextPath.contains("(") && nextPath.contains(")")  || nextPath.indexOf(")") < nextPath.indexOf("(")) {
				nextPath = nextPath.substring(0,nextPath.indexOf(")"));
				recursion = true;
			}
			//join outer level of the recursion
			if (recursion){
				String upper_recursion = nextPathUnsplit.substring(nextPathUnsplit.indexOf(")")+1);
				nextPath = nextPath+upper_recursion;
			}
			for (IBase nextObject : extractValues(nextPath, theResource)) {
				if (nextObject != null) {
					String typeName = toRootTypeName(nextObject);
					if (!myIgnoredForSearchDatatypes.contains(typeName)) {
						theExtractor.extract(theSetToPopulate, theSearchParameterDef, nextObject, nextPath, theWantLocalReferences);
					}
				}
			}
		}
	}
```

**Comment by tadgh** [comment]
We've run into this bug before with the splitter, let me see if i can replicate this on master.

**Comment by tadgh** [comment]
I've got a fix working, will ensure it works for all other tests as well. I fixed this previously when we noticed that DSTU3 used pipes occasionally within parentheses (indicating that the path should _not_ be split), but this fix didn't propagate above R4.
