### ISSUE TITLE
"or" is not supported in FHIRPath .where() function in STU3

### ISSUE THREAD

**Issue by RitikaSmile** [hapifhir/hapi-fhir#3469]
**Describe the bug**
Unable to use an 'OR' condition within the where function in DSTU3 whereas the same operation works for R4.

**To Reproduce**

1. Set up the system with DSTU3
2. Add a SearchParameter similar to the below-
{
"resourceType":"SearchParameter",
"id":"patient-phoneUnformatted",
"title":"Phone number without formatting",
"url":"hssc-smilecdr-d.clemson.edu:28000/SearchParameter/phoneUnformatted",
"name":"phoneUnformatted",
"status":"active",
"code":"phoneUnformtted",
"base":["Patient"],
"type":"token",
"description":"Phone number without any formatting",
"expression":"Patient.telecom.where(system='phone' and (use='home' or use='mobile')).value.select(replaceMatches('[^0-9]+',''))",
"xpathUsage":"normal"
}
3. The error returned:

"HAPI-1119: The expression \"Patient.telecom.where(use=&apos;home&apos;\" can not be evaluated and may be invalid: HAPI-0607: org.hl7.fhir.dstu3.utils.FHIRLexer$FHIRLexerException: Error at 1, 1: The token null is not expected here - either a &quot;,&quot; or a &quot;)&quot; expected"

Note: If we change it to just be an '**and**' as follows, it creates the SearchParameter successfully. Also, working fine with the R4 version.
"expression":"Patient.telecom.where(use='home' and use='mobile').value.select(replaceMatches('[^0-9]+',''))",

**Expected behavior**
The 'OR' expression should help create the SearchParameter successfully.

**Screenshots**
<img width="915" alt="Screen Shot 2022-03-11 at 4 58 41 PM" src="https://user-images.githubusercontent.com/96147561/158437438-9cad94cd-9389-4634-970c-c89df715b860.png">

**Environment (please complete the following information):**
 - HAPI FHIR Version [ HAPI FHIR // 6.0.0-PRE3-SNAPSHOT / build c9b87d7c67 2022-02-25]
 - Browser  [chrome]

**Additional context**

**Comment by tadgh** [comment]
@dotasek
