### ISSUE TITLE
Add New Index On HFJ_RESOURCE For $reindex Operation

### ISSUE THREAD

**Issue by KevinDougan-SmileCDR** [hapifhir/hapi-fhir#3534]
The `$reindex` Operation takes a very long time to gather the list of Resources to be used in that Operation.

An example request would look like:
```
POST http://myfhirserver.com:8000/$reindex
{
  "resourceType": "Parameters",
  "parameter": [ {
    "name": "url",
    "valueString": "Organization?"
  } ]
}
```

The SQL Query it generates is:
```
SELECT t0.RES_ID 
FROM HFJ_RESOURCE t0 
WHERE (((t0.RES_TYPE = 'Organization') 
  AND (t0.RES_DELETED_AT IS NULL)) 
  AND (t0.RES_UPDATED <= '2021-11-30 10:17:11.119')) 
ORDER BY t0.RES_UPDATED DESC NULLS LAST limit 800;
```

On a sample Postgres database loaded with data, this query takes almost 10 minutes to complete. See the internal Wiki for all the Query Plan details.

When I add the following Index on the HFJ_RESOURCE Table:
```
CREATE INDEX CONCURRENTLY idx_res_type_del_updated ON hfj_resource USING btree (res_type, res_deleted_at, res_updated, res_id);
```
the same query can use the Index to gather all the required data and it completes in only 16 seconds!

**Rationale for adding this Index to HFJ_RESOURCE**

First of all, I understand that changing anything related to this table is potentially very impactful!

The example that lead me to propose adding this new Index is the `$reindex` operation scenario.

The first thing that a `$reindex` operation does is query the HFJ_RESOURCE table to build a list of resources to be re-indexed. In a "real-world scenario", which means a database with many resources such as the sample database that I am working with, this initial query can take more than 10 minutes to complete, and can fail due to database query timeout errors.

Many sites will perform a `$reindex` operation on a specific resource type, rather than the entire database. That implies that several of these _Full Table Scan_ queries will be needed in order to finish a full re-index, which means a lot more long-running queries.

Additionally, this proposed Index is not only good for this one scenario, even though this one is fairly generic and common, but it also satisfies the Index Demand of a different scenario that has been raised as a problem. In that other scenario, the query in question requires 2 of the 3 columns being indexed, so it is satisfied with using this Index in that query to return the `res_id` values. This aligns with the SQL Performance initiative which encourages you to create the minimal amount of indexes to satisfy the entire set of queries in a system.

**Comment by michaelabuckley** [comment]
Please add partition_id to the end of the column list, to support partitioned instances.
