### ISSUE TITLE
Lucene string searches are case-sensitive on newer Elasticsearch

### ISSUE THREAD

**Issue by michaelabuckley** [hapifhir/hapi-fhir#3584]
**Describe the bug**

When using lucene search parameter indexing, `/Patient?name=kelly` produces different results that `/Patient?name=Kelly`.

**To Reproduce**

- Enable lucene indexing and lucene search parameter indexing, configured to use Elasticsearch 7.17 or newer.
- Insert a Patient named Kelly Smith
- Search for `/Patient?name=kelly` and `/Patient?name=Kelly` and compare results.

**Expected behavior**
These searches should return the same results

**Environment (please complete the following information):**
 - Hapi 6.0.0-SNAPSHOT
 - jpa-serverstarter built from the [rel_6_0_0](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/tree/rel_6_0_0) branch
 - Elasticsearch 7.17

**Additional context**

The `wildcard` query is considered a term query, which means it isn't filtered by the analyzer.  Consider using a simple query instead.

**Comment by xluanlhc** [comment]
We observed the issue with Elastic 7.17 but not sure when did the default behavior change (between 7.9 and 7.17). Here is a discussion related to the issue (not related to HAPI FHIR):
   https://discuss.elastic.co/t/search-returning-no-results-after-upgrade-from-7-9-3-to-7-15-0/286739

**Comment by michaelabuckley** [comment]
Fixed in #3596.
