### ISSUE TITLE
Paging on FHIR search results sometimes does not deliver all possible results

### ISSUE THREAD

**Issue by GeorgFette** [hapifhir/hapi-fhir#3599]
When I query the public HAPI FHIR server for the count of available conditions:
http://hapi.fhir.org/baseR4/Condition?_summary=count&_total=accurate
I currently get a total of 64271.
When I query those coditions directly:
http://hapi.fhir.org/baseR4/Condition?_count=500
I get the first page of results and can browse through the pages of this result via the next links.
After 14 times of paging (_getpagesoffset=12000) there is no new next link.
No more further result pages can be retrieved from the query, so the rest of the result cannot be retrieved.

**Comment by jamesagnew** [comment]
The public hapi server has a maximum fetch size of 10,000 resources. This means that it is not possible to fetch more than 10,000 resources in any single query. We do this to limit the load on the server, which people really like to try and abuse with large queries. This is set here: https://github.com/hapifhir/hapi-fhir/blob/cfc8b02b937e9516cc78b89f97fb4ce47b9a86c1/hapi-fhir-jpaserver-uhnfhirtest/src/main/java/ca/uhn/fhirtest/config/TestR4Config.java#L75

This can be configured on your own server using `JpaStorageSettings#setFetchSizeDefaultMaximum`
