### ISSUE TITLE
Hapi shouldn't throw an exception if validation fails

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/hapi-fhir#3611]
Problem:
In [BaseHapiFhirResourceDao](https://github.com/hapifhir/hapi-fhir/blob/544ef3de1bddb6f97349378a7c771461e8c92cf0/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirResourceDao.java#L1911) a PreconditionFailedException is thrown if the Validator returns Errors or Fatal Issues.

Expected behaviour: 
The OperationOutcome is returned, no Exception is thrown. 4xx or 5xx status codes are should only be returned if the validation itself fails: "This operation returns a 200 OK whether or not the resource is valid. A 4xx or 5xx error means that the validation itself could not be performed, and it is unknown whether the resource is valid or not."

**Comment by tadgh** [comment]
Are you working on this one patrick? Just want to check before I open a branch for it.

**Comment by jamesagnew** [comment]
Oh interesting.. this is a change from how it used to work. Agree with your assessment Patrick, we are doing the wrong thing now.

**Comment by patrick-werner** [comment]
> Are you working on this one patrick? Just want to check before I open a branch for it.

no. Just reported it. I checked with 6.0.1: 
hapi still reports 412 on validation errors.
