### ISSUE TITLE
Runtime undeclared extension check should be checking for existence of myRuntimeChildUndeclaredExtensionDefinition rather than the null check

### ISSUE THREAD

**Issue by spawnpoint** [hapifhir/hapi-fhir#3653]
https://github.com/hapifhir/hapi-fhir/blob/c42ecc5c08613d87a4b9c0eb3a6c9d73a2949905/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java#L1001-L1003

should be 

 	if (myRuntimeChildUndeclaredExtensionDefinition != null) { 
 	 	myRuntimeChildUndeclaredExtensionDefinition = scanner.getRuntimeChildUndeclaredExtensionDefinition(); 
 	}

**Comment by jamesagnew** [comment]
Hi @spawnpoint - Any chance you could submit a PR with a test demonstrating the resolution of this issue?
