### ISSUE TITLE
JPA async path is slower now that is synchronous

### ISSUE THREAD

**Issue by michaelabuckley** [hapifhir/hapi-fhir#3664]
**Describe the bug**
The JPA persistence provider became slower when the async cached query threadpool was removed.

## To Reproduce
Steps to reproduce the behaviour:
1. Install 5.3
2. Load some synthea data
3. Make a query that returns more that 500 results. E.g. /Observation?status=active
4. Upgrade to 6.0
5. Compare results
6. The new server is much slower.  E.g. 200ms vs 30ms.

## Expected behaviour
Sub 50ms response

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.0 vs 5.3
 - Postgres

**Comment by michaelabuckley** [comment]
This one looks related - https://github.com/hapifhir/hapi-fhir/issues/866

**Comment by jamesagnew** [comment]
That #866 suggestion is a really good one.

**Comment by michaelabuckley** [comment]
This bug got fixed elsewhere by limiting the ES prefetch- https://github.com/hapifhir/hapi-fhir/issues/860

See also https://github.com/hapifhir/hapi-fhir/issues/536

A modification of #866 is drop the pid, and use a composite PK - (search_pid, search_order).  Both of these are known at insert time, and they are small.

Need to test if the inserts are actually batched, and turn that on by default in our props.
