### ISSUE TITLE
Search by id is returning a deleted resource with a client generated id

### ISSUE THREAD

**Issue by nathandoef** [hapifhir/hapi-fhir#3693]
**Describe the bug**
When searching for a deleted resource with a client generated id (i.e. added via PUT) using `_id`, the returned bundle includes the deleted resource in the total count.

**To Reproduce**
1. Create a Patient with a client-generated id via HTTP PUT (i.e. AAA)
2. Delete the Patient
3. Search for the deleted Patient using `_id` (issue persists when `Cache-Control:  no-cache`)
4. The returned bundle has a total count of 1 with no resources in the `entry` field

**Expected behavior**
The returned bundle should have a total value of 0 and no resources in the `entry` field

**Environment**
 - HAPI-FHIR: 6.0.1

**Comment by jhoeflaken** [comment]
Hi,

I am using v6.2.5 but still see that resources marked as deleted are included in the total of the bundle when executing a REST search using the Spring Boot JPA Server implementation, while the resulting bundle does only include the non-deleted ones. Does this fix not fix the issue I perceive? 

Kind regards,

Jacob

**Comment by neumartin** [comment]
Try to search using GET with headers Cache-Control: no-cache, in version 7 works.
