### ISSUE TITLE
MPI_LINK Query Performance Improvement Needed

### ISSUE THREAD

**Issue by kateryna-mironova** [hapifhir/hapi-fhir#3702]
While importing Patient data with MDM enabled, we noticed that queries on the MPI_LINK table were performing poorly and being raised in the AWS Console as a "Top 2 Most Active Query".

We added the following Index and it improved our performance:

```
CREATE INDEX CONCURRENTLY idx_empi_match_tgt_ver ON mpi_link USING btree (match_result, target_pid, version);
```

**Comment by tadgh** [comment]
Super interesting. By any chance can you share the size of that table in rows?  I would be happy to add this index if it provides a nice improvement.
