### ISSUE TITLE
Add support for ICD-10 (International Version)

### ISSUE THREAD

**Issue by kaicode** [hapifhir/hapi-fhir#3734]
**Context**
I'm working on [Snowstorm](https://github.com/IHTSDO/snowstorm), the SNOMED International terminology server. 
  I'm making a major update to allow serving any code system, not just SNOMED CT, via the Snowstorm FHIR API.
  Snowstorm uses this brilliant HAPI-FHIR library!

**Feature Request**
Several of our members use the International version of ICD-10 so I would like to add support for loading this. I'm creating this issue ahead of submitting a PR for this feature if that's okay?

**Comment by KevinDougan-SmileCDR** [comment]
Support for uploading ICD-10 has already been added:

https://hapifhir.io/hapi-fhir/docs/tools/hapi_fhir_cli.html#upload-terminology

**Comment by kaicode** [comment]
That looks like ICD-10-**CM** which is the US variant of the standard which has the code system URL `http://hl7.org/fhir/sid/icd-10-cm`

This issue is about the international version of ICD-10 which has the system URL `http://hl7.org/fhir/sid/icd-10`.

See [Using ICD-[X] Codes with FHIR](https://www.hl7.org/fhir/icd.html#4.3.11.1).

**Comment by kaicode** [comment]
Although the two standards sound the same the US version uses a tabular format whereas the International version uses ClaML format. So unfortunately the ICD-10-CM loader can not be used to load ICD-10 (International).

**Comment by KevinDougan-SmileCDR** [comment]
Ah, I mis-read your Issue and I did remember when ICD-10 support was added recently, so I thought you hadn;t seen that latest update ... sorry about that!

Yes, I believe a PR adding support would be great, thanks!

**Comment by kaicode** [comment]
PR created #3849

**Comment by psavva** [comment]
Hi,

Where can I download the ICD-10 International Version (ZIP File) to upload into HapiFhir?

**Comment by kaicode** [comment]
I last downloaded the ICD-10 International ClaML files from the [WHO ICD download page](https://apps.who.int/classifications/apps/icd/ClassificationDownloadNR/list.htm) but that page looks broken now, there are no download links.

**Comment by psavva** [comment]
> 

Thank you very much

**Comment by LizaKing0** [comment]
Hi @kaicode,
I think the location of the file has changed since your reply. Do you perhaps know where it has moved to? On the download page I can only find PDF updates for ICD-10, and no ClaML files. Thanks in advance!

**Comment by kaicode** [comment]
I've spent a long time looking through the WHO websites but can not find the ICD-10 ClaML files. It's possible to find documents about various ICD-10 updates but getting standardised machine readable data is harder.

I've emailed one of their teams to ask.

**Comment by kaicode** [comment]
I'm still trying to get hold of the official download page for this file.
In the short term this is a copy of [icdClaML2019ens.zip](https://github.com/user-attachments/files/17428684/icdClaML2019ens.zip) that I downloaded from the official ICD website last year.

**Comment by HengJayWang** [comment]
Hi @LizaKing0 & @kaicode,

I found the ICD-10 ClaML file from https://icdcdn.who.int/icd10/index.html

**Comment by kaicode** [comment]
Thank you @HengJayWang , great find 👍
