### ISSUE TITLE
posting Observations not working (InvalidRequestException) when lastN is enabled

### ISSUE THREAD

**Issue by BSVogler** [hapifhir/hapi-fhir#3739]
When enabling option `lastn_enabled` writing observations e.g. by POST results in an error message by InvalidRequestException
[potential line](https://github.com/hapifhir/hapi-fhir/blob/581f40f37351c69cc3ffab03e9824abcb8d4a1ee/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/lastn/ElasticsearchSvcImpl.java#L738)

**Environment:**
- hapi-fhir 6.0.1 or 6.0.2
- in combination with Elastic Search bitnami/elasticsearch:8.2.3-debian-11-r0

**Comment by ZuSe** [comment]
I can confirm this. Running latest jpa-starter.

Environment:
-  Ubuntu 22.04
-  OpenJDK 17
-  Springboot (distroless)
-  Elastic 8.2.2
-  PostgreSQL 14.0
-  HAPI 6.0.2

**Comment by adriangitvitz** [comment]
For me the error seems to be thrown when the test ( ElasticsearchLastNR4IT ) tries to create the observation resource, after creating the Patient

```java
IIdType obsId = ourClient.create().resource(obs).execute().getId().toUnqualifiedVersionless();
```

Logs:

WARN  c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:182] Failure during REST processing: ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HAPI-1190: Unable to persist Observation Code document 4887be16-4b73-410c-a676-4b476e317fa0

fhirtest.access [LoggingInterceptor.java:159] ERROR - POST http://localhost:33133/fhir/Observation
