### ISSUE TITLE
Create operations going through SearchNarrowingInterceptor

### ISSUE THREAD

**Issue by rogtrifork** [hapifhir/hapi-fhir#3749]
## Describe the bug

Starting with HAPI FHIR 6.0.0, CREATE operations on various resources (such as Observation) go through SearchNarrowingInterceptor unlike in 5.7.x where it did not appear to do so. Is this the new intended behavior or a bug? 

## To Reproduce
Steps to reproduce the behavior: Create a resource on the server and put a breakpoint on [this](https://github.com/hapifhir/hapi-fhir/blob/cc841e16673b01e6e712f6101ccbbb5f92d63f35/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/interceptor/auth/SearchNarrowingInterceptor.java#L149) line 

Example of a test that exhibits the failure can be found [here](https://github.com/trifork/hapi-fhir-jpaserver-starter/blob/99fef97671efa6e985601b23fdaa72ec4e513032/src/test/java/ca/uhn/fhir/jpa/starter/AuthorizationInterceptorTest.java#L331) or alternatively something along the lines would do the trick too:
```java
void sendResource(){
        String ourServerBase = "http://localhost:" + port + "/fhir/";
        client = ctx.newRestfulGenericClient(ourServerBase);
        IBaseResource mockPatient = patientResourceDao.create(new Patient()).getResource();
        Observation observation = new Observation();
        observation.setSubject(new Reference(mockPatient.getIdElement()));
        ICreateTyped observationCreateExecutable = client.create().resource(observation).withAdditionalHeader("Authorization", MOCK_HEADER);
        MethodOutcome outcome = observationCreateExecutable.execute();
}
```

## Expected behavior
I'd expect the `SearchNarrowingInterceptor` to be applied only when specific resources are read and not applied when a resource is created. Similar issue occurs when trying to reach the metadata endpoint, in 5.7.x it would not hit the `SearchNarrowingInterceptor` but now it does.

## Environment (please complete the following information):*
 - HAPI FHIR Version: 6.0.1
 - OS: MacOS Monterey 12.4

**Comment by tadgh** [comment]
Hey there, I found the offending commit (i think) : https://github.com/hapifhir/hapi-fhir/pull/3405 I'm investigating whether this behaviour change was intentional or not.

**Comment by tadgh** [comment]
So, having looked at this, it does make sense for the narrowing interceptor to be hit, but it should immediately drop out when it recognizes that it is not a search that is occurring. Looks like the short-circuit code to drop out of the interceptor was slightly moved. I'm submitting a PR to move it back
