### ISSUE TITLE
HAPI FHIR public test server down

### ISSUE THREAD

**Issue by Eik0fresh** [hapifhir/hapi-fhir#3768]
It seems the server is down again, getting a 502 gateway error when I try to go to:

http://[hapi.fhir.org](http://hapi.fhir.org/)/

**Comment by jamesagnew** [comment]
Please see here for an announcement about this: https://groups.google.com/u/1/g/hapi-fhir/c/jMY934Fgf8w

We are having some network troubles right now, and it has been temporarily moved to http://test.hapifhir.io
