### ISSUE TITLE
hapi 6.0.1 requires a JDK 17 runtime (class file version 61.0)

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/hapi-fhir#3774]
The hapi 6.0.1 client library seems to be built as java 17 bytecode. As hapi still supports java 11 (according to the docu) this might be a mistake.

`Jul 09 14:22:05 vitu-data lab-import-facade-1.0.8.jar[1176]: java.lang.UnsupportedClassVersionError: org/hl7/fhir/instance/model/api/IAnyResource has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

**Comment by jamesagnew** [comment]
This has been flagged as a release blocker for 6.1.0

**Comment by tadgh** [comment]
Heya @patrick-werner , I just spun up a tiny little project which imports the hapi-fhir-client and hapi-fhir-structures, and generates an IGenericClient and makes a capabilities request, and it _seems_ to be working while using JDK 11. Can you give me some replication steps?

**Comment by tadgh** [comment]
Let me clear my local build cache in case I accidentally built a non-jdk-17-pinned-version

**Comment by tadgh** [comment]
Still nothing, JPAServer is cruising along with 6.0.1 and JDK11. Also, I dug into our code, and we had at the time correctly set:
```xml
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <maven.compiler.release>11</maven.compiler.release>
        <maven.compiler.testSource>17</maven.compiler.testSource>
	<maven.compiler.testTarget>17</maven.compiler.testTarget>
        <maven.compiler.testRelease>17</maven.compiler.testRelease>
```

**Comment by patrick-werner** [comment]
Hi @tadgh sorry for my delayed response. I'm on vacation until the end of next week.

here is the relevant part of my pom:
`  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.3.0.RELEASE</version>
  </parent>

  <properties>
    <hapi.version>5.7.2</hapi.version>
  </properties>

  <dependencies>
    
    <dependency>
      <groupId>ca.uhn.hapi.fhir</groupId>
      <artifactId>hapi-fhir-base</artifactId>
      <version>${hapi.version}</version>
    </dependency>

    
    <dependency>
      <groupId>ca.uhn.hapi.fhir</groupId>
      <artifactId>hapi-fhir-server</artifactId>
      <version>${hapi.version}</version>
    </dependency>

    
    <dependency>
      <groupId>ca.uhn.hapi.fhir</groupId>
      <artifactId>hapi-fhir-structures-r4</artifactId>
      <version>${hapi.version}</version>
    </dependency>
    <dependency>
      <groupId>ca.uhn.hapi.fhir</groupId>
      <artifactId>hapi-fhir-client</artifactId>
      <version>${hapi.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-mail</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.20</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>4.0.1</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>`

here is my base 6.0.1: https://echinos-my.sharepoint.com/:u:/g/personal/pw_echinos_eu/EXD1sGLZ9mRDm22FMhcu7ukBpZlHxKGGxckjqFrlHiImrQ?e=QHou95

I hope this helps, i can dig deeper into it after my holiday.

**Comment by tadgh** [comment]
So, I pulled your version off your sharepoint, and it indeed has major version 61. If I pull down the official version from maven (https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/hapi-fhir-base/6.0.1) I get major version 55. Either way, sounds like if you just remove that dependency from your system, and force maven to redownlaod it, your issue should be gone. 

Is there any way you compiled hapi locally and that's the jar its using?

**Comment by patrick-werner** [comment]
@tadgh Yes i compiled hapi locally before (but never changed maven.compiler plugin settings, weird).
I retried my project with 6.0.1 & 6.0.2 -> works.
 Closing.

**Comment by jamesagnew** [comment]
FYI Patrick I bet what happened is that you had hapi open in IDEA/Eclipse and it compiled these classes at JDK17 level, then you built the JAR without running `mvn clean`.

.....I know this pain because I've done it a few times too. 🥇 haha

**Comment by patrick-werner** [comment]
> FYI Patrick I bet what happened is that you had hapi open in IDEA/Eclipse and it compiled these classes at JDK17 level, then you built the JAR without running `mvn clean`.
> 
> .....I know this pain because I've done it a few times too. 🥇 haha

that's a very valid theory. Sorry for the confusion.
