### ISSUE TITLE
[R4/5] Pagination not working on 6.0.x

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir#3780]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
After upgrading to 6.0.2  the server reports the following on large datasets

2022-07-11 21:41:03.555 [http-nio-8080-exec-2] INFO  c.u.f.r.s.m.BaseResourceReturningMethodBinding [BaseResourceReturningMethodBinding.java:213] Found null results but paging provider did not provide an ID to use for paging

**To Reproduce**
1. Upgrade from 5.7.x to 6.0.2
2. Start the server
3. Create more than 100 resources
4. Trigger a default GET request

**Expected behavior**
A next-url should be provided with pagination enabled

**Environment (please complete the following information):**
 - 6.0.2
 - OS: Ubuntu 22.04
 - Browser: NA

**Additional context**

**Comment by tadgh** [comment]
Are you specifically using hapi-fhir-jpaserver-starter? Or do you have your own wrapper around HAPI?

**Comment by ZuSe** [comment]
Hi @tadgh 

we are using the jpa-starter with no wrapper.
I tested it last week with the very plain repo, without any change on the default config and the pagination is not working.
This is the case for 6.0.2 and 6.1.0-PRE16

Best
Patrick

**Comment by ZuSe** [comment]
Were you able to reproduce it? 
I did some rough debugging but couldn't explain which commit/change killed it.
I am just curios to understand what killed it.

**Comment by tadgh** [comment]
I haven't done any replication yet, this is on my list. Will let you know when I find it.

**Comment by tadgh** [comment]
OK, I have written a test for this scenario, and am unable to replicate the problem in pure hapi-fhir. I will need some information from you: 
1. which branch of HAPI-FHIR-jpaserver-starter are you operating on?
2. Which settings have you changed in application.yaml (if any)

I will see if i can replicate on hapi-fhir-jpaserver-starter with no changes, while awaiting your response.

**Comment by ZuSe** [comment]
Hi @tadgh,

we are operating on the master branch to test against 6.0.2 and on the branch rel_6.1.0 to test against 6.1.0-PRE16.
All I changed is the database from H2 to postgres.

```
  datasource:
    url: 'jdbc:postgresql://localhost:5432/fhir_r5_local'
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    max-active: 32
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
```

For 6.1.0 I also had to set
`allow-bean-definition-overriding: true`

Don't you see the error of the pagination provider in your local log? I get it with both, jetty and spring boot.

**Comment by tadgh** [comment]
What I meant to say was that I could not replicate it in a test in hapi fhir which exercises pagination with a live db. I'll try replicating it using jpaserver tomorrow

**Comment by ZuSe** [comment]
ok, thanks!

**Comment by tadgh** [comment]
I just checked out master, wrote a branch with a custom test for paging, and then also physically attempted to page via search. no problems: 

![image](https://user-images.githubusercontent.com/1720433/179806752-0f3766f7-86c6-40bd-b1cb-a640a7282338.png)

Only thing I haven't done is dropped in the Postgres replacement, will try that next

**Comment by tadgh** [comment]
Yup, works with PSQL too. At this point I'm pretty curious. Could you possibly take a screen recording of you: 

1. Start from scratch with master HAPI-FHIR-jpaserver-starter. 
2. modify settings to how you use it. 
3. replicate this bug 


This might help reveal something that I missed in my replication.

**Comment by ZuSe** [comment]
@tadgh on it. Gimme 5-10min

**Comment by ZuSe** [comment]
Here we go:

https://cloud.palacin.eu/index.php/s/7jAJ2cSwfj76kC2

Happy to debug it further. If you want I can also setup a Teams or Zoom call

**Comment by tadgh** [comment]
Thanks patrick, that is very well put together. I will try to do _precisely_ what you did here to see if I can get it replicated.

**Comment by ZuSe** [comment]
Urw, just keep me updated. It's driving me nuts not understanding what is going on. Ofc, your own test didnt make it better, but I would be so happy if we figure out that the problem is only popping up on my side. 

The only thing I could think of is spawning a plain VM that has never run HAPI and try it there. I really wonder why it worked in your test, I just checked your branch of the JPA start repo, more than simple...

**Comment by ZuSe** [comment]
@tadgh We did the test with a plain Mac today that never compiled hapi or jpa starter before. Same problem.

JPA-starter in branch rel_6_1_0 in combination with hapi 6.1.0-PRE16

**Comment by tadgh** [comment]
Hey sorry for the delay on this, I have split priorities at the moment. Attempting to replicate using your video now

**Comment by tadgh** [comment]
Ah shoot, looks like the file was pulled off of nextcloud, and I didnt download it the first time I watched it. Can you send me a fresh link, and i'll re-download it?

**Comment by tadgh** [comment]
Shot in the dark since you didn't mention it in the video, but you aren't using Hibernate Search are you?

**Comment by tadgh** [comment]
Can you do me a favour, and replicate this with this replacement logback.xml?
```
<configuration scan="true" scanPeriod="30 seconds">

	<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
		<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
			<level>DEBUG</level>
		</filter>
		<encoder>
			<pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%file:%line] %msg%n</pattern>
		</encoder>
	</appender>

	<logger name="org.springframework.beans" level="INFO">
		<appender-ref ref="STDOUT" />
	</logger>
	<logger name="org.springframework.core" level="INFO">
		<appender-ref ref="STDOUT" />
	</logger>

	<logger name="ca.uhn.fhir.jpa.search" level="DEBUG">
		<appender-ref ref="STDOUT" />
	</logger>

	<root level="INFO">
		<appender-ref ref="STDOUT" />
	</root>

</configuration>
```

Replicate it and provide me logs here and we'll see what comes about. This logging config should show details of the registered search UUIDs and the total number of results.

**Comment by ZuSe** [comment]
Hi @tadgh here a new link: https://cloud.palacin.eu/index.php/s/Re7mo7mKrWSFrTw

I am gonna run the test with advanced logging now. 

I am using the default config of JPA-Starter. However, also enabling elastic and advanced lucene indexing is not changing anything.

**Comment by ZuSe** [comment]
Please find attached the logs.
[hapi_log_error_in_paging.txt](https://github.com/hapifhir/hapi-fhir/files/9173395/hapi_log_error_in_paging.txt)

**Comment by tadgh** [comment]
Heya... I have an idea. Can you show me the headers tab of your insomnia request? I have a sneaking suspicion that you are using `no-store` as a cache-control header. At timestamp 2:55 you indicate there are no headers, but i see 8 headers in the postman tab. If you indeed have setup no-store as cache-control, that disables paging at the request level. Can you try executing this curl instead of using your postman and see if that alleviates it?

```
curl --request GET \
  --url http://localhost:8080/fhir/Patient \
  --header 'cache-control: no-cache' 
  ```

**Comment by ZuSe** [comment]
good catch. That was the case indeed! no-store got set per default.

**Comment by tadgh** [comment]
no problemo :) i'm just glad it wasn't a core issue in the search builder haha. Have a nice day!
