### ISSUE TITLE
JSON parser ignores Extensions of type valueReference when they are populated in the meta

### ISSUE THREAD

**Issue by DMWhiteley** [hapifhir/hapi-fhir#3890]
**Describe the bug**
This is a constellation of circumstances which ultimately result in extensions being silently dropped from HAPI FHIR objects when they are parsed to JSON.

**To Reproduce**
1. Create any resource. An R4 Appointment is the example we are using.
2. Add a Meta.
3. Add an Extension to that meta.
4. Set the value of the Extension to be a Reference.  Have the Reference be constructed around the target object, not around a string reference, e.g. `new Reference(new Organization().setId("123"));`. If you do `new Reference("Organization/123")` then different fields are set on the Reference and the bug does not manifest.
5. Call `encodeResourceToString()` on a JSON parser off the appropriate FHIR context
6. Extension is missing from the resultant string.

From testing this appears to only be the case when:
1. The Reference is populated using the object constructor, not the string constructor
2. The Extension is stored in the meta

**Expected behavior**
Extensions populated on the object should be parsed to JSON successfully.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.5.3
 - OS: linux
 - Browser: n/a

**Additional context**
An example appointment is below. In this example the extension example-source-team.com is silently dropped. All others are rendered correctly.

```
{
  "appointmentType": {
    "coding": [
      {
        "display": "Eye checkup"
      }
    ]
  },
  "comment": "Your opthamology appointment.  Please arrive ten minutes prior to appointment.",
  "created": "2022-04-14T10:00:00+00:00",
  "end": "2022-04-14T10:00:00.000+00:00",
  "id": "9979deca-443a-459f-9bc0-4f36762a53e9",
  "meta": {
    "extension": [
      {
        "url": "http://example-source-team.com",
        "valueReference": {
          "reference": "Organization/9979deca-443a-459f-9bc0-4f36762a53b9"
        }
      },
      {
        "url": "http://example-source-text.com",
        "valueString": "sourceText"
      },
      {
        "url": "http://example-access-route.com",
        "valueCoding": {
          "code": "WEBAPP",
          "display": "Main website",
          "system": "http://example-access-route-system.com"
        }
      }
    ],
    "lastUpdated": "2022-04-14T10:00:00.000+00:00"
  },
  "participant": [
    {
      "actor": {
        "display": "Opthamology",
        "type": "Location"
      },
      "status": "accepted"
    },
    {
      "actor": {
        "display": "John Doe (Patient)"
      },
      "status": "accepted"
    }
  ],
  "resourceType": "Appointment",
  "serviceType": [
    {
      "coding": [
        {
          "code": "typeCode",
          "system": "typeCodeSystem"
        }
      ]
    }
  ],
  "start": "2022-04-14T10:00:00.000+00:00",
  "status": "booked"
}

**Comment by DMWhiteley** [comment]
Yes, this is parsing from JSON to object rather than the other way around. Please try this test instead:

```
@Test
    public void testParseReferenceExtensionInMeta() {

        Appointment appointment = new Appointment();
        appointment.setId("123");

        Meta meta = new Meta();
        Extension extension = new Extension();
        extension.setUrl("http://example-source-team.com");
        extension.setValue(new Reference(new Organization().setId("546")));
        meta.addExtension(extension);
        appointment.setMeta(meta);

        var parser = FhirContext.forR4().newJsonParser();
        String output = parser.encodeResourceToString(appointment);
        Appointment input = parser.parseResource(Appointment.class, output);

        assertTrue(input.getMeta().getExtensionByUrl("http://example-source-team.com") == null);
    }

**Comment by jamesagnew** [comment]
Ah, it looks like this isn't specific to the JSON parser.

It looks like the `Reference#copy()` method doesn't preserve the resource value in references. That's the root cause here.
