### ISSUE TITLE
Deleting non-exist resources will provide a response successfully deleted

### ISSUE THREAD

**Issue by MykolaMedynskyiSCDR** [hapifhir/hapi-fhir#3897]
**Describe the bug**
Deleting non-existing and already deleted resources will provide a response "successfully deleted"

**To Reproduce**
1. DELETE http://localhost:8000/Patient/12345
2. See error

**Expected behavior**
response 200, display reasonable error message

**Comment by jamesagnew** [comment]
Per the [spec](http://hl7.org/fhir/http.html#delete):

> Upon successful deletion, or if the resource does not exist at all, the server should return either a 200 OK if the response contains a payload, or a 204 No Content with no response payload, or a 202 Accepted if the server wishes to be non-commital about the outcome of the delete. 

Do you feel that we are not in alignment with the way the spec says this should work?

**Comment by jamesagnew** [comment]
Oh wait, I read the bug ticket backward - You're saying we don't currently return a 200 but we should, yes?

**Comment by epeartree** [comment]
The implementation follows the spec.  The issue which should have been better explained, is about the message returned to the caller on a delete operation for a non-existing or already deleted resource.  In both of these cases, the implementation returns message 
`Successfully deleted 1 resource` although no resources were deleted.

The pull request associated with this issue aims at providing responses messages aligned with the actual operation result.

**Comment by jamesagnew** [comment]
@epeartree ahh got it. Yeah, that does sound like a good improvement.
