### ISSUE TITLE
Bulk Expunge of large amounts of data in sql backed dbs fails

### ISSUE THREAD

**Issue by TipzCM** [hapifhir/hapi-fhir#3922]
Trying to delete a large amount of resources (in an SQL database) with $delete-expunge results in SQL failures.

**Comment by KevinDougan-SmileCDR** [comment]
It looks like this Issue was fixed via this Pull Request:

https://github.com/hapifhir/hapi-fhir/pull/3923

**Comment by TipzCM** [comment]
As cited above, closed by #3923
