### ISSUE TITLE
Why are distributions missing from some releases ?

### ISSUE THREAD

**Issue by tyfoni-systematic** [hapifhir/hapi-fhir#3976]
When we choose to upgrade to a new release we use the hapi-fhir-cli to execute schema migration.
But the distributions are not always present in releases:
In https://github.com/hapifhir/hapi-fhir/releases/tag/v6.0.0 there is a hapi-fhir-6.0.0-cli.tar.bz2 (https://github.com/hapifhir/hapi-fhir/releases/download/v6.0.0/hapi-fhir-6.0.0-cli.tar.bz2)
But in https://github.com/hapifhir/hapi-fhir/releases/tag/v6.1.0 there are only source-code.

Our docker build just do:
RUN curl -L -O "https://github.com/jamesagnew/hapi-fhir/releases/download/v${FHIR_VERSION}/hapi-fhir-${FHIR_VERSION}-cli.tar.bz2"

When missing we must build the distribution locally which is inconvenient.

**Comment by tadgh** [comment]
Heya, sorry about this, we are reworking our release automation and there are certainly some bumps in the road as we try to make this a completely touchless process. I'll go ahead and ensure that 6.1.0 has all releases added now. This should be resolved in the future but please let me know if you see any others.

**Comment by tyfoni-systematic** [comment]
Thanks
