### ISSUE TITLE
Resolution for _include by canonical reference

### ISSUE THREAD

**Issue by Capt-Mac** [hapifhir/hapi-fhir#4001]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
Currently the _include Search Parameter resolves references by relative reference, but not by canonical reference.

Reference type Search Parameters should also resolve by canonical or absolute urls: http://www.hl7.org/fhir/search.html#reference 

-- [parameter]=[url] where the [url] is an absolute URL - a reference to a resource by its absolute location, or by it's canonical URL

Example: {{fhirbase}}/Library?context-type=program&_include=Library:composed-of
Works:
"relatedArtifact": [
{
"type": "composed-of",
"resource": "Measure/HTN1Measure"
}
]

Does not work:

"relatedArtifact": [
{
"type": "composed-of",
"resource": "http://cds.optum.com/dqm-hypertension/fhir/Measure/HTN1Measure"
}
]

**To Reproduce**
1. put 'CanonicalHTN1Measure' file to server (using attached files in zip)
2. put non-canonical measure 'HTN1Measure' to server
3. put library 'HypertensionManagementProgram' to server
4. Then run get query {{fhirbase}}/Library?context-type=program&_include=Library:composed-of
5. This only results in finding measure with non-canonical measure

**Expected behavior**
This should have returned results for the two measures both canonical and non-canonical, but only was able to find relative reference "Measure/HTN1Measure"

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.5.3
 - OS: Running on mac OS within docker container

**Additional context**
This is using the https://github.com/DBCG/cqf-ruler docker container to run hapi 5.5.3

[canonicalurlexamples.zip](https://github.com/hapifhir/hapi-fhir/files/9508686/canonicalurlexamples.zip)

**Comment by michaelabuckley** [comment]
Fixed in #3440
