### ISSUE TITLE
Hardcoded lowercase hfj_res_link table name in hapi-fhir-jpaserver-base-6.1.0.jar at ca.uhn.fhir.jpa.search.builder.SearchBuilder at line 1148

### ISSUE THREAD

**Issue by jzhou-maxmd** [hapifhir/hapi-fhir#4014]
Hello,

We noticed an issue using the _include and _revinclude search parameters on our FHIR server built on hapi-fhir 6.1.0.
We are using 10.2.44-MariaDB on a Linux system.

We saw a reference to SearchBuilder in hapi-fhir-jpaserver-base-6.1.0.jar at ca.uhn.fhir.jpa.search.builder.
Lines 1147-1151 shows a hardcoded reference to hfj_res_link that is causing an error due to mismatched case to the SQL table names.

StringBuilder resourceIdBasedQuery = new StringBuilder("SELECT " + fieldsToLoad +
							" FROM hfj_res_link r " +
							" WHERE r.src_path = :src_path AND " +
							" r.target_resource_id IS NOT NULL AND " +
							" r." + searchPidFieldSqlColumn + " IN (:target_pids) ");

**Comment by agnesguion** [comment]
Hello, we have the same issue with MariaDB. 
This is a big problem for us and we can't upgrade to HAPI 6

**Comment by KevinDougan-SmileCDR** [comment]
Configure your DB Server to IGNORE CASE for SQL queries:

https://www.simplified.guide/mysql-mariadb/case-insensitive-table-linux
