### ISSUE TITLE
Bulk export to support [fhir base]/Patient/[id]/$export endpoint

### ISSUE THREAD

**Issue by StevenXLi** [hapifhir/hapi-fhir#4030]
**Describe the issue**
Currently we support bulk export requests at the endpoint [fhir base]/Patient/$export, need to add support for single patient's records through the [fhir base]/Patient/[id]/$export endpoint.

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.2.0
 - OS: MacOS
 - Browser chrome

**Comment by dmuylwyk** [comment]
FYSA, here's a ticket I've filed against PDex regarding the suspect request pattern they've described for Patient-level exports:

https://jira.hl7.org/browse/FHIR-38650
