### ISSUE TITLE
Align :text query sytax with Hapi string search

### ISSUE THREAD

**Issue by michaelabuckley** [hapifhir/hapi-fhir#4034]
**Describe the issue**
The new :text support using lucene/elasticsearch uses the standard [Lucene Simple Query Syntax](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-query-notes) for queries.  In this syntax, bare tokens are treated as quoted strings (i.e. string match instead of prefix match), and a trailing `*` is required for prefix match.  But prefix match is the standard match for Hapi string searching.

Instead, let's change the default for unquoted tokens to be prefix match. 

Current
- Smit - matches "smit", but not "smith"
- Smit* - matches "smit" and "smith"
- "Smit"- matches "smit", but not "smith"

Proposed
- Smit - matches "smit" and "smith"
- Smit* - matches "smit" and "smith"
- "Smit"- matches "smit", but not "smith"

** Design details

Propose:
- tokenize the query string on whitespace
- add * to all unquoted tokens that do not contain *

E.g.
| query input.      | translated SQS query     | Note |
|----------------|-----------------------|---- |
| smit                   | smit*      |
| smit*                   | smit*      |
| sm*t                   | sm*t      | Only matches tokens ending in "t" |
| "smit"                   | "smit"      |
| Frank  Smit      |  Frank*  Smit* |
| Frank "Smit"     |  Frank* "Smit" |

**Environment (please complete the following information):**
Hapi since 6.0

**Comment by jmarchionatto** [comment]
Fixed by: https://github.com/hapifhir/hapi-fhir/pull/4045
