### ISSUE TITLE
Internal Server error getting from hapi server while accessing all swagger API from 9/19/2022

### ISSUE THREAD

**Issue by jibinjacz** [hapifhir/hapi-fhir#4044]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version

**Additional context**

**Comment by jibinjacz** [comment]
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>HAPI-0389: Failed to call access method: org.springframework.dao.InvalidDataAccessApiUsageException: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled.</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "HAPI-0389: Failed to call access method: org.springframework.dao.InvalidDataAccessApiUsageException: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled."
    }
  ]
}

**Comment by jamesagnew** [comment]
Server was restarted
