### ISSUE TITLE
Search modifiers are ignored in chained searches

### ISSUE THREAD

**Issue by munirabidks** [hapifhir/hapi-fhir#4060]
**Details**
When requesting a query with chained params (ServiceRequest?patient:Patient.family:contains=nes), expected result set is not returned when first letters are not included in the value. It should return the result because “jones” contains letters “nes”. 

**Example**
http://hapi.fhir.org/baseR4/ServiceRequest?patient:Patient.family:contains=jones
This url work fine and returns expected result set.
But if we remove first letters from name e.g. replacing “jones” with ending letters “nes” do not returns expected result set. See below url for example.
[ http://hapi.fhir.org/baseR4/ServiceRequest?patient:Patient.family:contains=nes](https://hapi.fhir.tw/fhir/ServiceRequest?patient:Patient.family:contains=nes&_total=accurate)

**Current**
Consider the following in this scenario with given name jones and query with a contains modifier.
 - jones – matches jones
 - jon – matches jones
 - nes – do not match jones

**Expected**
 - jones – matches jones
 - jon – matches jones
 - nes – matches jones

**Environment (please complete the following information):**
 - HAPI FHIR Version-: HAPI FHIR 6.0.0-PRE8-SNAPSHOT

**Comment by reasonableJP** [comment]
Just wanted to confirm that this issue is still present in version HAPI FHIR 6.5.0-SNAPSHOT/148cbf119b/2023-02-05

https://hapi.fhir.org/baseR4/Patient?family:contains=nes 
works as expected, but
https://hapi.fhir.org/baseR4/ServiceRequest?patient.family:contains=nes
returns no results

**Comment by freiric** [comment]
Is it intended to work? It is a genuine question. My understanding is that it would be a feature going beyond the FHIR specification.
The [specification](http://hl7.org/fhir/search.html#chaining) mentions that "chained search parameters are not intended to work with [search modifiers](http://hl7.org/fhir/search.html#modifiers)."

**Comment by reasonableJP** [comment]
> Is it intended to work? It is a genuine question. My understanding is that it would be a feature going beyond the FHIR specification. The [specification](http://hl7.org/fhir/search.html#chaining) mentions that "chained search parameters are not intended to work with [search modifiers](http://hl7.org/fhir/search.html#modifiers)."

Thank you for pointing this out. This is not mentioned explicitly in [version R4](http://hl7.org/fhir/R4/search.html#chaining), which is what we are currently working with. Thus we were unaware.

Issue can be closed.
