### ISSUE TITLE
Use one Elastic Instance for multiple deployments

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir#4077]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the issue**
For development purpose we are running multiple FHIR-server instances within our development cluster (k8s). To save resources, we tried to share the ES-Server across all FHIR-Servers. While such an approach is possible for PSQL or redis, it doesn't seem for ES. The servers are interfering each others and access all the same indices. 

Would it be possible to add prefixes to the indices of each FHIR server appliance or make one server create a main index and put all other indices under it?

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.1
 - OS: Ubuntu 22.04 / K8S 1.24
 - ES: 7.16

**Comment by tadgh** [comment]
Heya, this already exists, via the elasticsearch index prefix setting. 

- https://github.com/hapifhir/hapi-fhir/issues/2962
- https://github.com/hapifhir/hapi-fhir/pull/2963


This setting is available on DaoConfig as `setElasticSearchIndexPrefix(String prefix)`

**Comment by ZuSe** [comment]
Hi tadgh, 

you saved my day. Should be easy to bring this to the jpa starter

**Comment by tadgh** [comment]
Ah yeah that should definitely be work done in the JPA-server starter project.
