### ISSUE TITLE
Support ONC requirements for Group Bulk Export

### ISSUE THREAD

**Issue by StevenXLi** [hapifhir/hapi-fhir#4080]
**Describe the issue**
ONC requirements mentioned [here](https://www.healthit.gov/test-method/standardized-api-patient-and-population-services#ccg), require that HAPI-FHIR be able to include Practitioner, Organization, Device and Location resources as part of the responses for requests for multiple patient Group Bulk Export. The resources are referenced within the resources that is a part of the patient compartment.

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.2.0
 - OS: MacOS
 - Browser: chrome

**Comment by sjayswal** [comment]
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/446
its not resolved yet in 6.2.0 pre18.
