### ISSUE TITLE
[6.1.2] Can not create new resources in patient comparment

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir#4118]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
We have create a custom Interceptor that limits access to the patient's own compartment. Before the upgrade from 6.0.4 to 6.1.2 it was possible for our patients to create resources within their compartment (e.g. Observation, Coverage etc.). After the upgrade the same RuleBuilder rejects the requests that worked before. 

**To Reproduce**
1. Use the latest jpa starter
2. setup an auth interceptor with the following Rule:
```
		if (userId != null) {
			return new RuleBuilder()
				.allow("Allow PATCH").patch().allRequests().andThen()
				.allow("Allow reading all resources in patient compartment").read().allResources()
				.inCompartment(Patient.class.getSimpleName(), userId).andThen()
				.allow("Allow writing all resources to patient").write().allResources()
				.inCompartment(Patient.class.getSimpleName(), userId).andThen()
				.allow("Allow creating new patients").write().resourcesOfType(Patient.class).withAnyId().andThen()
				.allow("Allow reading Activity Definitions").read().resourcesOfType(ActivityDefinition.class).withAnyId().andThen()
				.allow("Allow reading ValueSets").read().resourcesOfType(ValueSet.class).withAnyId().andThen()
				.allow("Allow reading Questionnaires").read().resourcesOfType(Questionnaire.class).withAnyId().andThen()
				.allow().transaction().withAnyOperation().andApplyNormalRules().andThen()
				.denyAll("Limit Access to Patient Compartment")
				.build();
		}
```
4. Do a request as a user that is identified by the interceptor (the id needs to be derived from the token)
5. See error

**Expected behavior**
Patients should be able to create resources within their own compartment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/522403/194284956-a9e2af4d-1c28-4e53-9608-8dc285ba5ec1.png)

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.1.2
 - OS: Ubuntu 22.04
 - Browser: Postman
 - Authentication: OIDC Bearer
 - Context: R5

**Additional context**
Example for userId: Patient/9f99f236-82f0-4fc9-a223-cf78330d64e2

**Comment by ZuSe** [comment]
It seems like the payor attribute in the coverage is breaking the compartment logic. I really can't explain why as it has been working before.

**Comment by tadgh** [comment]
Did you mean to close this?
