### ISSUE TITLE
One source record can be matched with two Golden record creating two match links

### ISSUE THREAD

**Issue by PreethiRadha** [hapifhir/hapi-fhir#4156]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
In MDM when one source resource is a possible match to two different Golden resources, accepting both possible match record creates 2 match links (manual) in single source

**To Reproduce**
1. Create two different Patient resources thus creating two Golden records
2. Create a patient resource with info that connects with already created Golden records thus creating two possible match record
3. Accept both the possible match records 

**Expected behavior**
One source record should only be matched with one Golden record, In this case one source is linked with two Golden record

**Screenshots**
N/A

**Environment (please complete the following information):**
 - HAPI FHIR 6.1.1
 - OS: macOS Monterey Version 12.6
 - Browser: Google Chrome Version 105.0.5195.125

**Comment by jmarchionatto** [comment]
Fixed by: https://github.com/hapifhir/hapi-fhir/pull/4344
