### ISSUE TITLE
6.2.0 is missing R4B in forVersionString parsing

### ISSUE THREAD

**Issue by jkiddo** [hapifhir/hapi-fhir#4276]
See - https://github.com/hapifhir/hapi-fhir/blob/a71b8fad56b9c11b0dc5c3575f4552ce48fcc95d/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirVersionEnum.java#L286

**Comment by jamesagnew** [comment]
Fixed in https://github.com/hapifhir/hapi-fhir/pull/4291
