### ISSUE TITLE
Missing R4B support for installing IG's

### ISSUE THREAD

**Issue by jkiddo** [hapifhir/hapi-fhir#4277]
[PackageInstallerSvcImpl](https://github.com/hapifhir/hapi-fhir/blob/a824ba263bf6f99dbb90f697605df74413ff1b74/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageInstallerSvcImpl.java#L139) does not support R4B.

**Comment by jamesagnew** [comment]
Fixed in https://github.com/hapifhir/hapi-fhir/pull/4291
