### ISSUE TITLE
MdmStorageInterceptor Is Unnecessarily Processing Data That Is Not MDM-Related

### ISSUE THREAD

**Issue by samguntersmilecdr** [hapifhir/hapi-fhir#4450]
**Describe the bug**
The `MdmStorageInterceptor` method called `blockManualGoldenResourceManipulationOnUpdate()` is processing data that it doesn't need to process, causing undue processing overhead and also writing log entries that are misleading and unnecessary.

**Comment by KevinDougan-SmileCDR** [comment]
The code can be found here:

https://github.com/hapifhir/hapi-fhir/blob/f2f29a1a32450ab7a447026d03992cfd2620e6a9/hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/interceptor/MdmStorageInterceptor.java#L89
