### ISSUE TITLE
Swagger UI "Authorize" button is hidden

### ISSUE THREAD

**Issue by jbonzohln** [hapifhir/hapi-fhir#4555]
When using hapi-fhir-server-openapi to generate a swagger-ui page, the "Authorize" button is missing.

**To Reproduce**
Create a hapi-fhir project with hapi-fhir-server-openapi as a dependency.
Subclass the `OpenApiInterceptor` provided and modify the `OpenAPI` object returned from `generateOpenApi` to contain security schema and requirements
Run the project
Go to http://localhost:8080/swagger-ui
See that "Authorize" is missing

**Expected behavior**
The Authorize button should be present to allow for testing APIs with authentication

**Screenshots**
This is missing
![image](https://user-images.githubusercontent.com/97121974/219156206-48c7ebaf-0dec-4269-ae8e-668bf97b8691.png)

**Comment by jbonzohln** [comment]
Here is a demo showing when I'd expect the Authorize button to be visible at http://localhost:8080/fhir/swagger-ui/
[demo.gz](https://github.com/hapifhir/hapi-fhir/files/10748806/demo.gz)

**Comment by athenaecascketta** [comment]
Workaround for this is to set the custom css text on the `OpenApiInterceptor`
`openApiInterceptor.setCssText("body .swagger-ui .scheme-container { display: block; }");`
