### ISSUE TITLE
Parser does not report repeating choice data type to IParserErrorHandler

### ISSUE THREAD

**Issue by Boereck** [hapifhir/hapi-fhir#4574]
**Describe the bug**
We found when parsing a JSON FHIR resource which had multiple `value[x]` [choice](https://www.hl7.org/fhir/formats.html#choice) fields, that the parser does not call the `IParserErrorHandler#unexpectedRepeatingElement` method on the configured parser error handler:

https://github.com/hapifhir/hapi-fhir/blob/794e4510c6bf566dc2a6bb49818f198defb4355c/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/ParserState.java#L587

We would expect a check, if child is instance of `ca.uhn.fhir.context.RuntimeChildChoiceDefinition` ,and if so, call

```java
myParsedNonRepeatableName.addAll( ((RuntimeChildChoiceDefinition) child).getField().getName() )
```
instead of
```java
myParsedNonRepeatableNames.add(theChildName)
```
We would be willing to open a PR fixing the issue, if this is wanted.

For reference we reported this issue first in [this Mail](https://groups.google.com/g/hapi-fhir/c/--pnNrOqOaU) on the mailing list.

**To Reproduce**
Use a FHIR resource with multiple `choice[x]` fileds and parse it, e.g. with the `ca.uhn.fhir.parser.StrictErrorHandler` set.

Here is an example XML resource:

```xml
<Patient xmlns="http://hl7.org/fhir">
   <id value="ae2582e3-8376-3b7a-b4ae-4390b6a45ae8"></id>
   <name>
      <use value="official"></use>
      <family value="John"></family>
      <given value="Doe"></given>
   </name>
   <gender value="male"></gender>
   <birthDate value="1977-08-14"></birthDate>
   <deceasedBoolean value="true"></deceasedBoolean>
   <deceasedDateTime value="2022-02-07T13:28:17-05:00"></deceasedDateTime>
</Patient>
```
This resource has two `deceased[x]` fields set, even though the cardinality for it is `0..1`.
When loading the file with a parser with `StrictErrorHandler`, no exception is thrown. Example code:

```java
    FhirContext ctx = FhirContext.forR4();
    IParser parser = ctx.newXmlParser().setParserErrorHandler(new StrictErrorHandler());
    InputStream stream = Main.class.getResourceAsStream("/person-example.xml");
    parser.parseResource(stream);
```

**Expected behavior**
The `IParserErrorHandler#unexpectedRepeatingElement` shall be called in the case of a repeating choice field.
In the example we would expect the `StrictErrorHandler` to throw a `DataFormatException` with the message  
`HAPI-1823: Multiple repetitions of non-repeatable element 'deceased' found during parse`

**Screenshots**
--

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.4.0
 - OS: All of them

**Additional context**
The example given is available on GitHub as a simple project for debugging:
https://github.com/Boereck/choice-parser-example

**Comment by gijsbert802** [comment]
Just an FYI, I found this issue after a user reported an issue with missing data. We use the Lenient error handler, so I would expect the behaviour to be the same as before, but now the element that occurs multiple times is ignored (deceased in your example). That was not the case before this fix, although I'm not sure which value the parser picked.

Don't know if this is an unintended side effect or not, but it caused some confusion on our end.
