### ISSUE TITLE
Public test server JDBCConnectionException 

### ISSUE THREAD

**Issue by gosso22** [hapifhir/hapi-fhir#4678]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
When I try to access the resources in the public server as https://hapi.fhir.org/baseR4/Patient/, I am getting the exception below:
"HAPI-0389: Failed to call access method: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection"

**To Reproduce**
1. Go to '[Patient resource end-point](https://hapi.fhir.org/baseR4/Patient/)'
2. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version

**Additional context**

**Comment by azzimuth** [comment]
Any chance that this will be fixed soon?

**Comment by jamesagnew** [comment]
This was fixed
