### ISSUE TITLE
Batch2 reindex operation performance regression

### ISSUE THREAD

**Issue by sampoto** [hapifhir/hapi-fhir#4764]
**Describe the bug**
The batch2 implementation of reindexing since 6.0.0 (ReindexStep) is slow with hapi-fhir-jpaserver-base BaseHapiFhirResourceDao implementation due to Hibernate first level cache growing too big over the transactions and lot of time is spent in Hibernate dirty-checking. The chunk size is currently 500 due to selection of chunk size in ResourceIdListStep. This results in lower overall performance of reindex operations.

**To Reproduce**
1. Create significant amount (tested with 5000) of resources of same type (e.g. CarePlan)
2. Call the manual $reindex operation with the url parameter set for this resource type
3. Take note of the total time taken for the reindex operation
4. Modify ReindexStep temporarily to call EntityManager's clear() and flush() methods after each batch amount (e.g. every 20th) of items to control the cache size
5. Call the manual $reindex operation again after the modification is applied
-> The speed of the reindex operation considerably improves

This is a performance regression, as the reindexing speed is significantly better with the previous ResourceReindexingSvcImpl implementation. This can be compared by calling the $mark-all-resources-for-reindexing endpoint with the type parameter set to the resource type.

**Expected behavior**
The transactions should flush and clear entities from cache with a smaller batch size, resulting in better performance for reindex operations.
The batch size would usually be configured to hibernate.jdbc.batch_size.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.2.4
 - JPA Server, DSTU3
 - OS: Windows, Linux (Any)

**Additional context**
Long reindex operation times require larger preparation time windows for introducing SearchParameter changes.
The possible solution could involve moving the current loop of calling the reindex function from ReindexStep to the hapi-fhir-jpaserver-base dao. This way clearing and flushing the cache is a part of the underlying implementation.

**Comment by tyfoni-systematic** [comment]
We are currently running on hapi-fhir 6.2.1 and have experienced very bad performance of the BATCH2 reindex (< 1 resource/sec), and subsequent transactions timeouts. The BATCH2 message field (bt2_work-chunk.error_msg) is not large enough for capturing the underlying error, causing "ERROR: value too long for type character varying(500)". The worker threads then give up, but a progress log message is still logged every minute. Its a mess.
This has caused us to revert back to the deprecated $mark-all-resources-for-reindexing which has much better performance.

**Comment by jamesagnew** [comment]
We've made a ton of improvements to Batch2 and reindexing in general in HAPI FHIR 6.4.0 and 6.6.0. Recommend upgrading to 6.6.0 and confirming whether you still see this issue.

**Comment by jamesagnew** [comment]
Assuming this is resolved. Please re-open if not.
