### ISSUE TITLE
Data too long for column 'src_path' triggered by SearchParameter.expression

### ISSUE THREAD

**Issue by xluanlhc** [hapifhir/hapi-fhir#4912]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
When a SearchParameter resource has many base types, e.g, "researchStudy" (for extension https://hl7.org/fhir/extensions/StructureDefinition-workflow-researchStudy.html), the "expression" can be long, which can trigger the error "java.sql.BatchUpdateException: Data truncation: Data too long for column 'src_path' at row 1"

**To Reproduce**
1. Rename the attached file to .json (had to use .txt to attach here, it does not seem to take json)
2. Upload the attached SearchParameter resource to FHIR server
3. Run "reindex", you will see the error in the HAPI FHIR log

**Expected behavior**
Such search parameter resources should be processed successfully.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.4.4 (JPAServer starter version 6.4.0)
 - OS: [e.g. iOS]: Linux
 - Browser: N/A
[SearchParameter-researchStudy-hapi.json.txt](https://github.com/hapifhir/hapi-fhir/files/11502343/SearchParameter-researchStudy-hapi.json.txt)

**Comment by jamesagnew** [comment]
I don't understand why such a long expression is needed like in the example... Why not just use `extension('http://hl7.org/fhir/StructureDefinition/workflow-researchStudy').value`? The `base` paramater already spells out which resource types it applies to...
