### ISSUE TITLE
SearchParameter cache invalidation causes errors on Postgres DBs

### ISSUE THREAD

**Issue by rogtrifork** [hapifhir/hapi-fhir#5015]
### **Describe the bug**
The SearchParameter cache invalidation procedure added in [this PR](https://github.com/hapifhir/hapi-fhir/pull/4635) breaks on Postgres DBs. The error occurs due to https://www.postgresql.org/docs/current/largeobjects.html which requires large object operations to occur within a transaction, but the SearchParamRegistry refresh is triggered within the `afterCommit` method of the `TransactionSyncrhonization`: 

https://github.com/hapifhir/hapi-fhir/blob/ee3c59a3bc2b25c79c166e8eea0cf70cbebf1a71/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/JpaResourceDaoSearchParameter.java#L62

Since it's triggered after the commit, there is no transaction active during the search performed by https://github.com/hapifhir/hapi-fhir/blob/ee3c59a3bc2b25c79c166e8eea0cf70cbebf1a71/hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/registry/SearchParamRegistryImpl.java#L165 which causes it to fail with `org.hibernate.HibernateException: Unable to access lob stream` exception.

This in turn causes any new `SearchParameter` resources to be unavailable until the server is rebooted and the SearchParameters are correctly reindexed. 

---

### **To Reproduce**
1. Spin up a fresh Postgres DB
2. Install an IG that adds `SearchParameter` resources 
3. Ping `/fhir/metadata` and validate whether the search parameters were added successfully (alternatively, look for `Unable to access lob stream` in the log)

---

### **Expected behavior**
The IG should be installed and the new search parameters should be returned as part of `/fhir/metadata` and they should be useable in regular requests.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.6.1

**Comment by rogtrifork** [comment]
The easiest solution would be to require `ca.uhn.fhir.jpa.searchparam.registry.SearchParamRegistryImpl#rebuildActiveSearchParams` to be performed within a new transaction (`@Transactional(Propagation.REQUIRES_NEW)`) but I don't know how that'd affect performance / other DBs

**Comment by jkiddo** [comment]
@jamesagnew would you have an issue with fixing this on a 6.6.X+1?

**Comment by tadgh** [comment]
While a PR would potentially be welcome here, we recommend limiting usage LOBs in Postgres. See[ troubleshooting docs here](https://smilecdr.com/docs/database_administration/troubleshooting_postgresql.html#managing-fhir-resource-body-storage). Recommend setting the `StorageSettings.setInlineResourceTextBelowSize();` to a very large size, to have hibernate use the varchar field (RES_TEXT_VC) instead of the RES_TEXT lob field, which has a whole bunch of drawbacks. FWIW if you do decide to keep using LOBs in postgres, know that after 2 billionth lob created, postgres runs out of OIDs. 
`

**Comment by tadgh** [comment]
FWIW, LOB performance is also worse than just flat varchar performance, at least in our testing. We totally support: 
1. Setting this value to a large number (e.g. 10k) 
2. Modifying the RES_TEXT_VC column in HFJ_RES_VER to match the length you've set it to. 

This will result in lobs only rarely being created, which is ideal for postgres.

**Comment by delopst** [comment]
At some point in time, we migrated from oid (which you use in DB schema initialization by default) to bytea for Postgres.  This change massively improved search performance since lobs were fetched separately. 

Because of that we also do not have this problem currently.

Regards, Primož

**Comment by ttntrifork** [comment]
This seems to have been fixed by #5555 ?

**Comment by jamesagnew** [comment]
Closing as this appears fixed. Please feel free to comment if this continues to occur on a current release.
