### ISSUE TITLE
Missing support for the standard search parameter _language

### ISSUE THREAD

**Issue by jkiddo** [hapifhir/hapi-fhir#5025]
https://hl7.org/fhir/search.html#_language was introduced as part of R5. It would be great to have standard support for it in R5 instances.

**Comment by adamzkover** [comment]
Related? "Support for the _language search parameter has been dropped from the JPA server. This search parameter was specified in FHIR DSTU1 but was dropped in later versions. It is rarely used in practice and imposes an indexing cost, so it has now been removed. A custom search parameter may be used in order to achieve the same functionality if needed." - https://hapifhir.io/hapi-fhir/docs/introduction/changelog_2021.html

**Comment by adamzkover** [comment]
A custom search parameter works fine with code `language`, for example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SearchParameter xmlns="http://hl7.org/fhir">
    <url value="https://felleskatalogen.no/fhir/r5/SearchParameter/Composition_language"/>
    <name value="CompositionLanguage"/>
    <title value="Composition language"/>
    <status value="active"/>
    <description value="Search parameter for Composition.language"/>
    <code value="language"/>
    <base value="Composition"/>
    <type value="token"/>
    <expression value="Composition.language"/>
    <processingMode value="normal"/>
</SearchParameter>
```

However, if code is changed to `_language` then the search parameter is ignored and results are returned regardless of language (using hapi-fhir-jpaserver-starter).

**Comment by jkiddo** [comment]
That is most likely because only those defined by the standard are allowed to start with '_'

**Comment by adamzkover** [comment]
Could this be an optional feature that can be turned on with configuration? We have a use case now where we need language search, and it would be great to do it the standard way with "_", but for most systems, the original reasoning for the removal might still be valid ("rarely used in practice and imposes an indexing cost").

**Comment by jamesagnew** [comment]
Had a discussion about this bug at this week's Phoenix conenctathon. I agree our current behaviour is broken. Working on a fix.

**Comment by jkiddo** [comment]
https://github.com/hapifhir/hapi-fhir/issues/5303 is technically unrelated but tied to the same use case (being able to do diff between two resources - more specifically, two FHIR documents)
