### ISSUE TITLE
Binaries with contentType `application/json` are returned decoded when `Accept: application/fhir+json` is used

### ISSUE THREAD

**Issue by vilaug** [hapifhir/hapi-fhir#5078]
**Describe the bug**
It is no longer possible to read the raw FHIR Binary for which the contentType matches a FHIR contentType. 

**To Reproduce**

1. Create a Binary with contentType `application/json` in a hapi-fhir-jpaserver
2. Execute a read with a header `Accept: application/fhir+json`
3. Receive the decoded binary instead of the JSON FHIR resource.

**Expected behavior**

I would expect that if an `Accept` header that indicates you'd like FHIR is received, FHIR is returned.

I think the cause is in this PR: https://github.com/hapifhir/hapi-fhir/pull/4053 @tadgh 

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.6.0

**Additional context**

**Comment by hassan-insight** [comment]
@vilaug Were you able to find a fix for this?
