### ISSUE TITLE
HAPI-1094: Resource DocumentReference/urn:oid:1.2.3not found, specified in path: Provenance.entity.what

### ISSUE THREAD

**Issue by MatthewThomasTiani** [hapifhir/hapi-fhir#5148]
**Describe the bug**
We have an implementation that publishes FHIR resources that have been extracted from a CDA document. The implementation is following the IHE Profiles MXDE and QEDm. Due to this, we create a Provenance resource that points back to the CDA document which resides in an XDS Registry/Repository using our FHIR IHE MHD implementation. 

We have a variety of external resources such as Patients which are stored in our EMPI which is accessed by the PIXm IHE Profile. We do not see any errors related to any references to these from resource types such as Observations, Medications, or AllergyIntollerance so I can assume the configuration "allow_external_references" is working as expected. So the error in question seems to be specific to the Provenance resource and/or the "entity.what.reference" handling.

This is how we reference the XDS Document,

`"entity": [
                    {
                        "role": "source",
                        "what": {
                            "reference": "https://somehost:8443/mhd/r4/responder/DocumentReference/urn:oid:1.2.40.0.13.1.1.584109161.20230630175432428.38899",
                            "type": "DocumentReference",
                            "identifier": {
                                "use": "official",
                                "system": "urn:oid:2.16.840.1.113883.3.704.2.103.2.1.1.1.1.8",
                                "value": "urn:oid:1.2.40.0.13.1.1.584109161.20230630175432428.38899"
                            },
                            "display": "CDA Document in XDS Repository"
                        }
                    }
                ]`

Since our customer updated their FHIR server to v6.6.0 we are now seeing this error:
`{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-1094: Resource DocumentReference/urn:oid:1.2.40.0.13.1.1.584109161.20230630175432428.38899 not found, specified in path: Provenance.entity.what"
        }
    ]
}`

Here is the stack trace from the server:
`2023-07-31 11:26:07.403 [qtp709671086-22] DEBUG c.u.f.j.d.tx.HapiTransactionService [HapiTransactionService.java:237] Unexpected transaction exception. Will not be retried.
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HAPI-1094: Resource DocumentReference/urn:oid:1.2.40.0.13.1.1.584109161.20230630175432428.38899 not found, specified in path: Provenance.entity.what
        at ca.uhn.fhir.jpa.dao.index.DaoResourceLinkResolver.findTargetResource(DaoResourceLinkResolver.java:127)
        at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.resolveTargetAndCreateResourceLinkOrReturnNull(SearchParamExtractorService.java:755)
        at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractResourceLinks(SearchParamExtractorService.java:610)
        at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractResourceLinks(SearchParamExtractorService.java:482)
        at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractFromResource(SearchParamExtractorService.java:144)
        at ca.uhn.fhir.jpa.dao.index.SearchParamWithInlineReferencesExtractor.populateFromResource(SearchParamWithInlineReferencesExtractor.java:94)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.updateEntity(BaseHapiFhirDao.java:1044)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.updateInternal(BaseHapiFhirDao.java:1382)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao$$FastClassBySpringCGLIB$$741dcd55.invoke(<generated>)`

Locally, I have been using a FHIr server v5.7.2, I have not had any of the above issues. Only when I update to a later version (v6.6.0 to match the customer) I see issues.

- Is there a configuration I am missing?
- I checked the Provenance Resource specification, but I see nothing new on how the "entity.what.reference" should be populated... :/

**To Reproduce in v6.6.0**
1. Download the https://github.com/hapifhir/hapi-fhir-jpaserver-starter/tree/v6.6.0 
1. I have attached the application.yaml (as a text file) configuration files - the only change I made was to allow_external_references
2. run using mvn jetty:run
3. I have attached an example payload (test_bundle.txt), I have removed most resources from it so that it's very simple

**Expected behavior**
I expect the FHIR bundle to be published to the FHIR server 

**Environment (please complete the following information):**
 - HAPI FHIR 6.6.0 REST Server (FHIR Server; FHIR 4.0.1/R4)
 - OS: Running on mac 13.4.1 , but the same issue on Linux

Appreciated any help!

Thanks,
Matthew

[application.txt](https://github.com/hapifhir/hapi-fhir/files/12214064/application.txt)
[test_bundle.txt](https://github.com/hapifhir/hapi-fhir/files/12214083/test_bundle.txt)

**Comment by vilaug** [comment]
I am also having the same issue but with another resourceType. It is also caused by an external reference in one of the fields. Did you perhaps find a solution to the issue?

**Comment by MatthewThomasTiani** [comment]
Hi, I did not, we found that downgrading the version to v6.0 removed the issue. But no fix/workaround/config option/resolution has been found for later versions from my side.

**Comment by vilaug** [comment]
I looked into the source code and the issue occurs when the field that contains an external reference also contains an identifier. Not sure about the what the fix should be yet though.

**Comment by jamesagnew** [comment]
The reference `https://somehost:8443/mhd/r4/responder/DocumentReference/urn:oid:1.2.40.0.13.1.1.584109161.20230630175432428.38899` is not a valid FHIR ID. I'm not entirely sure what is causing HAPI to give that specific error message, but FHIR resource IDs may not have a `:` character in them (per http://hl7.org/fhir/datatypes.html#id ). I'd assume this would work if you removed the `urn:oid:` prefix in your resource ID.

**Comment by vilaug** [comment]
Can also be replicated using the below bundle:
```
{
    "resourceType": "Bundle",
    "id": "de386b6f-0cd7-47bd-9412-427663291d45",
    "type": "transaction",
    "entry": [
        {
            "fullUrl": "urn:uuid:6cfc68f1-580f-4b07-bafc-11cc936b2b73",
            "resource": {
                "resourceType": "Observation",
                "performer": [
                    {
                        "reference": "https://fhir.nl/fhir/stu3/48/Practitioner/e8qJeIfJ04pAfYY6FQn8iHg3",
                        "identifier": [
                            {
                                "system": "http://fhir.nl/fhir/NamingSystem/agb-z",
                                "value": "2009877"
                            }
                        ],
                        "display": "Mw. F.H.M. v.d. Aardweg"
                    }
                ]
            },
            "request": {
                "method": "POST",
                "url": "Observation"
            }
        }
    ]
}
```

**Comment by jamesagnew** [comment]
I also don't know specially what changed, but validation does get tightened over time and various other functionality has been added around reference indexing that might be causing this.

Bottom line I don't actually think we should be erroring here since it's obvious what the intent is, but I'd say it's pretty low priority since this is invalid per the spec.

**Comment by jamesagnew** [comment]
I'll also add that it's only even speculation on my part that it's the oid: bit causing an issue. Would be interested in knowing whether removing that actually solves the issue.

**Comment by vilaug** [comment]
Hi @jamesagnew, 

I believe that the issue with the bundle I posted above causes the same error. I also experienced it on 6.6.2. You can replicate it on https://hapi.fhir.org.

Is there a reason you think the error is different? The stacktrace I got was identical.

**Comment by jamesagnew** [comment]
Digging into this today - this appears to be a regression introduced with https://github.com/hapifhir/hapi-fhir/pull/4731
