### ISSUE TITLE
Search for MedicationRequests with medication contained does not return correct results

### ISSUE THREAD

**Issue by StevenXLi** [hapifhir/hapi-fhir#5307]
**Describe the bug**
When a search is made to find a MedicationRequest with a certain Medication, the results will not return the correct MedicationRequest if the Medication is included as a contained resource. This is with IndexOnContainedResources set to true and using `_contained=true`.

**To Reproduce**
1. Enabled IndexOnContainedResources
2. Submit the following MedicationRequest resource
```
{
	"resourceType": "MedicationRequest",
	"contained": [
		{
			"resourceType": "Medication",
			"id": "med0312",
			"code": {
				"coding": [
					{
						"system": "http://snomed.info/sct",
						"code": "324689003",
						"display": "Nystatin 100,000 units/ml oral suspension (product)"
					}
				]
			}
		}
	],
	"identifier": [
		{
			"use": "official",
			"system": "http://www.bmc.nl/portal/prescriptions",
			"value": "12345689"
		}
	],
	"status": "completed",
	"intent": "order",
	"medicationReference": {
		"reference": "#med0312",
		"display": "Nystatin 100,000 u/ml oral suspension"
	}
}
```
3. Search with the following query: `MedicationRequest?medication.code=http://snomed.info/sct|324689003&_contained=true` 
4. See no results

**Expected behavior**
Should return the MedicationRequest

**Environment (please complete the following information):**
 - HAPI FHIR Version: 6.9.5
 - OS: MacOS
 - Browser: chrome

**Comment by dmuylwyk** [comment]
Root cause:

Some search parameters include parenthetical expressions (e.g. `(MedicationRequest.medication as Reference)`). The leading `(` was causing searches using parenthetical expressions to fail where the reference target was a contained resource. The culprit is in `ReferenceChainExtractor#extractPaths(...)` in `QueryStack.java`, which filters on startsWith without expecting any parentheses.

**Comment by michaelabuckley** [comment]
Nice diagnosis, @dmuylwyk
