### ISSUE TITLE
"Read" conflicts with "Search" in basic plain server 

### ISSUE THREAD

**Issue by pweissbrod-eh** [hapifhir/hapi-fhir#5319]
I must be doing something silly. I've distilled this use case down into the simplest possible example yet it still doesn't work.
The requirement is to support both "get by id" and "search". Yet in practice it seems I cannot support both for some reason?

Here is my servlet:

```
@WebServlet(urlPatterns = {"/fhir/*"}, displayName = "FHIR Server")
public class FhirServer extends RestfulServer {

	@Override
	protected void initialize() {
		FhirContext ctx = FhirContext.forR4();
		setFhirContext(ctx);
		List<IResourceProvider> resourceProviders = new ArrayList<>();
		resourceProviders.add(new PatientResourceProvider());
		setResourceProviders(resourceProviders);
    }
}
```

Here is my one and only resource provider: 

```
public class PatientResourceProvider implements IResourceProvider {

   /**
    * Signifies the resource supplied
    */
   @Override
   public Class<Patient> getResourceType() {
      return Patient.class;
   }

   /**
    * Implements get by ID e.g.: /patient/[id]
    */
   @Read(version = false)
   public Patient getResourceById(@IdParam IdType theId) {
      return getDummyPatient("test");
   }

   @Search()
   public List<Patient> getAllPatients(){
      return Collections.singletonList(getDummyPatient("test"));
   }

   /**
    * Implements /patient[?family=[theFamilyName]]
    */
   @Search
   public List<Patient> getPatient( @RequiredParam(name = Patient.SP_FAMILY) StringParam theFamilyName) {
      return Collections.singletonList(getDummyPatient(theFamilyName.getValue()));
   }

   private Patient getDummyPatient(String theFamilyName){
      Patient patient = new Patient();
      patient.addIdentifier();
      patient.getIdentifier().get(0).setUse(Identifier.IdentifierUse.OFFICIAL);
      patient.getIdentifier().get(0).setSystem(new UriDt("urn:hapitest:mrns").getValue());
      patient.getIdentifier().get(0).setValue("00001");
      patient.addName();
      patient.getName().get(0).setFamily(theFamilyName);
      patient.getName().get(0).addGiven("PatientOne");
      patient.setGender(Enumerations.AdministrativeGender.MALE);
      return patient;
   }
}
```

**Expected behavior**
- I can GET http://localhost:8080/fhir/Patient/123
- I can GET http://localhost:8080/fhir/Patient

**ACTUAL behavior**
- GET http://localhost:8080/fhir/Patient/123 works
- GET http://localhost:8080/fhir/Patient returns:

```
500 server error
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-0435: Server method returned resource of type[Patient] with no ID specified (IResource#setId(IdDt) must be called)"
        }
    ]
}
```

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.8.2
 - OS: iOS monterrey openjdk v20
 - POSTMAN calls

**Additional context**
I attempted splitting `Search` and `Read` out into separate resource providers but the issue does not change.

**Comment by jamesagnew** [comment]
You need to assign an ID to the Patient resource you are returning from search methods. It works on the read method because it's able to infer the ID from the request but it can't do that in the case of a search.

Ps- please use our google group to ask questions. See here for more information: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Comment by pweissbrod-eh** [comment]
That was a fast and accurate response. Thank you so much for your time and I will use the google group going forward.
