### ISSUE TITLE
Storage-CR module cache invalidation bug

### ISSUE THREAD

**Issue by Capt-Mac** [hapifhir/hapi-fhir#5356]
**Describe the bug**
When running storage-cr operations like evaluate-measure, any leveraged resources to evaluate the query are stored in a global resource cache. The issue is when an update to these resources (Library or ValueSet) are posted to a server running this, or are removed from the server, the cached resources are not removed or updated. 

**To Reproduce**
1. Run an r4 instance of hapi-fhir on a server in debug mode
2. Post a measure bundle like [cms130](https://raw.githubusercontent.com/hapifhir/hapi-fhir/master/hapi-fhir-storage-cr/src/test/resources/ColorectalCancerScreeningsFHIR-bundle.json)
3. Run $evaluate-measure against the measure in the server (this caches library and valuesets)
4. place breakpoint on r4 MEasureService's evaluationOptions.evaluationsettings.librarycache 
5. then run same operation again
6. This will show the library in the cache
7. Delete the library from the server via delete endpoint/Library/ColorecectalCancerScreeningsFHIR
8. run same evaluate-measure operation again, it still runs, the cache still contains the library

**Expected behavior**
update/delete to valueset or library would remove it from the global cache.

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.9.9-SNAPSHOT
 - OS: Mac M1 Monterey

**Comment by JPercival** [comment]
Resolved by #5360
