### ISSUE TITLE
hapi-fhir Server SpringBoot version 3.0.x support

### ISSUE THREAD

**Issue by rajankapadia** [hapifhir/hapi-fhir#5379]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the issue**
we are looking for hapi-fhir Server SpringBoot version 3.0.x support. Any tentative plan for release?

**Comment by jamesagnew** [comment]
Please this ticket: https://github.com/hapifhir/hapi-fhir/issues/2082

Ps - please don't use GitHub issues to ask questions, see this URL for details on where/how to ask questions: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help
