### ISSUE TITLE
Clinical Reasoning FHIRHelpers CQL bug

### ISSUE THREAD

**Issue by Capt-Mac** [hapifhir/hapi-fhir#5404]
**Describe the bug**
When using clinical reasoning operation $evaluate-measure on measure bundle that is leveraging FHIRHelpers library, users are presented with a cql exception error

**To Reproduce**
1. Post MeasureBundle to HapiFhir server like CDR or JpaStarter
2. Run evaluate measure
3. See error

`{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-0389: Failed to call access method: org.opencds.cqf.cql.engine.exception.CqlException: Could not resolve call to operator 'ToString(java.lang.Class)' in library 'FHIRHelpers'."
        }
    ]
}`

**Expected behavior**
Evaluate measure translates fhirHelpers and returns MeasureReport

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.9.10-SNAPSHOT
 - Clinical Reasoning 3.0.0-PRE8

**Additional context**

**Comment by JPercival** [comment]
Resolved by #5406
