### ISSUE TITLE
swap-to-non-javax-clinical-reasoning

### ISSUE THREAD

**Issue by Capt-Mac** [hapifhir/hapi-fhir#5436]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the issue**
- Moving clinical reasoning to non-javax dependency for alignment with incoming hapi-fhir changes
- New measure evaluation parameter for CQL parameters.
- New feature for offloading configuration for repository retrievesettings and terminologysettings. 
- CQL bug fixes and updates

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.11.1-SNAPSHOT

**Additional context**
update measure service with new cql parameters https://github.com/cqframework/clinical-reasoning/issues/334

**Comment by JPercival** [comment]
Resolved by #5463
