### ISSUE TITLE
500 error on any request to HAPI FHIR Test/Demo Server R4 Endpoint

### ISSUE THREAD

**Issue by roger-moulton** [hapifhir/hapi-fhir#5479]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
Getting:
Error: HTTP 500 Server Error:

OperationOutcome:
Error: HAPI-2223: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled.

**To Reproduce**
Go to http://hapi.fhir.org/baseR4
Make any request eg: https://hapi.fhir.org/baseR4/Patient
See 500 error

**Expected behavior**
200 + Response

**Environment (please complete the following information):**
 - HAPI FHIR 6.9.5-SNAPSHOT/7e3c42549d/2023-09-09 REST Server (FHIR Server; FHIR 4.0.1/R4)
 - OS: OS: Mac Os
 - Browser chrome

**Additional context**
Seems similar to https://github.com/hapifhir/hapi-fhir/issues/2247 where a reboot of server resolved the issue.

**Comment by mpeng** [comment]
No one has an answer about this error ???

**Comment by roger-moulton** [comment]
Closing this issue as the server is back up.
