### ISSUE TITLE
Getting 500 error

### ISSUE THREAD

**Issue by Jagathish94** [hapifhir/hapi-fhir#5485]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
Getting:
Error: HTTP 500 Server Error:

OperationOutcome:
Error: HAPI-2223: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already canceled.

To Reproduce
Go to http://hapi.fhir.org/baseR4
Make any request eg: https://hapi.fhir.org/baseR4/Patient
See 500 error

**Expected behavior**
200  Response
**Environment (please complete the following information):**
 - HAPI FHIR Version
 - OS: macOS
 - chrome, safari

**Comment by jamesagnew** [comment]
Server is back up

**Comment by Jagathish94** [comment]
> Had the same issue, server came back online... it took 10 hours. Alternative approach: install your copy of a server on a local, try to get all the mock data on it as well.

How to install a copy server? May I know the procedure to get locally?

**Comment by olejardamir** [comment]
> How to install a copy server? May I know the procedure to get locally?
Depends on what issues you got.
