### ISSUE TITLE
$care-gaps operation example doesn't work

### ISSUE THREAD

**Issue by XcrigX** [hapifhir/hapi-fhir#5532]
**Environment (please complete the following information):**
 - 6.10.0 (latest JPA Server) 

**Describe the bug**
The steps documented in sec: 11.2.1.4.1 don't work:  
https://hapifhir.io/hapi-fhir/docs/clinical_reasoning/caregaps.html

Problem 1) The CaregapsPatientData.json in step 3, available here appears to be incorrect: https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-storage-cr/src/test/resources/CaregapsPatientData.json

The MeasureReport references:
"reference": "Procedure/end-to-end-EXM130-1"

But the actual Procedure has id "end-to-end-EXM130-2". 
When you run $submit-data on this bundle it errors out because of the missing reference. 
I manually corrected that.

Problem 2) Step 4 fails with error: 
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-2001: Resource Organization/default is not known"
        }
    ]
}
```

I stepped into the code to try to debug this, the exception is thrown from: 
```
R4CareGapsService.validateConfiguration().
```
This line: 
https://github.com/cqframework/clinical-reasoning/blob/3af4cbfa9c4966458a13144299951ad52b92391d/cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java#L196
```
Resource configuredReporter = this.addConfiguredResource(Organization.class, this.myCareGapsProperties.getCareGapsReporter(), "care_gaps_reporter");
```

The CareGapsProperties instance has a defaulted value for CareGapsProperties.myCareGapsReporter of "default". 

I don't see in the JPA Config (application.yaml) any example values to configure these properties. 

Am I missing something? 

@JPercival - FYI

**Comment by XcrigX** [comment]
For my problem 2, looking at the unit tests it looks like some properties are required: 		"hapi.fhir.cr.caregaps_section_author=Organization/alphora-author"
"hapi.fhir.cr.caregaps_reporter=Organization/alphora"

So could just be the documentation needs to be updated to note this.

**Comment by Capt-Mac** [comment]
I'll update the documentation as you suggested

**Comment by Capt-Mac** [comment]
I would also use this version of hapi-fhir-jpastarter, this was the official release that contained CR updates: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/releases/tag/image%2Fv6.10.1
