### ISSUE TITLE
Incorrect version of auto versioned reference for conditional update with urn id placeholder

### ISSUE THREAD

**Issue by volodymyr-korzh** [hapifhir/hapi-fhir#5619]
If versioned_references.auto_at_paths is set for an element and transaction is filed with a placeholder reference in that element, and the target Resource is included in the Bundle but is not actually updated, then the reference is stored with a version number that does not exist.

**To Reproduce**

1. Enable Auto Version Reference At Paths for `MessageHeader.focus`.
`StorageSettings#setAutoVersionReferenceAtPaths("MessageHeader.focus")`
2. Post transaction bundle that contains: 
- conditional update for a Patient resource with `urn` id placeholder
- create MessageHeader with Patient `urn` id placeholder reference in `MessageHeader.focus`.
<details>
  <summary>Transaction Bundle Example</summary>

POST: http://localhost:8000/
  ```json
{
   "resourceType":"Bundle",
   "type":"transaction",
   "entry":[
      {
         "fullUrl":"urn:uuid:4eb8002c-226c-4ffe-b6e6-38cd700654db",
         "resource":{
            "resourceType":"Patient",
            "identifier":[
               {
                  "system":"http://example.com",
                  "value":"test"
               }
            ],
            "name":[
               {
                  "family":"family"
               }
            ]
         },
         "request":{
            "method":"PUT",
            "url":"Patient?identifier=http://example.com|test"
         }
      },
      {
         "resource":{
            "resourceType":"MessageHeader",
            "focus":[
               {
                  "reference":"urn:uuid:4eb8002c-226c-4ffe-b6e6-38cd700654db"
               }
            ]
         },
         "request":{
            "method":"POST",
            "url":"MessageHeader"
         }
      }
   ]
}
 ```
</details>
3. Check the response - Patient and MessageHeader should be created with version 1:

```
"status": "201 Created",
"location": "Patient/2203/_history/1",
```

```
"status": "201 Created",
"location": "MessageHeader/2202/_history/1",
```

4. Execute GET request for created MessageHeader, and check that `MessageHeader.focus.reference` is correct. 

<details>
  <summary>Get  MessageHeader response Example</summary>

GET http://localhost:8000/MessageHeader/2202
  ```json
{
	"resourceType": "MessageHeader",
	"id": "2202",
	"meta": {
		"extension": [
			{
				"url": "http://hapifhir.io/fhir/StructureDefinition/auto-version-references-at-path",
				"valueString": "focus"
			}
		],
		"versionId": "1",
		"lastUpdated": "2024-01-22T11:30:13.662-07:00",
		"source": "#IiucF2fgKVNQbKsu"
	},
	"focus": [
		{
			"reference": "Patient/2203/_history/1"
		}
	]
}
 ```
</details>

5. Post same transaction bundle from step 2.
6. Check the response - Patient not be updated and new MessageHeader should be created with version 1:

```
"status": "200 OK",
"location": "Patient/2203/_history/1",
```

```
"status": "201 Created",
"location": "MessageHeader/2204/_history/1",
```
7. Execute GET request for created MessageHeader, and check that `MessageHeader.focus.reference` is correct. 

**Expected behaviour**
Patient version in `MessageHeader.focus.reference` is correct - version 1.
```
	"focus": [
		{
			"reference": "Patient/2203/_history/1"
		}
```
**Actual behaviour**
Patient version in `MessageHeader.focus.reference` is incorrect - version 2.
```
	"focus": [
		{
			"reference": "Patient/2203/_history/2"
		}
```

**Comment by elavy-harris** [comment]
This issue also applies when using the new functionality in #5591.

**Comment by volodymyr-korzh** [comment]
@elavy-harris 
Fix covers both cases (with added `auto-version-references-at-path` extension  and with `setAutoVersionReferenceAtPaths` configuration)
