### ISSUE TITLE
Deadlock on Caffeine cash when creating a resource with conditional create

### ISSUE THREAD

**Issue by epeartree** [hapifhir/hapi-fhir#5621]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version

**Additional context**

**Comment by tadgh** [comment]
Closed by https://github.com/hapifhir/hapi-fhir/pull/5622
