### ISSUE TITLE
Annotation @EventListener on base method stop() of class HapiSchedulerServiceImpl  causes exception on context tear down

### ISSUE THREAD

**Issue by epeartree** [hapifhir/hapi-fhir#5626]
Base method stop() of class HapiSchedulerServiceImpl causes a BeanCreationNotAllowedException to be thrown in certain application context configuration due to being annotated with @EventListener(ContextClosedEvent.class)

One such configuration is having class HapiSchedulerServiceImpl instantiated as a Bean in `ParentContext`.  then a WebContext is created with ParentContext as parent.  Upon doing a ParentContext.close(), a first ContextClosedEvent is published by the ParentContext to all Bean in the context AND a second ContextClosedEvent is published by WebContext to all Beans in the context and its parent context.  As a result, method stop() of Bean HapiSchedulerServiceImpl is called twice with an exception thrown on the second invocation.

The eventListener needs to be replaced by @PreDestroy

**Comment by tadgh** [comment]
Closed by https://github.com/hapifhir/hapi-fhir/pull/5628
