### ISSUE TITLE
Confusing :missing search modifier

### ISSUE THREAD

**Issue by huthomas** [hapifhir/hapi-fhir#5685]
**Describe the bug**
If I understand the :missing modifier specification https://www.hl7.org/fhir/search.html#missing right, setting missing true should return all resources without that parameter.

If i create ChargeItem without a subject reference on the HAPI FHIR Server ( using docker image), and then search using HAPI FHIR client with `org.hl7.fhir.r4.model.ChargeItem.SUBJECT.isMissing(true)` these resources are not returned. If i search with `org.hl7.fhir.r4.model.ChargeItem.SUBJECT.isMissing(false)` these resources are returned, and no subject reference is set.

The Java doc of the HAPI client also states that setting missing false should return resources with this value missing.
<pre>
Sets the :missing qualifier for this parameter. Set this to true to indicate that the server should return resources with this value

populated

. Set this to false to indicate that the server should return resources with this value missing.
</pre>
But the FHIR specification states that the value should be true.

**To Reproduce**
1. Start HAPI FHIR Server docker container hapiproject/hapi:latest 
2. Use HAPI FHIR client to create ChargeItem with missing subject reference
3. Use HAPI FHIR client to query ChargeItem with date and `SUBJECT.isMissing(true)`
4. Use HAPI FHIR client to query ChargeItem with date and `SUBJECT.isMissing(false)`

**Expected behavior**
I expected the ChargeItem query to include the ChargeItem with `SUBJECT.isMissing(true)`. And to not include the ChargeItem with `SUBJECT.isMissing(false)`.

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version 6.10.4
 - OS: Linux

**Comment by jamesagnew** [comment]
The server needs to be configured to index for the `:missing` parameter. See here:

https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/e1d902c90388cacc837365be58c37827a26be1ce/src/main/resources/application.yaml#L120
