### ISSUE TITLE
SubscriptionWebsocketHandler to deliver ResourceDeliveryMessage if full-resource content

### ISSUE THREAD

**Issue by ArtyomyuS** [hapifhir/hapi-fhir#5687]
Hello there dear community.
I was looking into the Websocket handling of the subscriptions and try to figure out if one aspect of the implementation was done properly.

Accordingly to R5 standard https://hl7.org/fhir/subscription.html on managing a subscription: By adjusting Subscription.content, subscribers can request event notifications that include full resource content; or just the ID of the triggering resource; or an empty notification body.

Does it make sense to open a pull request that will update current code for SubscriptionWebsocketHandler so that:
if msg.getSubscription() has content = id-only to deliver(msg.getPayloadId()) and in case of content = full-reference to invoke `deliver(msg.getPayload())

Please advice if this is appropriate.

NOTE: Created initially this [here](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/638), will close it if the issues was created inappropriately

Thank you

**Comment by jamesagnew** [comment]
If you are interested in developing this as a PR, we'd definitely be happy to review and merge if appropriate. Please do feel free to discuss your approach if you want, and ensure that there are sufficient tests to fully exercize the feature as well as any edge cases and error conditions.

Also - yup, this is the appropriate place for this ticket and not the JPA starter project.

**Comment by ArtyomyuS** [comment]
Thank you for the response. Going to provide a pull-request soon.

**Comment by ArtyomyuS** [comment]
Hello there dear community, provided the following [pull-request](https://github.com/hapifhir/hapi-fhir/pull/5692/files). Please let me know if it's the right approach. Thank you for the support.
