### ISSUE TITLE
hapi-fhir-validation library accepts string for elements that fhir mentions as an array

### ISSUE THREAD

**Issue by indusankar89** [hapifhir/hapi-fhir#5727]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
In FHIR resource patient, identifier, generalPractitioner  etc are mentioned as array (0..*). 
I am using hapi-fhir-validation library for validation of fhir resource. But when i give "identifier": "12345", the validator library accepts this data and doesnt throw error. On trying the same payload in https://validator.fhir.org/ online tool, it throws error. 

**To Reproduce**
1. validate below payload with java hapi-fhir-validation library
   

>  {
>     "resourceType": "Patient",
>      "identifier":"12345"
>  }

**Expected behavior**
Fhir validator should not give a success message and should give error that identifier should be of array type

**Environment (please complete the following information):**
 -library used: 
implementation group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-validation', version: '6.10.2'

**Comment by jamesagnew** [comment]
Are you passing this payload as a raw string containing the error into the validator, or are you first parsing it into a FHIR resource class and then validating that? If it's the latter, the parser is probably logging a warning about your issue but it's then lost by the time it gets to the validator.

If it's the former, can you please provide a minimal code snippet that demonstrates the issue?

**Comment by jamesagnew** [comment]
Closing due to lack of response. Please re-open with a code snippet showing the issue if this is still a problem.
