### ISSUE TITLE
HAPO FHIR + Spring Boot 3.2x Native Image Compilation

### ISSUE THREAD

**Issue by goafabric** [hapifhir/hapi-fhir#5798]
When trying to compile latest HAPI FHIR 7.0.2 to a Native Image,
the AOT Processor will bail out immediately:

--- cut ---
Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
	ca.uhn.fhir.rest.server.method.BaseMethodBinding
	at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:100)
--- cut ---

Though I have 2 years experience with Native Image, I've never seen an exception like this before.
Then again it's pretty explicit.

The -parameters could be configured with the maven or gradle compiler plugin.
For maven compiler plugin it might me something in the veins of:

---
<compilerArgs>
    <arg>-parameters</arg>
</compilerArgs>
---

Any chance to compile with this with the new version ?

**Comment by jamesagnew** [comment]
I don't actually use native image, so I have no real way of testing this... Would you be able to try adding the `-parameters` argument to the compiler args section of the pom [here](https://github.com/hapifhir/hapi-fhir/blob/master/pom.xml#L2378) and then testing against a locally built version of HAPI with that change?

If this works, please feel free to file a PR.

**Comment by goafabric** [comment]
@jamesagnew 
Thanks for your reply.
I could eventually investigate that and Create a PR
