### ISSUE TITLE
HAPI-1821 being thrown for valueBase64Binary in R4 Json FHIR bundle

### ISSUE THREAD

**Issue by FranciscoPDNeto** [hapifhir/hapi-fhir#5844]
**Describe the bug**
We are receiving an Organization bundle from a R4 FHIR server which contains valueBase64Binary in extension list. This value contains a png base64 image string, but for some reason HAPI FHIR is throwing the error `HAPI-1821: [element=\"valueBase64Binary\"] Invalid attribute value` when I try to execute JsonParser.parseResource to Bundle. I decode the png and got valid image, so I think the problem is not with the value itself. When I remove the "data:image/png;base64," piece it works fine, but ideally it should accept it too, no?

**To Reproduce**
1. Get FHIR bundle with valueBase64Binary in extension list (`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII`)
2. Tries to execute JsonParser.parseResource in R4 Context

**Expected behavior**
It should parse successfully the bundle

**Environment (please complete the following information):**
 - HAPI FHIR Version: 7.0.2

**Comment by jamesagnew** [comment]
Unfortunately this isn't enough information to be able to reproduce this. Can you please provide a code snippet demonstrating the issue?

**Comment by FranciscoPDNeto** [comment]
Hello James, sure!

```
    String bundleStr = """
{
  "resourceType": "Bundle",
  "type": "searchset",
  "timestamp": "2023-05-04T15:33:53.781+00:00",
  "total": 1,
  "entry": [
    {
      "id": "a45c3fed-052c-5085-981e-a16baf147985",
      "extension": [
        {
          "url": "http://fhir.caremesh.app/r4/caremesh-organization-photo",
          "valueBase64Binary": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII"
        }
      ],
      "resource": {
        "resourceType": "Organization",
        "id": "a45c3fed-052c-5085-981e-a16baf147985"
      }
    }
  ]
}
    """;
    var context = FhirContext.forR4();
    var jsonParser = context.newJsonParser();
    jsonParser.parseResource(Bundle.class, bundleStr);
```

**Comment by jamesagnew** [comment]
You need to remove the `data:image/png;base64,` part. That isn't a valid base64 string with it, which is why HAPI is failing to parse it. See the definition of that datatype: http://hl7.org/fhir/datatypes.html#base64Binary
