### ISSUE TITLE
code for returning 'summary' search responses is automatically stripping extensions from the response

### ISSUE THREAD

**Issue by henryt678** [hapifhir/hapi-fhir#5871]
**Describe the bug**
The code for returning 'summary' search responses is automatically stripping extensions from the response.  In our case, there are certain extensions that need to be included in the summary search response.

Here is the code in BaseParser of HAPI FHIR,

if (retVal && isSummaryMode() && (getDef() == null || !getDef().isSummary())) {
    String resourceName = myEncodeContext.getLeafResourceName();
    // Technically the spec says we shouldn't include extensions in CapabilityStatement
    // but we will do so because there are people who depend on this behaviour, at least
    // as of 2019-07. See
    // https://github.com/smart-on-fhir/Swift-FHIR/issues/26
    // for example.
    if (("Conformance".equals(resourceName) || "CapabilityStatement".equals(resourceName))
          && ("extension".equals(myDef.getElementName())
                || "extension".equals(myEncodeContext.getLeafElementName()))) {
       // skip
    } else {
       retVal = false;
    }
}

In the summary mode, the extensions are dropped.

**To Reproduce**
...for a claim resource, when we add an extension, the HAPI plain server returns the response without the extension.

**Expected behavior**
The [wording from the specification](https://build.fhir.org/search.html#_summary) is "This subset SHOULD consist solely of all supported elements that are marked as "summary" in the base definition of the resource(s)".  Note the use of SHOULD rather than SHALL.  While it's reasonable for HAPI's default behavior to be stripping all extensions, there should be a configuration option to allow selected extensions to be included.  The only alternative to this is moving to custom operations, which is much less interoperable.

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.6.8
 - OS: Windows 

**Additional context**

**Comment by henryt678** [comment]
Glad to hear that there will be a fix! Any timelines on when it will be released?

**Comment by jamesagnew** [comment]
@henryt678 This should appear in snapshot builds in the next day or so, and will be released in our 7.4.0 (August 2024) release.
