### ISSUE TITLE
Search responses where references are version-specific are stripping out the version-specific references

### ISSUE THREAD

**Issue by henryt678** [hapifhir/hapi-fhir#5872]
**Describe the bug**
Search responses where references are version-specific are stripping out the version-specific references.  

![image](https://github.com/hapifhir/hapi-fhir/assets/167991625/1f0f259d-626e-427f-948e-72bef951a49e)

**To Reproduce**

**Expected behavior**
In FHIR, any Reference is permitted to be version-specific and it is possible within a search response for different references to point to different versions of the same resource.  The "_history/[version]" portion of the reference URL needs to be retained.  Per the spec [here](https://build.fhir.org/search.html#_revinclude): "Servers SHOULD resolve _include and _revinclude requests for version-specific references by resolving the version named in the reference."  There is also additional guidance [here](https://build.fhir.org/search.html#versions).

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.6.8
 - OS: Windows

**Comment by jamesagnew** [comment]
If you want HAPI FHIR to not filter versions from references, you can configure the ParserOptions (available from the FhirContext) to not strip versions from references using [this setting](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/ParserOptions.java#L111).

Closing this ticket, please re-open with a code snippet illustrating the problem if this is not working fr you.
