### ISSUE TITLE
Adding Manual Request/Response for Read and Search interactions

### ISSUE THREAD

**Issue by athenaecascketta** [hapifhir/hapi-fhir#5929]
I see that manual requests and responses are supported only for Operation interactions, I was wondering if there's a reason it's not for others?

I have a potential use case that would utilize manual responses for Read and/or Search and I was wondering if there would be any barriers to my team contributing that change? I'm asking before we put in any work to make that change in case the PR gets denied for architectural/conceptual reasons.

**Comment by jamesagnew** [comment]
@athenaecascketta There's no real reason other than we just didn't think it would be useful to anyone. 

Are you envisioning adding a `manualResponse()` element to the `@Read` and `@Search` annotations? Certainly if you wanted to contribute a patch that did just that, we'd be willing to accept it (assuming it included tests and documentation).

**Comment by athenaecascketta** [comment]
@jamesagnew Yes all we need is manualResponse for @Read and @Search.  

Would you be fine if that's the only change I made? Or would you rather we also do the same for manualRequest and reflect this for other interactions as well? Of course also with the requisite changes to documentation and tests.

And to make sure my understanding is correct this would only require a change to the annotations and the corresponding method bindings (along with tests and docs), do I have that right?
