### ISSUE TITLE
Unable to JSON parse Appointment resource

### ISSUE THREAD

**Issue by phommata** [hapifhir/hapi-fhir#5947]
**Describe the bug**
Unable to JSON parse Appointment resource similar to Patient example.

`ca.uhn.fhir.context.ConfigurationException: HAPI-1716: Resource class[org.hl7.fhir.r4.model.Encounter] does not contain any valid HAPI-FHIR annotations`

**To Reproduce**
Setup steps

1. Run JDK 17
2. Run Mirth Connect 4.5.0
3. Download Hapi FHIR 7.2.0 to custom-libs from [GitHub releases](https://github.com/hapifhir/hapi-fhir/releases/tag/v7.2.0)

1. Run code below in a JavaScript destination connector 
`// Create a HAPI FHIR context for FHIR
var context = new Packages.ca.uhn.fhir.context.FhirContext.forR4();

// Instantiate a new parser
var parser = ctx.newJsonParser();

var input = {
{
"resourceType" : "Appointment",
"status" : "booked"
};

// Parse it
var appointment = parser.parseResource(Packages.org.hl7.fhir.r4.model.Appointment, JSON.stringify(input));`

2. See error

**Expected behavior**
JSON parse of string to Appointment object.

**Screenshots**
None.

**Environment (please complete the following information):**
 - HAPI FHIR Version 7.2.0
 - OS: Windows
 - Mirth 4.5.0

**Additional context**
None

**Comment by jamesagnew** [comment]
The correct package for the Appointment resource is `org.hl7.fhir.r4.model.Appointment`, not `Packages.org.hl7.fhir.r4.model.Appointment`. I don't know what the Packages part refers to, but presumably that's a Mirth thing? I think you'd probably have to open a ticket with Mirth about this, unless you can supply a unit test that we can run outside of Mirth that reproduces this issue - There is definitely no issues with the Appointment resource, we have many many projects which successfully parse it.

**Comment by phommata** [comment]
It's specific to the Rhino.js that Mirth uses for translating JavaScript to Java. This might be an issue with that.
