### ISSUE TITLE
Default setting of isEnabledValidationForCodingsLogicalAnd() is wrong way round

### ISSUE THREAD

**Issue by stueynz** [hapifhir/hapi-fhir#6069]
Way back in Jan-2023 @lukedegruchy opened an issue [Inconsistent validation of language codes](https://github.com/hapifhir/hapi-fhir/issues/4461).   The resulting [pull request](https://github.com/hapifhir/hapi-fhir/commit/1755eb46e67329fb72636b663d42622e1e6c5d49) included a [commit](https://github.com/hapifhir/hapi-fhir/commit/1755eb46e67329fb72636b663d42622e1e6c5d49#diff-d8e47a5bb9c7cc151bf6f1bb31f822f76a7a5384b38a9c8765986bfc4c7f11af) that added a new validation configuration variable `IValidationContext..isEnabledValidationForCodingsLogicalAnd()`

![image](https://github.com/hapifhir/hapi-fhir/assets/7577039/10d9f34d-9167-47f6-bf72-3e3db7263a42)
 
The effect of the new config variable was:
* `false` - validation will return OK if there is **at least one** valid coding that matched the binding.
* `true` - validation will return OK **only if all** codings match the binding.

The default value for the new config variable was `false` which meant that validation would return OK if there was **at least one** valid coding that matched the binding.  This meant that default 'out of the box' codeset validation behaviour continued as before.

Then in until early June-2024 when [Core Library Bump 6.3.11](https://github.com/hapifhir/hapi-fhir/pull/5772) included a [commit](https://github.com/hapifhir/hapi-fhir/commit/4f491e8ee31d75abc64b2613154232b08efd8ff4) pull request that re-worked the codeset validation problem.

![image](https://github.com/hapifhir/hapi-fhir/assets/7577039/2f25efe5-030d-4460-bc5f-85b52675db46)

The re-worked code for implementing the desired effect of the `IValidationContext..isEnabledValidationForCodingsLogicalAnd()` reversed the meaning of the validation variable:  
* `true` - validation will return OK if there is **at least one** valid coding that matched the binding.
* `false` - validation will return OK **only if all** codings match the binding.

The [Core Library Bump 6.3.11](https://github.com/hapifhir/hapi-fhir/pull/5772) pull request included a [comment from @dotasek](https://github.com/hapifhir/hapi-fhir/pull/5772#issuecomment-2150261005) suggesting that the variable be renamed.  With the reversal of the meaning of `true` and `false` values, it probably should be.

**The Actual Problem:** The re-working of this code in [Core Library Bump 6.3.11](https://github.com/hapifhir/hapi-fhir/pull/5772) reversed the  behaviour of the config variable, **without reversing the default setting**, to ensure default behaviour that was consistent with historical behaviour.  ie: [This code](https://github.com/hapifhir/hapi-fhir/commit/1755eb46e67329fb72636b663d42622e1e6c5d49#diff-1d95203ff8a82d5250cff67861b073667e586f7f189486b055ecff5969b79f79) should set the default value to `true`

**Why I care:** In my IG we have made extensive use of [additional bindings](https://build.fhir.org/ig/FHIR/fhir-tools-ig/StructureDefinition-additional-binding.html) which means we have numerous codeable concepts with multiple bindings; which are now failing validation in the HAPI-FHIR validator because the default codeset validation behaviour has changed.

Is it unreasonable to expect the default out-of-the box behaviour to remain unchanged when new functionality is added?

**Comment by dotasek** [comment]
@stueynz there were several test cases that specified this behaviour: https://github.com/hapifhir/hapi-fhir/blame/724339c8861d61c3e6c62cb27024653d01b58335/hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorR4Test.java#L1780-1838

The only one of these that changed was https://github.com/hapifhir/hapi-fhir/blame/724339c8861d61c3e6c62cb27024653d01b58335/hapi-fhir-validation/src/test/java/org/hl7/fhir/r4/validation/FhirInstanceValidatorR4Test.java#L1797

In that case, I believe the original test case was expecting the incorrect result. Regardless of the `...LogicalAndSupport` setting, there are no valid codes present in this case (only an invalid `en_US` code) and this should never be valid. 

None of the other test cases covering this setting have changed. The behaviour should otherwise be as it was.

Is this actually what is impacting your validation? Is there a replicable example of what was previously valid that is no longer?

**Comment by stueynz** [comment]
I'm not questioning the test-cases or the functionality of the validation code.  It all works as expected, except for the default setting in the IValidationSupport interface which is `false`, meaning when validating multiple codings **all of them** must match the bound ValueSet. 

I've got some fixes to [ValidationCLI](https://github.com/hapifhir/hapi-fhir/commit/7835064044fed6e59e8024513409e21c9eca9061) fixes in my fork; just checking if there's anything I've missed before doing a PullRequest.

What I'm really asking:  Is my logic about default settings preserving historical behaviour coherent?  Should I just change the default setting in IValidationSupport ??

**Comment by dotasek** [comment]
@stueynz Thank you for checking. I did a similar exploration myself before my initial reply. 

@lukedegruchy and myself had a discussion about this yesterday, and believe we should revise the documentation to make this setting clearer.
