### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by anishn013** [hapifhir/hapi-fhir#6145]
Can we customize the validator in a way where we can omit the use of value set validation and still continue to use the rest of the validators from hapi-fhir-base lib. If so, could you please explain.

**Comment by jamesagnew** [comment]
Please don't use GitHub issues to ask questions. See [Getting Help](https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help) in our wiki for details on how to request help for HAPI FHIR.
