### ISSUE TITLE
Referential integrity not checked on DiagnosticReport.ImagingStudy

### ISSUE THREAD

**Issue by mkaehlershs** [hapifhir/hapi-fhir#6162]
**Describe the bug**
Referential integrity is not checked for Insert/Update/Delete operations on DiagnosticReport.ImagingStudy reference

**To Reproduce**

1. Post [bundle.json](https://github.com/user-attachments/files/16390447/bundle.json) to HAPI Server
2. Delete ImagingStudyExample resource (DELETE [base]/ImagingStudy/ImagingStudyExample)
HAPI allows deletion of ImagingStudy resource also in case there are DiagnosticReport resources referring to it.

**Expected behavior**
Hapi should throw Error 409 Conflict, as it does when I try to delete the patient.

**Environment (please complete the following information):**
 - HAPI v6.8.3, v6.10.1, v7.2.0
 - OS: Docker

**Additional context**
For other reference fields like basedOn or subject the referential integrity is checked correctly. Maybe the reason is, that there is no search parameter for DiagnosticReport.imagingStudy

**Comment by jamesagnew** [comment]
Referential integrity is not checked for elements that do not have an associated search parameter.

The default search parameters in R4 do not include an SP on `DiagnosticReport.imagingStudy`, so if you want referential integrity checking on that field, you need to add an SP with that path.

Note that FHIR R5 addresses this and adds an SP on the study element.

**Comment by mkaehlershs** [comment]
Ok, Thanks for that clear answer.
