### ISSUE TITLE
Tests failing when building the hapi-fhir-test-utilities module

### ISSUE THREAD

**Issue by alexandre-savaris** [hapifhir/hapi-fhir#6214]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
When building the hapi-fhir-test-utilities module, some tests fail.

**To Reproduce**
1. After cloning the HAPI FHIR project, go to the 'hapi-fhir-test-utilities' directory.
2. Execute: 'mvn clean install'
3. The output includes messages indicating the failing tests.

**Expected behavior**
The test set should be executed without errors.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 7.5.0-SNAPSHOT
 - OS: Windows 11 Pro 23H2

**Additional context**
When debugging the failures, it seems there are issues regarding line breaks ("\n" versus "\r\n") when the tests assert JSON keys and values.

[mvn_output.txt](https://github.com/user-attachments/files/16604583/mvn_output.txt)

**Comment by tadgh** [comment]
Hey there, are you building on windows?

We don't currently support that. Linux and Mac are the two targets for building that we test on. We could probably fix these particular tests but its just playing whack a mole with line endings.

If you need to just build it locally, you are free to skip the tests using `-DskipTests` on your maven command. Most tests will be unaffected by this problem, but there are certainly a whole class of them that will not pass on windows.

**Comment by alexandre-savaris** [comment]
Hello, Tadhg.

Thank you for responding so quickly!

OK. I'm moving to Linux for further development.

Best regards,
Alexandre Savaris.
