### ISSUE TITLE
Extreme validation slowdown due to changed primitive type check implementation

### ISSUE THREAD

**Issue by Boereck** [hapifhir/hapi-fhir#6252]
**Describe the bug**
We noticed an extreme slowdown of resource validation in our project when switching to HAPI 7.4.0. Instead of minutes the validation takes hours. We profiled the application and found out that almost 100% of the time was spent in `VersionSpecificWorkerContextWrapper#isPrimitiveType(String)`. The code is always traversing all `StructureDefinition`s to check if any type that is primitive has a matching name.

**To Reproduce**
Validate a resource with lots of `StructureDefinition`s available to the ValidationContext, triggering `isPrimitive` call. The simplest is a CodeSystem, since constraint `csd-1` triggers a lot of those calls when evaluating the `isDistinct` function.

**Expected behavior**
The expected behavior would be a reasonable evaluation time of `isPrimitive(String)`.  
We would suggest to add a field of type `Set<String>` of names of primitive types to `VersionSpecificWorkerContextWrapper` to cache the names of all primitive types, similar to how it is done for all known `StructureDefinition`s already.

If it is wanted, we can work on a PR implementing the suggested solution.

**Environment (please complete the following information):**
 - HAPI FHIR Version 7.4.0

**Comment by jamesagnew** [comment]
Thanks for the submission! That does sound like an issue. For what it's worth, a PR implementing the fix you propose would be gladly accepted.

**Comment by jamesagnew** [comment]
Possibly related to #6091
