### ISSUE TITLE
Any open source contributor got the access of the ca.uhn dependency?

### ISSUE THREAD

**Issue by Solodye** [hapifhir/hapi-fhir#6336]
https://github.com/hapifhir/hapi-fhir/blob/6bb72e445d759fa3d5fcc07e42b68fc2bc0a2816/pom.xml#L1069

**Comment by dotasek** [comment]
This is the project that builds that artifact: https://github.com/hapifhir/org.hl7.fhir.core

Feel free to follow up with any issues/PRs in that repository.
