### ISSUE TITLE
Search returns wrong results that do not match the query

### ISSUE THREAD

**Issue by G-2-Z** [hapifhir/hapi-fhir#6555]
**Describe the bug**
Resources can somehow get bricked where they will be wrongly returned as search results in JPA server. 
We search for Tasks for a specific patients that are in status 'ready'. Sometimes this will also return Tasks that were updated to status 'completed'. The resource in the resulting bundle will also show status 'completed'. If a resource is affected by this, it will always be returned wrongly. But not all resources are affected. See screenshots below. 
The affected resources will also be correctly return if searched for status 'completed'.
I already had a look at the HFJ_SPIDX_TOKEN table. The values and hashes there look correct.
Any idea what's happening here?

**To Reproduce**
Cannot reproduce. Seems random.

**Expected behavior**
Returned 'searchset' Bundle should only contain Tasks with status 'ready'.

**Screenshots**

![screenshot_1](https://github.com/user-attachments/assets/5ba0d717-d8c8-40d8-b55f-796f87f499cb)
![screenshot_2](https://github.com/user-attachments/assets/2b9dee9a-9e30-4659-a2af-6a9bb1492b24)

**Environment (please complete the following information):**
 - HAPI FHIR Version: 7.2.3
 - OS: Inside container based on distroless debian
 - DB: PostgreSQL 16

**Comment by jamesagnew** [comment]
There isn't really enough information here to be able to do much with it. If you can provide steps to reproduce this will be much more likely to see attention. Definitely a first step would be to ensure that it is still happening for you on the current release of HAPI FHIR.

**Comment by G-2-Z** [comment]
We found out, that we had corrupted our DB externally on the affected environment which caused this issue. However, we have not found out which defect specifically led to this behavior.
