### ISSUE TITLE
hapi-fhir-structures-r4 not compatible with recent  org.hl7.fhir.r4 6.4.1+ (interface method fetchResourcesByType() not implemented)

### ISSUE THREAD

**Issue by belpk** [hapifhir/hapi-fhir#6572]
Using the latest **_hapi-fhir-structures-r4 7.6.0_** together with a recent ca.uhn.hapi.fhir:**_org.hl7.fhir.r4 6.4.1_** or later (latest is currently 6.5.1) fails with an Error:

`AbstractMethod Receiver class org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext does not define or inherit an implementation of the resolved method 'abstract java.util.List fetchResourcesByType(java.lang.Class)' of interface org.hl7.fhir.r4.context.IWorkerContext.`

I know that the pom of hapi-fhir-structures-r4 7.6.0 depends on org.hl7.fhir.r4 _6.4.0_, which is the minimal version we should use since recently 2 CVE's were found in the previous version. But it's not uncommon for updating further to more recent org.hl7.fhir.r4 versions explicitly: to keep up-to-date; maybe as common practice; maybe to get some more recent changes; etc. Or for any other reason that independently from the above transitive maven dependency a more recent org.hl7.fhir.r4 version ends up in the application classpath. Especially when it merely looks like simple corrective versions 6.4.1, 6.4.2, etc. bumping up a version should normally be an 'innocent' operation.

Essentially the issue is, 
### in repo org.hl7.fhir.core/org.hl7.fhir.r4
In interface **org.hl7.fhir.r4.context.IWorkerContext.java** ,
on Oct 31, the abstract method 

` public <T extends Resource> List<T> fetchResourcesByType(Class<T> class_);`

was added.

### in repo hapi-fhir/hapi-fhir-structures-r4
The implementing class **org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.java**

does _not_ implement this interface method.
Which Java requires , as it's not a default interface method.
Which can obviously result in errors, even very late at runtime.

**Comment by jamesagnew** [comment]
Using the wrong version of the org.hl7 libraries is not supported. Every version of HAPI FHIR is pinned to exactly one version of the org.hl7.fhir libraries. We upgrade the two in sync with every quarterly release.
